const CHARS_PER_TOKEN: Record<string, number> = {
  o200k_base: 3.7, cl100k_base: 4.0, claude: 3.5, gemini: 3.8, grok: 3.7, llama: 3.6, mistral: 3.6, deepseek: 3.5, qwen: 3.2, command: 3.8,
};
export function estimateTokens(text: string, tokenizer = 'cl100k_base'): number {
  if (!text) return 0;
  const cpt = CHARS_PER_TOKEN[tokenizer] ?? 4;
  const words = text.trim().split(/\s+/).length;
  const byChars = text.length / cpt;
  const byWords = words * 1.3;
  return Math.max(1, Math.round((byChars + byWords) / 2));
}
export function estimateRequestTokens(messages: Array<{ content: string }>, tokenizer?: string): number {
  const joined = messages.map((m) => m.content).join('\n');
  return estimateTokens(joined, tokenizer) + messages.length * 4;
}
export function costUsd(inputTokens: number, outputTokens: number, inputPerMillion: number, outputPerMillion: number, cachedTokens = 0, cachedPerMillion = 0): number {
  const uncached = Math.max(0, inputTokens - cachedTokens);
  return (uncached * inputPerMillion + cachedTokens * (cachedPerMillion || inputPerMillion * 0.25) + outputTokens * outputPerMillion) / 1_000_000;
}
export const TOKEN_SHAPE_TABLE: Array<{ kind: string; sample: string; tokens: number }> = [
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. ', tokens: 17 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 35 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 52 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 70 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 87 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 105 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 122 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 140 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 157 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 175 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 192 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 210 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 227 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 245 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 262 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 280 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 297 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 315 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 332 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 350 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 367 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 385 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 402 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 420 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 437 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 455 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 472 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 490 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 507 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 525 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 542 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 560 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 577 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 595 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 612 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 630 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 647 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 665 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 682 },
  { kind: 'english', sample: 'The gateway reserved budget before the provider ever saw the request. The gatewa', tokens: 700 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } ', tokens: 17 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 34 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 51 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 69 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 86 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 103 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 120 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 138 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 155 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 172 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 189 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 207 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 224 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 241 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 258 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 276 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 293 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 310 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 327 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 345 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 362 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 379 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 396 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 414 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 431 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 448 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 465 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 483 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 500 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 517 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 534 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 552 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 569 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 586 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 603 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 621 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 638 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 655 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 672 },
  { kind: 'code', sample: 'export function handle(req: CanonicalRequest) { return route(req); } export func', tokens: 690 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} ', tokens: 12 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 25 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 38 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 51 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 63 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 76 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 89 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 102 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 114 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 127 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 140 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 153 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 165 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 178 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 191 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 204 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 216 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 229 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 242 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 255 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 267 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 280 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 293 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 306 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 318 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 331 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 344 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 357 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 369 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 382 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 395 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 408 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 420 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 433 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 446 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 459 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 471 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 484 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 497 },
  { kind: 'json', sample: '{"alias":"company-approved-fast","max_tokens":512} {"alias":"company-approved-fa', tokens: 510 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 ', tokens: 5 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 ', tokens: 11 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 ', tokens: 16 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 22 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 27 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 33 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 38 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 44 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 49 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 55 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 60 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 66 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 71 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 77 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 82 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 88 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 93 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 99 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 104 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 110 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 115 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 121 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 126 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 132 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 137 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 143 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 148 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 154 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 159 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 165 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 170 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 176 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 181 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 187 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 192 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 198 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 203 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 209 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 214 },
  { kind: 'cjk', sample: '把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里，再决定路由。 把每一次模型调用都放进预算里', tokens: 220 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. ', tokens: 6 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. ', tokens: 12 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. ', tokens: 18 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 24 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 30 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 36 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 42 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 48 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 54 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 60 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 66 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 72 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 78 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 84 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 90 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 96 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 102 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 108 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 114 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 120 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 126 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 132 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 138 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 144 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 150 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 156 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 162 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 168 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 174 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 180 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 186 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 192 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 198 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 204 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 210 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 216 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 222 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 228 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 234 },
  { kind: 'emoji-avoid', sample: 'Hold the line on spend. Hold the line on spend. Hold the line on spend. Hold the', tokens: 240 },
];
