import type { Modality, ModelSpec, Protocol } from "../types";

export const ALIBABA_MODELS: ModelSpec[] = [
  {
    id: 'alibaba/qwen3-235b',
    provider: 'alibaba',
    displayName: 'Qwen3 235B via alibaba',
    family: 'Qwen',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.2,
    outputPerMillion: 0.6,
    cachedInputPerMillion: 0.05,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-west', 'asia-east'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'Qwen3 235B via alibaba (alibaba/qwen3-235b) is a frontier Qwen model hosted by alibaba. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.2/M input tokens and $0.6/M output tokens, with cached input at $0.05/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['alibaba/qwen3-32b', 'alibaba/qwen2.5-72b', 'alibaba/qwen2.5-coder-32b'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'alibaba/qwen3-32b',
    provider: 'alibaba',
    displayName: 'Qwen3 32B via alibaba',
    family: 'Qwen',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.1,
    outputPerMillion: 0.3,
    cachedInputPerMillion: 0.025,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-west', 'asia-east'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen3 32B via alibaba (alibaba/qwen3-32b) is a workhorse Qwen model hosted by alibaba. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.1/M input tokens and $0.3/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['alibaba/qwen2.5-72b', 'alibaba/qwen2.5-coder-32b', 'alibaba/qwen-vl-max'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'alibaba/qwen2.5-72b',
    provider: 'alibaba',
    displayName: 'Qwen2.5 72B via alibaba',
    family: 'Qwen',
    release: '2024-09',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.12,
    outputPerMillion: 0.39,
    cachedInputPerMillion: 0.03,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-west', 'asia-east'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen2.5 72B via alibaba (alibaba/qwen2.5-72b) is a workhorse Qwen model hosted by alibaba. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.12/M input tokens and $0.39/M output tokens, with cached input at $0.03/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['alibaba/qwen3-32b', 'alibaba/qwen2.5-coder-32b', 'alibaba/qwen-vl-max'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'alibaba/qwen2.5-coder-32b',
    provider: 'alibaba',
    displayName: 'Qwen2.5 Coder 32B via alibaba',
    family: 'Qwen',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.08,
    outputPerMillion: 0.18,
    cachedInputPerMillion: 0.02,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-west', 'asia-east'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen2.5 Coder 32B via alibaba (alibaba/qwen2.5-coder-32b) is a workhorse Qwen model hosted by alibaba. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.08/M input tokens and $0.18/M output tokens, with cached input at $0.02/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['alibaba/qwen3-32b', 'alibaba/qwen2.5-72b', 'alibaba/qwen-vl-max'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'alibaba/qwen-vl-max',
    provider: 'alibaba',
    displayName: 'Qwen VL Max via alibaba',
    family: 'Qwen',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 32768,
    maxOutput: 8192,
    inputPerMillion: 0.8,
    outputPerMillion: 3.2,
    cachedInputPerMillion: 0.2,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-west', 'asia-east'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'Qwen VL Max via alibaba (alibaba/qwen-vl-max) is a workhorse Qwen model hosted by alibaba. It speaks openai-chat with a 32,768 token context window and a 8,192 token output cap. List price is $0.8/M input tokens and $3.2/M output tokens, with cached input at $0.2/M. Modalities: text, tools, json, code, vision. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['alibaba/qwen3-32b', 'alibaba/qwen2.5-72b', 'alibaba/qwen2.5-coder-32b'],
    carbonGPerMTok: 1.6,
  },
];

export const ALIBABA_MODEL_COUNT = ALIBABA_MODELS.length;

export const MODEL_DOC_alibaba_qwen3_235b = {
  id: 'alibaba/qwen3-235b',
  summary: 'Qwen3 235B via alibaba (alibaba/qwen3-235b) is a frontier Qwen model hosted by alibaba. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.2/M input tokens and $0.6/M output tokens, with cached input at $0.05/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer alibaba/qwen3-235b when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0007.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_alibaba_qwen3_32b = {
  id: 'alibaba/qwen3-32b',
  summary: 'Qwen3 32B via alibaba (alibaba/qwen3-32b) is a workhorse Qwen model hosted by alibaba. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.1/M input tokens and $0.3/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer alibaba/qwen3-32b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00035.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_alibaba_qwen2_5_72b = {
  id: 'alibaba/qwen2.5-72b',
  summary: 'Qwen2.5 72B via alibaba (alibaba/qwen2.5-72b) is a workhorse Qwen model hosted by alibaba. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.12/M input tokens and $0.39/M output tokens, with cached input at $0.03/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
  routingHints: [
    'Prefer alibaba/qwen2.5-72b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000435.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_alibaba_qwen2_5_coder_32b = {
  id: 'alibaba/qwen2.5-coder-32b',
  summary: 'Qwen2.5 Coder 32B via alibaba (alibaba/qwen2.5-coder-32b) is a workhorse Qwen model hosted by alibaba. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.08/M input tokens and $0.18/M output tokens, with cached input at $0.02/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer alibaba/qwen2.5-coder-32b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00025.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_alibaba_qwen_vl_max = {
  id: 'alibaba/qwen-vl-max',
  summary: 'Qwen VL Max via alibaba (alibaba/qwen-vl-max) is a workhorse Qwen model hosted by alibaba. It speaks openai-chat with a 32,768 token context window and a 8,192 token output cap. List price is $0.8/M input tokens and $3.2/M output tokens, with cached input at $0.2/M. Modalities: text, tools, json, code, vision. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer alibaba/qwen-vl-max when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0032.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

