import type { Modality, ModelSpec, Protocol } from "../types";

export const ANTHROPIC_MODELS: ModelSpec[] = [
  {
    id: 'anthropic/claude-opus-4.1',
    provider: 'anthropic',
    displayName: 'Claude Opus 4.1',
    family: 'claude-4',
    release: '2025-08',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'anthropic-messages' as Protocol,
    contextWindow: 200000,
    maxOutput: 32000,
    inputPerMillion: 15.0,
    outputPerMillion: 75.0,
    cachedInputPerMillion: 1.5,
    tokenizer: 'claude',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-central'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'Claude Opus 4.1 (anthropic/claude-opus-4.1) is a frontier claude-4 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 32,000 token output cap. List price is $15.0/M input tokens and $75.0/M output tokens, with cached input at $1.5/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: claude. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['anthropic/claude-sonnet-4.5', 'anthropic/claude-sonnet-4', 'anthropic/claude-haiku-4.5'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'anthropic/claude-opus-4',
    provider: 'anthropic',
    displayName: 'Claude Opus 4',
    family: 'claude-4',
    release: '2025-05',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'anthropic-messages' as Protocol,
    contextWindow: 200000,
    maxOutput: 32000,
    inputPerMillion: 15.0,
    outputPerMillion: 75.0,
    cachedInputPerMillion: 1.5,
    tokenizer: 'claude',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-central'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'Claude Opus 4 (anthropic/claude-opus-4) is a frontier claude-4 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 32,000 token output cap. List price is $15.0/M input tokens and $75.0/M output tokens, with cached input at $1.5/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: claude. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-05.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['anthropic/claude-sonnet-4.5', 'anthropic/claude-sonnet-4', 'anthropic/claude-haiku-4.5'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'anthropic/claude-sonnet-4.5',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 4.5',
    family: 'claude-4',
    release: '2025-11',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'anthropic-messages' as Protocol,
    contextWindow: 200000,
    maxOutput: 64000,
    inputPerMillion: 3.0,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.3,
    tokenizer: 'claude',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-central'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Claude Sonnet 4.5 (anthropic/claude-sonnet-4.5) is a workhorse claude-4 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 64,000 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.3/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: claude. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-11.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['anthropic/claude-sonnet-4', 'anthropic/claude-haiku-4.5', 'anthropic/claude-3-5-sonnet'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'anthropic/claude-sonnet-4',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 4',
    family: 'claude-4',
    release: '2025-05',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'anthropic-messages' as Protocol,
    contextWindow: 200000,
    maxOutput: 64000,
    inputPerMillion: 3.0,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.3,
    tokenizer: 'claude',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-central'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Claude Sonnet 4 (anthropic/claude-sonnet-4) is a workhorse claude-4 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 64,000 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.3/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: claude. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-05.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['anthropic/claude-sonnet-4.5', 'anthropic/claude-haiku-4.5', 'anthropic/claude-3-5-sonnet'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'anthropic/claude-haiku-4.5',
    provider: 'anthropic',
    displayName: 'Claude Haiku 4.5',
    family: 'claude-4',
    release: '2025-10',
    modality: ['text', 'vision', 'tools', 'json', 'code'] as Modality[],
    protocol: 'anthropic-messages' as Protocol,
    contextWindow: 200000,
    maxOutput: 8192,
    inputPerMillion: 0.8,
    outputPerMillion: 4.0,
    cachedInputPerMillion: 0.08,
    tokenizer: 'claude',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-central'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Claude Haiku 4.5 (anthropic/claude-haiku-4.5) is a utility claude-4 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 8,192 token output cap. List price is $0.8/M input tokens and $4.0/M output tokens, with cached input at $0.08/M. Modalities: text, vision, tools, json, code. Tokenizer: claude. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-10.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['anthropic/claude-sonnet-4.5', 'anthropic/claude-sonnet-4', 'anthropic/claude-3-5-sonnet'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'anthropic/claude-3-5-sonnet',
    provider: 'anthropic',
    displayName: 'Claude 3.5 Sonnet',
    family: 'claude-3',
    release: '2024-10',
    modality: ['text', 'vision', 'tools', 'json', 'code'] as Modality[],
    protocol: 'anthropic-messages' as Protocol,
    contextWindow: 200000,
    maxOutput: 8192,
    inputPerMillion: 3.0,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.3,
    tokenizer: 'claude',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-central'],
    status: 'legacy',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Claude 3.5 Sonnet (anthropic/claude-3-5-sonnet) is a workhorse claude-3 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 8,192 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.3/M. Modalities: text, vision, tools, json, code. Tokenizer: claude. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: legacy. Released 2024-10.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['anthropic/claude-sonnet-4.5', 'anthropic/claude-sonnet-4', 'anthropic/claude-haiku-4.5'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'anthropic/claude-3-5-haiku',
    provider: 'anthropic',
    displayName: 'Claude 3.5 Haiku',
    family: 'claude-3',
    release: '2024-10',
    modality: ['text', 'vision', 'tools', 'json', 'code'] as Modality[],
    protocol: 'anthropic-messages' as Protocol,
    contextWindow: 200000,
    maxOutput: 8192,
    inputPerMillion: 0.8,
    outputPerMillion: 4.0,
    cachedInputPerMillion: 0.08,
    tokenizer: 'claude',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-central'],
    status: 'legacy',
    speedClass: 'fast',
    qualityClass: 'utility',
    notes: 'Claude 3.5 Haiku (anthropic/claude-3-5-haiku) is a utility claude-3 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 8,192 token output cap. List price is $0.8/M input tokens and $4.0/M output tokens, with cached input at $0.08/M. Modalities: text, vision, tools, json, code. Tokenizer: claude. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: legacy. Released 2024-10.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['anthropic/claude-sonnet-4.5', 'anthropic/claude-sonnet-4', 'anthropic/claude-haiku-4.5'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'anthropic/claude-3-opus',
    provider: 'anthropic',
    displayName: 'Claude 3 Opus',
    family: 'claude-3',
    release: '2024-03',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'anthropic-messages' as Protocol,
    contextWindow: 200000,
    maxOutput: 4096,
    inputPerMillion: 15.0,
    outputPerMillion: 75.0,
    cachedInputPerMillion: undefined,
    tokenizer: 'claude',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-central'],
    status: 'deprecated',
    speedClass: 'slow',
    qualityClass: 'frontier',
    notes: 'Claude 3 Opus (anthropic/claude-3-opus) is a frontier claude-3 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 4,096 token output cap. List price is $15.0/M input tokens and $75.0/M output tokens. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: claude. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: deprecated. Released 2024-03.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['anthropic/claude-sonnet-4.5', 'anthropic/claude-sonnet-4', 'anthropic/claude-haiku-4.5'],
    carbonGPerMTok: 4.76,
  },
];

export const ANTHROPIC_MODEL_COUNT = ANTHROPIC_MODELS.length;

export const MODEL_DOC_anthropic_claude_opus_4_1 = {
  id: 'anthropic/claude-opus-4.1',
  summary: 'Claude Opus 4.1 (anthropic/claude-opus-4.1) is a frontier claude-4 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 32,000 token output cap. List price is $15.0/M input tokens and $75.0/M output tokens, with cached input at $1.5/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: claude. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
  routingHints: [
    'Prefer anthropic/claude-opus-4.1 when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0675.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol anthropic-messages; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_anthropic_claude_opus_4 = {
  id: 'anthropic/claude-opus-4',
  summary: 'Claude Opus 4 (anthropic/claude-opus-4) is a frontier claude-4 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 32,000 token output cap. List price is $15.0/M input tokens and $75.0/M output tokens, with cached input at $1.5/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: claude. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-05.',
  routingHints: [
    'Prefer anthropic/claude-opus-4 when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0675.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol anthropic-messages; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_anthropic_claude_sonnet_4_5 = {
  id: 'anthropic/claude-sonnet-4.5',
  summary: 'Claude Sonnet 4.5 (anthropic/claude-sonnet-4.5) is a workhorse claude-4 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 64,000 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.3/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: claude. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-11.',
  routingHints: [
    'Prefer anthropic/claude-sonnet-4.5 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0135.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol anthropic-messages; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_anthropic_claude_sonnet_4 = {
  id: 'anthropic/claude-sonnet-4',
  summary: 'Claude Sonnet 4 (anthropic/claude-sonnet-4) is a workhorse claude-4 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 64,000 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.3/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: claude. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-05.',
  routingHints: [
    'Prefer anthropic/claude-sonnet-4 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0135.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol anthropic-messages; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_anthropic_claude_haiku_4_5 = {
  id: 'anthropic/claude-haiku-4.5',
  summary: 'Claude Haiku 4.5 (anthropic/claude-haiku-4.5) is a utility claude-4 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 8,192 token output cap. List price is $0.8/M input tokens and $4.0/M output tokens, with cached input at $0.08/M. Modalities: text, vision, tools, json, code. Tokenizer: claude. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-10.',
  routingHints: [
    'Prefer anthropic/claude-haiku-4.5 when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0036.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol anthropic-messages; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_anthropic_claude_3_5_sonnet = {
  id: 'anthropic/claude-3-5-sonnet',
  summary: 'Claude 3.5 Sonnet (anthropic/claude-3-5-sonnet) is a workhorse claude-3 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 8,192 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.3/M. Modalities: text, vision, tools, json, code. Tokenizer: claude. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: legacy. Released 2024-10.',
  routingHints: [
    'Prefer anthropic/claude-3-5-sonnet when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0135.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol anthropic-messages; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_anthropic_claude_3_5_haiku = {
  id: 'anthropic/claude-3-5-haiku',
  summary: 'Claude 3.5 Haiku (anthropic/claude-3-5-haiku) is a utility claude-3 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 8,192 token output cap. List price is $0.8/M input tokens and $4.0/M output tokens, with cached input at $0.08/M. Modalities: text, vision, tools, json, code. Tokenizer: claude. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: legacy. Released 2024-10.',
  routingHints: [
    'Prefer anthropic/claude-3-5-haiku when quality class is utility and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0036.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol anthropic-messages; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_anthropic_claude_3_opus = {
  id: 'anthropic/claude-3-opus',
  summary: 'Claude 3 Opus (anthropic/claude-3-opus) is a frontier claude-3 model hosted by anthropic. It speaks anthropic-messages with a 200,000 token context window and a 4,096 token output cap. List price is $15.0/M input tokens and $75.0/M output tokens. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: claude. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: deprecated. Released 2024-03.',
  routingHints: [
    'Prefer anthropic/claude-3-opus when quality class is frontier and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0675.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol anthropic-messages; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

