import type { Modality, ModelSpec, Protocol } from "../types";

export const AZURE_MODELS: ModelSpec[] = [
  {
    id: 'azure/llama-4-maverick',
    provider: 'azure',
    displayName: 'Llama 4 Maverick via azure',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.324,
    outputPerMillion: 1.02,
    cachedInputPerMillion: 0.081,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Llama 4 Maverick via azure (azure/llama-4-maverick) is a frontier Llama model hosted by azure. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.324/M input tokens and $1.02/M output tokens, with cached input at $0.081/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'azure/llama-4-scout',
    provider: 'azure',
    displayName: 'Llama 4 Scout via azure',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.216,
    outputPerMillion: 0.708,
    cachedInputPerMillion: 0.054,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 4 Scout via azure (azure/llama-4-scout) is a workhorse Llama model hosted by azure. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.216/M input tokens and $0.708/M output tokens, with cached input at $0.054/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['azure/llama-3.3-70b', 'azure/llama-3.1-8b', 'azure/mistral-small-3.1'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'azure/llama-3.3-70b',
    provider: 'azure',
    displayName: 'Llama 3.3 70B via azure',
    family: 'Llama',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.708,
    outputPerMillion: 0.948,
    cachedInputPerMillion: 0.177,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 3.3 70B via azure (azure/llama-3.3-70b) is a workhorse Llama model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.708/M input tokens and $0.948/M output tokens, with cached input at $0.177/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.1-8b', 'azure/mistral-small-3.1'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'azure/llama-3.1-8b',
    provider: 'azure',
    displayName: 'Llama 3.1 8B via azure',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.06,
    outputPerMillion: 0.096,
    cachedInputPerMillion: 0.015,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Llama 3.1 8B via azure (azure/llama-3.1-8b) is a utility Llama model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.06/M input tokens and $0.096/M output tokens, with cached input at $0.015/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/mistral-small-3.1'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'azure/llama-3.1-405b',
    provider: 'azure',
    displayName: 'Llama 3.1 405B via azure',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 2.148,
    outputPerMillion: 2.148,
    cachedInputPerMillion: 0.537,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'frontier',
    notes: 'Llama 3.1 405B via azure (azure/llama-3.1-405b) is a frontier Llama model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.148/M input tokens and $2.148/M output tokens, with cached input at $0.537/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'azure/mistral-large-2411',
    provider: 'azure',
    displayName: 'Mistral Large 2411 via azure',
    family: 'Mistral',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 2.4,
    outputPerMillion: 7.2,
    cachedInputPerMillion: 0.6,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'Mistral Large 2411 via azure (azure/mistral-large-2411) is a frontier Mistral model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.4/M input tokens and $7.2/M output tokens, with cached input at $0.6/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'azure/mistral-small-3.1',
    provider: 'azure',
    displayName: 'Mistral Small 3.1 via azure',
    family: 'Mistral',
    release: '2025-03',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.12,
    outputPerMillion: 0.36,
    cachedInputPerMillion: 0.03,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Mistral Small 3.1 via azure (azure/mistral-small-3.1) is a workhorse Mistral model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.12/M input tokens and $0.36/M output tokens, with cached input at $0.03/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'azure/codestral-2501',
    provider: 'azure',
    displayName: 'Codestral 2501 via azure',
    family: 'Mistral',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 262144,
    maxOutput: 16384,
    inputPerMillion: 0.36,
    outputPerMillion: 1.08,
    cachedInputPerMillion: 0.09,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Codestral 2501 via azure (azure/codestral-2501) is a workhorse Mistral model hosted by azure. It speaks openai-chat with a 262,144 token context window and a 16,384 token output cap. List price is $0.36/M input tokens and $1.08/M output tokens, with cached input at $0.09/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'azure/pixtral-large',
    provider: 'azure',
    displayName: 'Pixtral Large via azure',
    family: 'Mistral',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 2.4,
    outputPerMillion: 7.2,
    cachedInputPerMillion: 0.6,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'Pixtral Large via azure (azure/pixtral-large) is a workhorse Mistral model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.4/M input tokens and $7.2/M output tokens, with cached input at $0.6/M. Modalities: text, tools, json, code, vision. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 1.6,
  },
  {
    id: 'azure/ministral-8b',
    provider: 'azure',
    displayName: 'Ministral 8B via azure',
    family: 'Mistral',
    release: '2024-10',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.12,
    outputPerMillion: 0.12,
    cachedInputPerMillion: 0.03,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Ministral 8B via azure (azure/ministral-8b) is a utility Mistral model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.12/M input tokens and $0.12/M output tokens, with cached input at $0.03/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-10.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'azure/gpt-4o',
    provider: 'azure',
    displayName: 'GPT-4o on Azure',
    family: 'gpt-4o',
    release: '2024-05',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 128000,
    maxOutput: 16384,
    inputPerMillion: 2.5,
    outputPerMillion: 10.0,
    cachedInputPerMillion: 1.25,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'GPT-4o on Azure (azure/gpt-4o) is a workhorse gpt-4o model hosted by azure. It speaks openai-chat with a 128,000 token context window and a 16,384 token output cap. List price is $2.5/M input tokens and $10.0/M output tokens, with cached input at $1.25/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-05.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'azure/gpt-4o-mini',
    provider: 'azure',
    displayName: 'GPT-4o mini on Azure',
    family: 'gpt-4o',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 128000,
    maxOutput: 16384,
    inputPerMillion: 0.15,
    outputPerMillion: 0.6,
    cachedInputPerMillion: 0.075,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'utility',
    notes: 'GPT-4o mini on Azure (azure/gpt-4o-mini) is a utility gpt-4o model hosted by azure. It speaks openai-chat with a 128,000 token context window and a 16,384 token output cap. List price is $0.15/M input tokens and $0.6/M output tokens, with cached input at $0.075/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'azure/gpt-4.1',
    provider: 'azure',
    displayName: 'GPT-4.1 on Azure',
    family: 'gpt-4.1',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1047576,
    maxOutput: 32768,
    inputPerMillion: 2.0,
    outputPerMillion: 8.0,
    cachedInputPerMillion: 0.5,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'GPT-4.1 on Azure (azure/gpt-4.1) is a workhorse gpt-4.1 model hosted by azure. It speaks openai-chat with a 1,047,576 token context window and a 32,768 token output cap. List price is $2.0/M input tokens and $8.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'azure/gpt-4.1-mini',
    provider: 'azure',
    displayName: 'GPT-4.1 mini on Azure',
    family: 'gpt-4.1',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1047576,
    maxOutput: 32768,
    inputPerMillion: 0.4,
    outputPerMillion: 1.6,
    cachedInputPerMillion: 0.1,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'GPT-4.1 mini on Azure (azure/gpt-4.1-mini) is a workhorse gpt-4.1 model hosted by azure. It speaks openai-chat with a 1,047,576 token context window and a 32,768 token output cap. List price is $0.4/M input tokens and $1.6/M output tokens, with cached input at $0.1/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'azure/gpt-4.1-nano',
    provider: 'azure',
    displayName: 'GPT-4.1 nano on Azure',
    family: 'gpt-4.1',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1047576,
    maxOutput: 32768,
    inputPerMillion: 0.1,
    outputPerMillion: 0.4,
    cachedInputPerMillion: 0.025,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'GPT-4.1 nano on Azure (azure/gpt-4.1-nano) is a utility gpt-4.1 model hosted by azure. It speaks openai-chat with a 1,047,576 token context window and a 32,768 token output cap. List price is $0.1/M input tokens and $0.4/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'azure/gpt-5',
    provider: 'azure',
    displayName: 'GPT-5 on Azure',
    family: 'gpt-5',
    release: '2025-08',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1047576,
    maxOutput: 65536,
    inputPerMillion: 5.0,
    outputPerMillion: 20.0,
    cachedInputPerMillion: 0.5,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'GPT-5 on Azure (azure/gpt-5) is a frontier gpt-5 model hosted by azure. It speaks openai-chat with a 1,047,576 token context window and a 65,536 token output cap. List price is $5.0/M input tokens and $20.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'azure/gpt-5-mini',
    provider: 'azure',
    displayName: 'GPT-5 mini on Azure',
    family: 'gpt-5',
    release: '2025-08',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 400000,
    maxOutput: 32768,
    inputPerMillion: 0.4,
    outputPerMillion: 1.6,
    cachedInputPerMillion: 0.1,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'GPT-5 mini on Azure (azure/gpt-5-mini) is a workhorse gpt-5 model hosted by azure. It speaks openai-chat with a 400,000 token context window and a 32,768 token output cap. List price is $0.4/M input tokens and $1.6/M output tokens, with cached input at $0.1/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'azure/gpt-5-nano',
    provider: 'azure',
    displayName: 'GPT-5 nano on Azure',
    family: 'gpt-5',
    release: '2025-08',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 400000,
    maxOutput: 16384,
    inputPerMillion: 0.1,
    outputPerMillion: 0.4,
    cachedInputPerMillion: 0.025,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'GPT-5 nano on Azure (azure/gpt-5-nano) is a utility gpt-5 model hosted by azure. It speaks openai-chat with a 400,000 token context window and a 16,384 token output cap. List price is $0.1/M input tokens and $0.4/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'azure/gpt-5-pro',
    provider: 'azure',
    displayName: 'GPT-5 pro on Azure',
    family: 'gpt-5',
    release: '2025-12',
    modality: ['text', 'tools', 'json', 'vision', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-responses' as Protocol,
    contextWindow: 1047576,
    maxOutput: 65536,
    inputPerMillion: 15.0,
    outputPerMillion: 60.0,
    cachedInputPerMillion: 1.5,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'reasoning',
    notes: 'GPT-5 pro on Azure (azure/gpt-5-pro) is a reasoning gpt-5 model hosted by azure. It speaks openai-responses with a 1,047,576 token context window and a 65,536 token output cap. List price is $15.0/M input tokens and $60.0/M output tokens, with cached input at $1.5/M. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-12.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'azure/o3',
    provider: 'azure',
    displayName: 'o3 on Azure',
    family: 'o-series',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'reasoning'] as Modality[],
    protocol: 'openai-responses' as Protocol,
    contextWindow: 200000,
    maxOutput: 100000,
    inputPerMillion: 10.0,
    outputPerMillion: 40.0,
    cachedInputPerMillion: 2.5,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'reasoning',
    notes: 'o3 on Azure (azure/o3) is a reasoning o-series model hosted by azure. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $10.0/M input tokens and $40.0/M output tokens, with cached input at $2.5/M. Modalities: text, tools, json, reasoning. Tokenizer: o200k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'azure/o3-mini',
    provider: 'azure',
    displayName: 'o3-mini on Azure',
    family: 'o-series',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'vision', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-responses' as Protocol,
    contextWindow: 200000,
    maxOutput: 100000,
    inputPerMillion: 1.1,
    outputPerMillion: 4.4,
    cachedInputPerMillion: 0.55,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'reasoning',
    notes: 'o3-mini on Azure (azure/o3-mini) is a reasoning o-series model hosted by azure. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $1.1/M input tokens and $4.4/M output tokens, with cached input at $0.55/M. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'azure/o4-mini',
    provider: 'azure',
    displayName: 'o4-mini on Azure',
    family: 'o-series',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'vision', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-responses' as Protocol,
    contextWindow: 200000,
    maxOutput: 100000,
    inputPerMillion: 1.1,
    outputPerMillion: 4.4,
    cachedInputPerMillion: 0.275,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'reasoning',
    notes: 'o4-mini on Azure (azure/o4-mini) is a reasoning o-series model hosted by azure. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $1.1/M input tokens and $4.4/M output tokens, with cached input at $0.275/M. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'azure/o1',
    provider: 'azure',
    displayName: 'o1 on Azure',
    family: 'o-series',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'reasoning'] as Modality[],
    protocol: 'openai-responses' as Protocol,
    contextWindow: 200000,
    maxOutput: 100000,
    inputPerMillion: 15.0,
    outputPerMillion: 60.0,
    cachedInputPerMillion: 7.5,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'reasoning',
    notes: 'o1 on Azure (azure/o1) is a reasoning o-series model hosted by azure. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $15.0/M input tokens and $60.0/M output tokens, with cached input at $7.5/M. Modalities: text, tools, json, reasoning. Tokenizer: o200k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'azure/o1-mini',
    provider: 'azure',
    displayName: 'o1-mini on Azure',
    family: 'o-series',
    release: '2024-09',
    modality: ['text', 'tools', 'json', 'vision', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-responses' as Protocol,
    contextWindow: 128000,
    maxOutput: 65536,
    inputPerMillion: 3.0,
    outputPerMillion: 12.0,
    cachedInputPerMillion: undefined,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'reasoning',
    notes: 'o1-mini on Azure (azure/o1-mini) is a reasoning o-series model hosted by azure. It speaks openai-responses with a 128,000 token context window and a 65,536 token output cap. List price is $3.0/M input tokens and $12.0/M output tokens. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'azure/text-embedding-3-small',
    provider: 'azure',
    displayName: 'Embedding 3 small on Azure',
    family: 'embeddings',
    release: '2024-01',
    modality: ['embed'] as Modality[],
    protocol: 'openai-embeddings' as Protocol,
    contextWindow: 8191,
    maxOutput: 0,
    inputPerMillion: 0.02,
    outputPerMillion: 0.0,
    cachedInputPerMillion: undefined,
    tokenizer: 'cl100k_base',
    streaming: false,
    tools: false,
    jsonMode: false,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Embedding 3 small on Azure (azure/text-embedding-3-small) is a utility embeddings model hosted by azure. It speaks openai-embeddings with a 8,191 token context window and a 0 token output cap. List price is $0.02/M input tokens and $0.0/M output tokens. Modalities: embed. Tokenizer: cl100k_base. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-01.',
    useCases: ['semantic search', 'cluster labeling', 'cache keys', 'dedup'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'azure/text-embedding-3-large',
    provider: 'azure',
    displayName: 'Embedding 3 large on Azure',
    family: 'embeddings',
    release: '2024-01',
    modality: ['embed'] as Modality[],
    protocol: 'openai-embeddings' as Protocol,
    contextWindow: 8191,
    maxOutput: 0,
    inputPerMillion: 0.13,
    outputPerMillion: 0.0,
    cachedInputPerMillion: undefined,
    tokenizer: 'cl100k_base',
    streaming: false,
    tools: false,
    jsonMode: false,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Embedding 3 large on Azure (azure/text-embedding-3-large) is a workhorse embeddings model hosted by azure. It speaks openai-embeddings with a 8,191 token context window and a 0 token output cap. List price is $0.13/M input tokens and $0.0/M output tokens. Modalities: embed. Tokenizer: cl100k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-01.',
    useCases: ['semantic search', 'cluster labeling', 'cache keys', 'dedup'],
    fallbacks: ['azure/llama-4-scout', 'azure/llama-3.3-70b', 'azure/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
];

export const AZURE_MODEL_COUNT = AZURE_MODELS.length;

export const MODEL_DOC_azure_llama_4_maverick = {
  id: 'azure/llama-4-maverick',
  summary: 'Llama 4 Maverick via azure (azure/llama-4-maverick) is a frontier Llama model hosted by azure. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.324/M input tokens and $1.02/M output tokens, with cached input at $0.081/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer azure/llama-4-maverick when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001158.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_llama_4_scout = {
  id: 'azure/llama-4-scout',
  summary: 'Llama 4 Scout via azure (azure/llama-4-scout) is a workhorse Llama model hosted by azure. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.216/M input tokens and $0.708/M output tokens, with cached input at $0.054/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer azure/llama-4-scout when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000786.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_llama_3_3_70b = {
  id: 'azure/llama-3.3-70b',
  summary: 'Llama 3.3 70B via azure (azure/llama-3.3-70b) is a workhorse Llama model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.708/M input tokens and $0.948/M output tokens, with cached input at $0.177/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer azure/llama-3.3-70b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00189.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_llama_3_1_8b = {
  id: 'azure/llama-3.1-8b',
  summary: 'Llama 3.1 8B via azure (azure/llama-3.1-8b) is a utility Llama model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.06/M input tokens and $0.096/M output tokens, with cached input at $0.015/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer azure/llama-3.1-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000168.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_azure_llama_3_1_405b = {
  id: 'azure/llama-3.1-405b',
  summary: 'Llama 3.1 405B via azure (azure/llama-3.1-405b) is a frontier Llama model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.148/M input tokens and $2.148/M output tokens, with cached input at $0.537/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer azure/llama-3.1-405b when quality class is frontier and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00537.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_mistral_large_2411 = {
  id: 'azure/mistral-large-2411',
  summary: 'Mistral Large 2411 via azure (azure/mistral-large-2411) is a frontier Mistral model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.4/M input tokens and $7.2/M output tokens, with cached input at $0.6/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer azure/mistral-large-2411 when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0084.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_mistral_small_3_1 = {
  id: 'azure/mistral-small-3.1',
  summary: 'Mistral Small 3.1 via azure (azure/mistral-small-3.1) is a workhorse Mistral model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.12/M input tokens and $0.36/M output tokens, with cached input at $0.03/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
  routingHints: [
    'Prefer azure/mistral-small-3.1 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00042.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_codestral_2501 = {
  id: 'azure/codestral-2501',
  summary: 'Codestral 2501 via azure (azure/codestral-2501) is a workhorse Mistral model hosted by azure. It speaks openai-chat with a 262,144 token context window and a 16,384 token output cap. List price is $0.36/M input tokens and $1.08/M output tokens, with cached input at $0.09/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer azure/codestral-2501 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00126.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_pixtral_large = {
  id: 'azure/pixtral-large',
  summary: 'Pixtral Large via azure (azure/pixtral-large) is a workhorse Mistral model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.4/M input tokens and $7.2/M output tokens, with cached input at $0.6/M. Modalities: text, tools, json, code, vision. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer azure/pixtral-large when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0084.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_ministral_8b = {
  id: 'azure/ministral-8b',
  summary: 'Ministral 8B via azure (azure/ministral-8b) is a utility Mistral model hosted by azure. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.12/M input tokens and $0.12/M output tokens, with cached input at $0.03/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-10.',
  routingHints: [
    'Prefer azure/ministral-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0003.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_azure_gpt_4o = {
  id: 'azure/gpt-4o',
  summary: 'GPT-4o on Azure (azure/gpt-4o) is a workhorse gpt-4o model hosted by azure. It speaks openai-chat with a 128,000 token context window and a 16,384 token output cap. List price is $2.5/M input tokens and $10.0/M output tokens, with cached input at $1.25/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-05.',
  routingHints: [
    'Prefer azure/gpt-4o when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.01.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_gpt_4o_mini = {
  id: 'azure/gpt-4o-mini',
  summary: 'GPT-4o mini on Azure (azure/gpt-4o-mini) is a utility gpt-4o model hosted by azure. It speaks openai-chat with a 128,000 token context window and a 16,384 token output cap. List price is $0.15/M input tokens and $0.6/M output tokens, with cached input at $0.075/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer azure/gpt-4o-mini when quality class is utility and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0006.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_azure_gpt_4_1 = {
  id: 'azure/gpt-4.1',
  summary: 'GPT-4.1 on Azure (azure/gpt-4.1) is a workhorse gpt-4.1 model hosted by azure. It speaks openai-chat with a 1,047,576 token context window and a 32,768 token output cap. List price is $2.0/M input tokens and $8.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer azure/gpt-4.1 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.008.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_gpt_4_1_mini = {
  id: 'azure/gpt-4.1-mini',
  summary: 'GPT-4.1 mini on Azure (azure/gpt-4.1-mini) is a workhorse gpt-4.1 model hosted by azure. It speaks openai-chat with a 1,047,576 token context window and a 32,768 token output cap. List price is $0.4/M input tokens and $1.6/M output tokens, with cached input at $0.1/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer azure/gpt-4.1-mini when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0016.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_gpt_4_1_nano = {
  id: 'azure/gpt-4.1-nano',
  summary: 'GPT-4.1 nano on Azure (azure/gpt-4.1-nano) is a utility gpt-4.1 model hosted by azure. It speaks openai-chat with a 1,047,576 token context window and a 32,768 token output cap. List price is $0.1/M input tokens and $0.4/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer azure/gpt-4.1-nano when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0004.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_azure_gpt_5 = {
  id: 'azure/gpt-5',
  summary: 'GPT-5 on Azure (azure/gpt-5) is a frontier gpt-5 model hosted by azure. It speaks openai-chat with a 1,047,576 token context window and a 65,536 token output cap. List price is $5.0/M input tokens and $20.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
  routingHints: [
    'Prefer azure/gpt-5 when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.02.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_gpt_5_mini = {
  id: 'azure/gpt-5-mini',
  summary: 'GPT-5 mini on Azure (azure/gpt-5-mini) is a workhorse gpt-5 model hosted by azure. It speaks openai-chat with a 400,000 token context window and a 32,768 token output cap. List price is $0.4/M input tokens and $1.6/M output tokens, with cached input at $0.1/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
  routingHints: [
    'Prefer azure/gpt-5-mini when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0016.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_gpt_5_nano = {
  id: 'azure/gpt-5-nano',
  summary: 'GPT-5 nano on Azure (azure/gpt-5-nano) is a utility gpt-5 model hosted by azure. It speaks openai-chat with a 400,000 token context window and a 16,384 token output cap. List price is $0.1/M input tokens and $0.4/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
  routingHints: [
    'Prefer azure/gpt-5-nano when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0004.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_azure_gpt_5_pro = {
  id: 'azure/gpt-5-pro',
  summary: 'GPT-5 pro on Azure (azure/gpt-5-pro) is a reasoning gpt-5 model hosted by azure. It speaks openai-responses with a 1,047,576 token context window and a 65,536 token output cap. List price is $15.0/M input tokens and $60.0/M output tokens, with cached input at $1.5/M. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-12.',
  routingHints: [
    'Prefer azure/gpt-5-pro when quality class is reasoning and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.06.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-responses; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_o3 = {
  id: 'azure/o3',
  summary: 'o3 on Azure (azure/o3) is a reasoning o-series model hosted by azure. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $10.0/M input tokens and $40.0/M output tokens, with cached input at $2.5/M. Modalities: text, tools, json, reasoning. Tokenizer: o200k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer azure/o3 when quality class is reasoning and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.04.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-responses; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_o3_mini = {
  id: 'azure/o3-mini',
  summary: 'o3-mini on Azure (azure/o3-mini) is a reasoning o-series model hosted by azure. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $1.1/M input tokens and $4.4/M output tokens, with cached input at $0.55/M. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer azure/o3-mini when quality class is reasoning and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0044.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-responses; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_o4_mini = {
  id: 'azure/o4-mini',
  summary: 'o4-mini on Azure (azure/o4-mini) is a reasoning o-series model hosted by azure. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $1.1/M input tokens and $4.4/M output tokens, with cached input at $0.275/M. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer azure/o4-mini when quality class is reasoning and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0044.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-responses; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_o1 = {
  id: 'azure/o1',
  summary: 'o1 on Azure (azure/o1) is a reasoning o-series model hosted by azure. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $15.0/M input tokens and $60.0/M output tokens, with cached input at $7.5/M. Modalities: text, tools, json, reasoning. Tokenizer: o200k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer azure/o1 when quality class is reasoning and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.06.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-responses; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_o1_mini = {
  id: 'azure/o1-mini',
  summary: 'o1-mini on Azure (azure/o1-mini) is a reasoning o-series model hosted by azure. It speaks openai-responses with a 128,000 token context window and a 65,536 token output cap. List price is $3.0/M input tokens and $12.0/M output tokens. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
  routingHints: [
    'Prefer azure/o1-mini when quality class is reasoning and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.012.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-responses; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_azure_text_embedding_3_small = {
  id: 'azure/text-embedding-3-small',
  summary: 'Embedding 3 small on Azure (azure/text-embedding-3-small) is a utility embeddings model hosted by azure. It speaks openai-embeddings with a 8,191 token context window and a 0 token output cap. List price is $0.02/M input tokens and $0.0/M output tokens. Modalities: embed. Tokenizer: cl100k_base. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-01.',
  routingHints: [
    'Prefer azure/text-embedding-3-small when quality class is utility and speed class is instant.',
    'Cap max_tokens at 0 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $4e-05.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-embeddings; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_azure_text_embedding_3_large = {
  id: 'azure/text-embedding-3-large',
  summary: 'Embedding 3 large on Azure (azure/text-embedding-3-large) is a workhorse embeddings model hosted by azure. It speaks openai-embeddings with a 8,191 token context window and a 0 token output cap. List price is $0.13/M input tokens and $0.0/M output tokens. Modalities: embed. Tokenizer: cl100k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-01.',
  routingHints: [
    'Prefer azure/text-embedding-3-large when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 0 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00026.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-embeddings; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

