import type { Modality, ModelSpec, Protocol } from "../types";

export const BEDROCK_MODELS: ModelSpec[] = [
  {
    id: 'bedrock/llama-4-maverick',
    provider: 'bedrock',
    displayName: 'Llama 4 Maverick via bedrock',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'bedrock-converse' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.3105,
    outputPerMillion: 0.9775,
    cachedInputPerMillion: 0.0776,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Llama 4 Maverick via bedrock (bedrock/llama-4-maverick) is a frontier Llama model hosted by bedrock. It speaks bedrock-converse with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.3105/M input tokens and $0.9775/M output tokens, with cached input at $0.0776/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['bedrock/llama-4-scout', 'bedrock/llama-3.3-70b', 'bedrock/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'bedrock/llama-4-scout',
    provider: 'bedrock',
    displayName: 'Llama 4 Scout via bedrock',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'bedrock-converse' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.207,
    outputPerMillion: 0.6785,
    cachedInputPerMillion: 0.0517,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 4 Scout via bedrock (bedrock/llama-4-scout) is a workhorse Llama model hosted by bedrock. It speaks bedrock-converse with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.207/M input tokens and $0.6785/M output tokens, with cached input at $0.0517/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['bedrock/llama-3.3-70b', 'bedrock/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'bedrock/llama-3.3-70b',
    provider: 'bedrock',
    displayName: 'Llama 3.3 70B via bedrock',
    family: 'Llama',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'bedrock-converse' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.6785,
    outputPerMillion: 0.9085,
    cachedInputPerMillion: 0.1696,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 3.3 70B via bedrock (bedrock/llama-3.3-70b) is a workhorse Llama model hosted by bedrock. It speaks bedrock-converse with a 131,072 token context window and a 16,384 token output cap. List price is $0.6785/M input tokens and $0.9085/M output tokens, with cached input at $0.1696/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['bedrock/llama-4-scout', 'bedrock/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'bedrock/llama-3.1-8b',
    provider: 'bedrock',
    displayName: 'Llama 3.1 8B via bedrock',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'bedrock-converse' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.0575,
    outputPerMillion: 0.092,
    cachedInputPerMillion: 0.0144,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Llama 3.1 8B via bedrock (bedrock/llama-3.1-8b) is a utility Llama model hosted by bedrock. It speaks bedrock-converse with a 131,072 token context window and a 8,192 token output cap. List price is $0.0575/M input tokens and $0.092/M output tokens, with cached input at $0.0144/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['bedrock/llama-4-scout', 'bedrock/llama-3.3-70b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'bedrock/llama-3.1-405b',
    provider: 'bedrock',
    displayName: 'Llama 3.1 405B via bedrock',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'bedrock-converse' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 2.0585,
    outputPerMillion: 2.0585,
    cachedInputPerMillion: 0.5146,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'frontier',
    notes: 'Llama 3.1 405B via bedrock (bedrock/llama-3.1-405b) is a frontier Llama model hosted by bedrock. It speaks bedrock-converse with a 131,072 token context window and a 16,384 token output cap. List price is $2.0585/M input tokens and $2.0585/M output tokens, with cached input at $0.5146/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['bedrock/llama-4-scout', 'bedrock/llama-3.3-70b', 'bedrock/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
];

export const BEDROCK_MODEL_COUNT = BEDROCK_MODELS.length;

export const MODEL_DOC_bedrock_llama_4_maverick = {
  id: 'bedrock/llama-4-maverick',
  summary: 'Llama 4 Maverick via bedrock (bedrock/llama-4-maverick) is a frontier Llama model hosted by bedrock. It speaks bedrock-converse with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.3105/M input tokens and $0.9775/M output tokens, with cached input at $0.0776/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer bedrock/llama-4-maverick when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00111.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol bedrock-converse; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_bedrock_llama_4_scout = {
  id: 'bedrock/llama-4-scout',
  summary: 'Llama 4 Scout via bedrock (bedrock/llama-4-scout) is a workhorse Llama model hosted by bedrock. It speaks bedrock-converse with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.207/M input tokens and $0.6785/M output tokens, with cached input at $0.0517/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer bedrock/llama-4-scout when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000753.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol bedrock-converse; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_bedrock_llama_3_3_70b = {
  id: 'bedrock/llama-3.3-70b',
  summary: 'Llama 3.3 70B via bedrock (bedrock/llama-3.3-70b) is a workhorse Llama model hosted by bedrock. It speaks bedrock-converse with a 131,072 token context window and a 16,384 token output cap. List price is $0.6785/M input tokens and $0.9085/M output tokens, with cached input at $0.1696/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer bedrock/llama-3.3-70b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001811.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol bedrock-converse; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_bedrock_llama_3_1_8b = {
  id: 'bedrock/llama-3.1-8b',
  summary: 'Llama 3.1 8B via bedrock (bedrock/llama-3.1-8b) is a utility Llama model hosted by bedrock. It speaks bedrock-converse with a 131,072 token context window and a 8,192 token output cap. List price is $0.0575/M input tokens and $0.092/M output tokens, with cached input at $0.0144/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer bedrock/llama-3.1-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000161.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol bedrock-converse; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_bedrock_llama_3_1_405b = {
  id: 'bedrock/llama-3.1-405b',
  summary: 'Llama 3.1 405B via bedrock (bedrock/llama-3.1-405b) is a frontier Llama model hosted by bedrock. It speaks bedrock-converse with a 131,072 token context window and a 16,384 token output cap. List price is $2.0585/M input tokens and $2.0585/M output tokens, with cached input at $0.5146/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer bedrock/llama-3.1-405b when quality class is frontier and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.005146.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol bedrock-converse; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

