import type { Modality, ModelSpec, Protocol } from "../types";

export const CEREBRAS_MODELS: ModelSpec[] = [
  {
    id: 'cerebras/llama-4-maverick',
    provider: 'cerebras',
    displayName: 'Llama 4 Maverick via cerebras',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.216,
    outputPerMillion: 0.68,
    cachedInputPerMillion: 0.054,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'frontier',
    notes: 'Llama 4 Maverick via cerebras (cerebras/llama-4-maverick) is a frontier Llama model hosted by cerebras. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.216/M input tokens and $0.68/M output tokens, with cached input at $0.054/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['cerebras/llama-4-scout', 'cerebras/llama-3.3-70b', 'cerebras/llama-3.1-8b'],
    carbonGPerMTok: 0.56,
  },
  {
    id: 'cerebras/llama-4-scout',
    provider: 'cerebras',
    displayName: 'Llama 4 Scout via cerebras',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.144,
    outputPerMillion: 0.472,
    cachedInputPerMillion: 0.036,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'workhorse',
    notes: 'Llama 4 Scout via cerebras (cerebras/llama-4-scout) is a workhorse Llama model hosted by cerebras. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.144/M input tokens and $0.472/M output tokens, with cached input at $0.036/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['cerebras/llama-3.3-70b', 'cerebras/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'cerebras/llama-3.3-70b',
    provider: 'cerebras',
    displayName: 'Llama 3.3 70B via cerebras',
    family: 'Llama',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.472,
    outputPerMillion: 0.632,
    cachedInputPerMillion: 0.118,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'workhorse',
    notes: 'Llama 3.3 70B via cerebras (cerebras/llama-3.3-70b) is a workhorse Llama model hosted by cerebras. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.472/M input tokens and $0.632/M output tokens, with cached input at $0.118/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['cerebras/llama-4-scout', 'cerebras/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'cerebras/llama-3.1-8b',
    provider: 'cerebras',
    displayName: 'Llama 3.1 8B via cerebras',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.04,
    outputPerMillion: 0.064,
    cachedInputPerMillion: 0.01,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Llama 3.1 8B via cerebras (cerebras/llama-3.1-8b) is a utility Llama model hosted by cerebras. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.04/M input tokens and $0.064/M output tokens, with cached input at $0.01/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['cerebras/llama-4-scout', 'cerebras/llama-3.3-70b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'cerebras/llama-3.1-405b',
    provider: 'cerebras',
    displayName: 'Llama 3.1 405B via cerebras',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 1.432,
    outputPerMillion: 1.432,
    cachedInputPerMillion: 0.358,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'frontier',
    notes: 'Llama 3.1 405B via cerebras (cerebras/llama-3.1-405b) is a frontier Llama model hosted by cerebras. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.432/M input tokens and $1.432/M output tokens, with cached input at $0.358/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['cerebras/llama-4-scout', 'cerebras/llama-3.3-70b', 'cerebras/llama-3.1-8b'],
    carbonGPerMTok: 0.56,
  },
];

export const CEREBRAS_MODEL_COUNT = CEREBRAS_MODELS.length;

export const MODEL_DOC_cerebras_llama_4_maverick = {
  id: 'cerebras/llama-4-maverick',
  summary: 'Llama 4 Maverick via cerebras (cerebras/llama-4-maverick) is a frontier Llama model hosted by cerebras. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.216/M input tokens and $0.68/M output tokens, with cached input at $0.054/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer cerebras/llama-4-maverick when quality class is frontier and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000772.',
    'Carbon intensity about 0.56 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_cerebras_llama_4_scout = {
  id: 'cerebras/llama-4-scout',
  summary: 'Llama 4 Scout via cerebras (cerebras/llama-4-scout) is a workhorse Llama model hosted by cerebras. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.144/M input tokens and $0.472/M output tokens, with cached input at $0.036/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer cerebras/llama-4-scout when quality class is workhorse and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000524.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_cerebras_llama_3_3_70b = {
  id: 'cerebras/llama-3.3-70b',
  summary: 'Llama 3.3 70B via cerebras (cerebras/llama-3.3-70b) is a workhorse Llama model hosted by cerebras. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.472/M input tokens and $0.632/M output tokens, with cached input at $0.118/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer cerebras/llama-3.3-70b when quality class is workhorse and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00126.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_cerebras_llama_3_1_8b = {
  id: 'cerebras/llama-3.1-8b',
  summary: 'Llama 3.1 8B via cerebras (cerebras/llama-3.1-8b) is a utility Llama model hosted by cerebras. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.04/M input tokens and $0.064/M output tokens, with cached input at $0.01/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer cerebras/llama-3.1-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000112.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_cerebras_llama_3_1_405b = {
  id: 'cerebras/llama-3.1-405b',
  summary: 'Llama 3.1 405B via cerebras (cerebras/llama-3.1-405b) is a frontier Llama model hosted by cerebras. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.432/M input tokens and $1.432/M output tokens, with cached input at $0.358/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer cerebras/llama-3.1-405b when quality class is frontier and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00358.',
    'Carbon intensity about 0.56 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

