import type { Modality, ModelSpec, Protocol } from "../types";

export const COHERE_MODELS: ModelSpec[] = [
  {
    id: 'cohere/command-a',
    provider: 'cohere',
    displayName: 'Command A via cohere',
    family: 'Command',
    release: '2025-03',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 256000,
    maxOutput: 8192,
    inputPerMillion: 2.5,
    outputPerMillion: 10.0,
    cachedInputPerMillion: 0.625,
    tokenizer: 'command',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Command A via cohere (cohere/command-a) is a frontier Command model hosted by cohere. It speaks openai-chat with a 256,000 token context window and a 8,192 token output cap. List price is $2.5/M input tokens and $10.0/M output tokens, with cached input at $0.625/M. Modalities: text, tools, json, code. Tokenizer: command. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['cohere/command-r-plus', 'cohere/command-r', 'cohere/embed-v4'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'cohere/command-r-plus',
    provider: 'cohere',
    displayName: 'Command R+ via cohere',
    family: 'Command',
    release: '2024-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 128000,
    maxOutput: 4096,
    inputPerMillion: 2.5,
    outputPerMillion: 10.0,
    cachedInputPerMillion: 0.625,
    tokenizer: 'command',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Command R+ via cohere (cohere/command-r-plus) is a workhorse Command model hosted by cohere. It speaks openai-chat with a 128,000 token context window and a 4,096 token output cap. List price is $2.5/M input tokens and $10.0/M output tokens, with cached input at $0.625/M. Modalities: text, tools, json, code. Tokenizer: command. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['cohere/command-r', 'cohere/embed-v4', 'cohere/rerank-v3.5'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'cohere/command-r',
    provider: 'cohere',
    displayName: 'Command R via cohere',
    family: 'Command',
    release: '2024-03',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 128000,
    maxOutput: 4096,
    inputPerMillion: 0.15,
    outputPerMillion: 0.6,
    cachedInputPerMillion: 0.0375,
    tokenizer: 'command',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Command R via cohere (cohere/command-r) is a workhorse Command model hosted by cohere. It speaks openai-chat with a 128,000 token context window and a 4,096 token output cap. List price is $0.15/M input tokens and $0.6/M output tokens, with cached input at $0.0375/M. Modalities: text, tools, json, code. Tokenizer: command. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-03.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['cohere/command-r-plus', 'cohere/embed-v4', 'cohere/rerank-v3.5'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'cohere/embed-v4',
    provider: 'cohere',
    displayName: 'Embed v4 via cohere',
    family: 'Command',
    release: '2025-01',
    modality: ['embed'] as Modality[],
    protocol: 'openai-embeddings' as Protocol,
    contextWindow: 128000,
    maxOutput: 0,
    inputPerMillion: 0.12,
    outputPerMillion: 0.0,
    cachedInputPerMillion: 0.03,
    tokenizer: 'command',
    streaming: false,
    tools: false,
    jsonMode: false,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'workhorse',
    notes: 'Embed v4 via cohere (cohere/embed-v4) is a workhorse Command model hosted by cohere. It speaks openai-embeddings with a 128,000 token context window and a 0 token output cap. List price is $0.12/M input tokens and $0.0/M output tokens, with cached input at $0.03/M. Modalities: embed. Tokenizer: command. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['semantic search', 'cluster labeling', 'cache keys', 'dedup'],
    fallbacks: ['cohere/command-r-plus', 'cohere/command-r', 'cohere/rerank-v3.5'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'cohere/rerank-v3.5',
    provider: 'cohere',
    displayName: 'Rerank v3.5 via cohere',
    family: 'Command',
    release: '2024-12',
    modality: ['rerank'] as Modality[],
    protocol: 'cohere-chat' as Protocol,
    contextWindow: 4096,
    maxOutput: 0,
    inputPerMillion: 2.0,
    outputPerMillion: 0.0,
    cachedInputPerMillion: 0.5,
    tokenizer: 'command',
    streaming: false,
    tools: false,
    jsonMode: false,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'workhorse',
    notes: 'Rerank v3.5 via cohere (cohere/rerank-v3.5) is a workhorse Command model hosted by cohere. It speaks cohere-chat with a 4,096 token context window and a 0 token output cap. List price is $2.0/M input tokens and $0.0/M output tokens, with cached input at $0.5/M. Modalities: rerank. Tokenizer: command. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['search rerank', 'RAG compression'],
    fallbacks: ['cohere/command-r-plus', 'cohere/command-r', 'cohere/embed-v4'],
    carbonGPerMTok: 0.4,
  },
];

export const COHERE_MODEL_COUNT = COHERE_MODELS.length;

export const MODEL_DOC_cohere_command_a = {
  id: 'cohere/command-a',
  summary: 'Command A via cohere (cohere/command-a) is a frontier Command model hosted by cohere. It speaks openai-chat with a 256,000 token context window and a 8,192 token output cap. List price is $2.5/M input tokens and $10.0/M output tokens, with cached input at $0.625/M. Modalities: text, tools, json, code. Tokenizer: command. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
  routingHints: [
    'Prefer cohere/command-a when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.01.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_cohere_command_r_plus = {
  id: 'cohere/command-r-plus',
  summary: 'Command R+ via cohere (cohere/command-r-plus) is a workhorse Command model hosted by cohere. It speaks openai-chat with a 128,000 token context window and a 4,096 token output cap. List price is $2.5/M input tokens and $10.0/M output tokens, with cached input at $0.625/M. Modalities: text, tools, json, code. Tokenizer: command. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-04.',
  routingHints: [
    'Prefer cohere/command-r-plus when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.01.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_cohere_command_r = {
  id: 'cohere/command-r',
  summary: 'Command R via cohere (cohere/command-r) is a workhorse Command model hosted by cohere. It speaks openai-chat with a 128,000 token context window and a 4,096 token output cap. List price is $0.15/M input tokens and $0.6/M output tokens, with cached input at $0.0375/M. Modalities: text, tools, json, code. Tokenizer: command. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-03.',
  routingHints: [
    'Prefer cohere/command-r when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0006.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_cohere_embed_v4 = {
  id: 'cohere/embed-v4',
  summary: 'Embed v4 via cohere (cohere/embed-v4) is a workhorse Command model hosted by cohere. It speaks openai-embeddings with a 128,000 token context window and a 0 token output cap. List price is $0.12/M input tokens and $0.0/M output tokens, with cached input at $0.03/M. Modalities: embed. Tokenizer: command. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer cohere/embed-v4 when quality class is workhorse and speed class is instant.',
    'Cap max_tokens at 0 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00024.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-embeddings; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_cohere_rerank_v3_5 = {
  id: 'cohere/rerank-v3.5',
  summary: 'Rerank v3.5 via cohere (cohere/rerank-v3.5) is a workhorse Command model hosted by cohere. It speaks cohere-chat with a 4,096 token context window and a 0 token output cap. List price is $2.0/M input tokens and $0.0/M output tokens, with cached input at $0.5/M. Modalities: rerank. Tokenizer: command. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer cohere/rerank-v3.5 when quality class is workhorse and speed class is instant.',
    'Cap max_tokens at 0 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.004.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol cohere-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

