import type { Modality, ModelSpec, Protocol } from "../types";

export const DEEPSEEK_MODELS: ModelSpec[] = [
  {
    id: 'deepseek/deepseek-v3.2',
    provider: 'deepseek',
    displayName: 'DeepSeek V3.2 via deepseek',
    family: 'DeepSeek',
    release: '2025-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 163840,
    maxOutput: 8192,
    inputPerMillion: 0.27,
    outputPerMillion: 1.1,
    cachedInputPerMillion: 0.0675,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'DeepSeek V3.2 via deepseek (deepseek/deepseek-v3.2) is a frontier DeepSeek model hosted by deepseek. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.27/M input tokens and $1.1/M output tokens, with cached input at $0.0675/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-12.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['deepseek/deepseek-coder-v2'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'deepseek/deepseek-v3',
    provider: 'deepseek',
    displayName: 'DeepSeek V3 via deepseek',
    family: 'DeepSeek',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 163840,
    maxOutput: 8192,
    inputPerMillion: 0.27,
    outputPerMillion: 1.1,
    cachedInputPerMillion: 0.0675,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'DeepSeek V3 via deepseek (deepseek/deepseek-v3) is a frontier DeepSeek model hosted by deepseek. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.27/M input tokens and $1.1/M output tokens, with cached input at $0.0675/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['deepseek/deepseek-coder-v2'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'deepseek/deepseek-r1',
    provider: 'deepseek',
    displayName: 'DeepSeek R1 via deepseek',
    family: 'DeepSeek',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 163840,
    maxOutput: 8192,
    inputPerMillion: 0.55,
    outputPerMillion: 2.19,
    cachedInputPerMillion: 0.1375,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'reasoning',
    notes: 'DeepSeek R1 via deepseek (deepseek/deepseek-r1) is a reasoning DeepSeek model hosted by deepseek. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.55/M input tokens and $2.19/M output tokens, with cached input at $0.1375/M. Modalities: text, tools, json, code, reasoning. Tokenizer: deepseek. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['deepseek/deepseek-coder-v2'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'deepseek/deepseek-coder-v2',
    provider: 'deepseek',
    displayName: 'DeepSeek Coder V2 via deepseek',
    family: 'DeepSeek',
    release: '2024-06',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.14,
    outputPerMillion: 0.28,
    cachedInputPerMillion: 0.035,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'DeepSeek Coder V2 via deepseek (deepseek/deepseek-coder-v2) is a workhorse DeepSeek model hosted by deepseek. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.14/M input tokens and $0.28/M output tokens, with cached input at $0.035/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-06.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: [],
    carbonGPerMTok: 0.9,
  },
];

export const DEEPSEEK_MODEL_COUNT = DEEPSEEK_MODELS.length;

export const MODEL_DOC_deepseek_deepseek_v3_2 = {
  id: 'deepseek/deepseek-v3.2',
  summary: 'DeepSeek V3.2 via deepseek (deepseek/deepseek-v3.2) is a frontier DeepSeek model hosted by deepseek. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.27/M input tokens and $1.1/M output tokens, with cached input at $0.0675/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-12.',
  routingHints: [
    'Prefer deepseek/deepseek-v3.2 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00109.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepseek_deepseek_v3 = {
  id: 'deepseek/deepseek-v3',
  summary: 'DeepSeek V3 via deepseek (deepseek/deepseek-v3) is a frontier DeepSeek model hosted by deepseek. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.27/M input tokens and $1.1/M output tokens, with cached input at $0.0675/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer deepseek/deepseek-v3 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00109.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepseek_deepseek_r1 = {
  id: 'deepseek/deepseek-r1',
  summary: 'DeepSeek R1 via deepseek (deepseek/deepseek-r1) is a reasoning DeepSeek model hosted by deepseek. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.55/M input tokens and $2.19/M output tokens, with cached input at $0.1375/M. Modalities: text, tools, json, code, reasoning. Tokenizer: deepseek. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer deepseek/deepseek-r1 when quality class is reasoning and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.002195.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepseek_deepseek_coder_v2 = {
  id: 'deepseek/deepseek-coder-v2',
  summary: 'DeepSeek Coder V2 via deepseek (deepseek/deepseek-coder-v2) is a workhorse DeepSeek model hosted by deepseek. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.14/M input tokens and $0.28/M output tokens, with cached input at $0.035/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-06.',
  routingHints: [
    'Prefer deepseek/deepseek-coder-v2 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00042.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

