import type { Modality, ModelSpec, Protocol } from "../types";

export const DEEPINFRA_MODELS: ModelSpec[] = [
  {
    id: 'deepinfra/llama-4-maverick',
    provider: 'deepinfra',
    displayName: 'Llama 4 Maverick via deepinfra',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.2025,
    outputPerMillion: 0.6375,
    cachedInputPerMillion: 0.0506,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Llama 4 Maverick via deepinfra (deepinfra/llama-4-maverick) is a frontier Llama model hosted by deepinfra. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.2025/M input tokens and $0.6375/M output tokens, with cached input at $0.0506/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.3-70b', 'deepinfra/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'deepinfra/llama-4-scout',
    provider: 'deepinfra',
    displayName: 'Llama 4 Scout via deepinfra',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.135,
    outputPerMillion: 0.4425,
    cachedInputPerMillion: 0.0338,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 4 Scout via deepinfra (deepinfra/llama-4-scout) is a workhorse Llama model hosted by deepinfra. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.135/M input tokens and $0.4425/M output tokens, with cached input at $0.0338/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['deepinfra/llama-3.3-70b', 'deepinfra/llama-3.1-8b', 'deepinfra/deepseek-coder-v2'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'deepinfra/llama-3.3-70b',
    provider: 'deepinfra',
    displayName: 'Llama 3.3 70B via deepinfra',
    family: 'Llama',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.4425,
    outputPerMillion: 0.5925,
    cachedInputPerMillion: 0.1106,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 3.3 70B via deepinfra (deepinfra/llama-3.3-70b) is a workhorse Llama model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.4425/M input tokens and $0.5925/M output tokens, with cached input at $0.1106/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.1-8b', 'deepinfra/deepseek-coder-v2'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'deepinfra/llama-3.1-8b',
    provider: 'deepinfra',
    displayName: 'Llama 3.1 8B via deepinfra',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.0375,
    outputPerMillion: 0.06,
    cachedInputPerMillion: 0.0094,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Llama 3.1 8B via deepinfra (deepinfra/llama-3.1-8b) is a utility Llama model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.0375/M input tokens and $0.06/M output tokens, with cached input at $0.0094/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.3-70b', 'deepinfra/deepseek-coder-v2'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'deepinfra/llama-3.1-405b',
    provider: 'deepinfra',
    displayName: 'Llama 3.1 405B via deepinfra',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 1.3425,
    outputPerMillion: 1.3425,
    cachedInputPerMillion: 0.3356,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'frontier',
    notes: 'Llama 3.1 405B via deepinfra (deepinfra/llama-3.1-405b) is a frontier Llama model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.3425/M input tokens and $1.3425/M output tokens, with cached input at $0.3356/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.3-70b', 'deepinfra/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'deepinfra/deepseek-v3.2',
    provider: 'deepinfra',
    displayName: 'DeepSeek V3.2 via deepinfra',
    family: 'DeepSeek',
    release: '2025-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 163840,
    maxOutput: 8192,
    inputPerMillion: 0.2025,
    outputPerMillion: 0.825,
    cachedInputPerMillion: 0.0506,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'DeepSeek V3.2 via deepinfra (deepinfra/deepseek-v3.2) is a frontier DeepSeek model hosted by deepinfra. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.2025/M input tokens and $0.825/M output tokens, with cached input at $0.0506/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-12.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.3-70b', 'deepinfra/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'deepinfra/deepseek-v3',
    provider: 'deepinfra',
    displayName: 'DeepSeek V3 via deepinfra',
    family: 'DeepSeek',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 163840,
    maxOutput: 8192,
    inputPerMillion: 0.2025,
    outputPerMillion: 0.825,
    cachedInputPerMillion: 0.0506,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'DeepSeek V3 via deepinfra (deepinfra/deepseek-v3) is a frontier DeepSeek model hosted by deepinfra. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.2025/M input tokens and $0.825/M output tokens, with cached input at $0.0506/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.3-70b', 'deepinfra/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'deepinfra/deepseek-r1',
    provider: 'deepinfra',
    displayName: 'DeepSeek R1 via deepinfra',
    family: 'DeepSeek',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 163840,
    maxOutput: 8192,
    inputPerMillion: 0.4125,
    outputPerMillion: 1.6425,
    cachedInputPerMillion: 0.1031,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'reasoning',
    notes: 'DeepSeek R1 via deepinfra (deepinfra/deepseek-r1) is a reasoning DeepSeek model hosted by deepinfra. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.4125/M input tokens and $1.6425/M output tokens, with cached input at $0.1031/M. Modalities: text, tools, json, code, reasoning. Tokenizer: deepseek. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.3-70b', 'deepinfra/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'deepinfra/deepseek-coder-v2',
    provider: 'deepinfra',
    displayName: 'DeepSeek Coder V2 via deepinfra',
    family: 'DeepSeek',
    release: '2024-06',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.105,
    outputPerMillion: 0.21,
    cachedInputPerMillion: 0.0263,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'DeepSeek Coder V2 via deepinfra (deepinfra/deepseek-coder-v2) is a workhorse DeepSeek model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.105/M input tokens and $0.21/M output tokens, with cached input at $0.0263/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-06.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.3-70b', 'deepinfra/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'deepinfra/qwen3-235b',
    provider: 'deepinfra',
    displayName: 'Qwen3 235B via deepinfra',
    family: 'Qwen',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.15,
    outputPerMillion: 0.45,
    cachedInputPerMillion: 0.0375,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'Qwen3 235B via deepinfra (deepinfra/qwen3-235b) is a frontier Qwen model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.15/M input tokens and $0.45/M output tokens, with cached input at $0.0375/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.3-70b', 'deepinfra/llama-3.1-8b'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'deepinfra/qwen3-32b',
    provider: 'deepinfra',
    displayName: 'Qwen3 32B via deepinfra',
    family: 'Qwen',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.075,
    outputPerMillion: 0.225,
    cachedInputPerMillion: 0.0188,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen3 32B via deepinfra (deepinfra/qwen3-32b) is a workhorse Qwen model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.075/M input tokens and $0.225/M output tokens, with cached input at $0.0188/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.3-70b', 'deepinfra/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'deepinfra/qwen2.5-72b',
    provider: 'deepinfra',
    displayName: 'Qwen2.5 72B via deepinfra',
    family: 'Qwen',
    release: '2024-09',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.09,
    outputPerMillion: 0.2925,
    cachedInputPerMillion: 0.0225,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen2.5 72B via deepinfra (deepinfra/qwen2.5-72b) is a workhorse Qwen model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.09/M input tokens and $0.2925/M output tokens, with cached input at $0.0225/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.3-70b', 'deepinfra/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'deepinfra/qwen2.5-coder-32b',
    provider: 'deepinfra',
    displayName: 'Qwen2.5 Coder 32B via deepinfra',
    family: 'Qwen',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.06,
    outputPerMillion: 0.135,
    cachedInputPerMillion: 0.015,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen2.5 Coder 32B via deepinfra (deepinfra/qwen2.5-coder-32b) is a workhorse Qwen model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.06/M input tokens and $0.135/M output tokens, with cached input at $0.015/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.3-70b', 'deepinfra/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'deepinfra/qwen-vl-max',
    provider: 'deepinfra',
    displayName: 'Qwen VL Max via deepinfra',
    family: 'Qwen',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 32768,
    maxOutput: 8192,
    inputPerMillion: 0.6,
    outputPerMillion: 2.4,
    cachedInputPerMillion: 0.15,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'Qwen VL Max via deepinfra (deepinfra/qwen-vl-max) is a workhorse Qwen model hosted by deepinfra. It speaks openai-chat with a 32,768 token context window and a 8,192 token output cap. List price is $0.6/M input tokens and $2.4/M output tokens, with cached input at $0.15/M. Modalities: text, tools, json, code, vision. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['deepinfra/llama-4-scout', 'deepinfra/llama-3.3-70b', 'deepinfra/llama-3.1-8b'],
    carbonGPerMTok: 1.6,
  },
];

export const DEEPINFRA_MODEL_COUNT = DEEPINFRA_MODELS.length;

export const MODEL_DOC_deepinfra_llama_4_maverick = {
  id: 'deepinfra/llama-4-maverick',
  summary: 'Llama 4 Maverick via deepinfra (deepinfra/llama-4-maverick) is a frontier Llama model hosted by deepinfra. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.2025/M input tokens and $0.6375/M output tokens, with cached input at $0.0506/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer deepinfra/llama-4-maverick when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000724.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepinfra_llama_4_scout = {
  id: 'deepinfra/llama-4-scout',
  summary: 'Llama 4 Scout via deepinfra (deepinfra/llama-4-scout) is a workhorse Llama model hosted by deepinfra. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.135/M input tokens and $0.4425/M output tokens, with cached input at $0.0338/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer deepinfra/llama-4-scout when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000491.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepinfra_llama_3_3_70b = {
  id: 'deepinfra/llama-3.3-70b',
  summary: 'Llama 3.3 70B via deepinfra (deepinfra/llama-3.3-70b) is a workhorse Llama model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.4425/M input tokens and $0.5925/M output tokens, with cached input at $0.1106/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer deepinfra/llama-3.3-70b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001181.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepinfra_llama_3_1_8b = {
  id: 'deepinfra/llama-3.1-8b',
  summary: 'Llama 3.1 8B via deepinfra (deepinfra/llama-3.1-8b) is a utility Llama model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.0375/M input tokens and $0.06/M output tokens, with cached input at $0.0094/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer deepinfra/llama-3.1-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000105.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_deepinfra_llama_3_1_405b = {
  id: 'deepinfra/llama-3.1-405b',
  summary: 'Llama 3.1 405B via deepinfra (deepinfra/llama-3.1-405b) is a frontier Llama model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.3425/M input tokens and $1.3425/M output tokens, with cached input at $0.3356/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer deepinfra/llama-3.1-405b when quality class is frontier and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.003356.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepinfra_deepseek_v3_2 = {
  id: 'deepinfra/deepseek-v3.2',
  summary: 'DeepSeek V3.2 via deepinfra (deepinfra/deepseek-v3.2) is a frontier DeepSeek model hosted by deepinfra. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.2025/M input tokens and $0.825/M output tokens, with cached input at $0.0506/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-12.',
  routingHints: [
    'Prefer deepinfra/deepseek-v3.2 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000817.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepinfra_deepseek_v3 = {
  id: 'deepinfra/deepseek-v3',
  summary: 'DeepSeek V3 via deepinfra (deepinfra/deepseek-v3) is a frontier DeepSeek model hosted by deepinfra. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.2025/M input tokens and $0.825/M output tokens, with cached input at $0.0506/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer deepinfra/deepseek-v3 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000817.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepinfra_deepseek_r1 = {
  id: 'deepinfra/deepseek-r1',
  summary: 'DeepSeek R1 via deepinfra (deepinfra/deepseek-r1) is a reasoning DeepSeek model hosted by deepinfra. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.4125/M input tokens and $1.6425/M output tokens, with cached input at $0.1031/M. Modalities: text, tools, json, code, reasoning. Tokenizer: deepseek. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer deepinfra/deepseek-r1 when quality class is reasoning and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001646.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepinfra_deepseek_coder_v2 = {
  id: 'deepinfra/deepseek-coder-v2',
  summary: 'DeepSeek Coder V2 via deepinfra (deepinfra/deepseek-coder-v2) is a workhorse DeepSeek model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.105/M input tokens and $0.21/M output tokens, with cached input at $0.0263/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-06.',
  routingHints: [
    'Prefer deepinfra/deepseek-coder-v2 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000315.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepinfra_qwen3_235b = {
  id: 'deepinfra/qwen3-235b',
  summary: 'Qwen3 235B via deepinfra (deepinfra/qwen3-235b) is a frontier Qwen model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.15/M input tokens and $0.45/M output tokens, with cached input at $0.0375/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer deepinfra/qwen3-235b when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000525.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepinfra_qwen3_32b = {
  id: 'deepinfra/qwen3-32b',
  summary: 'Qwen3 32B via deepinfra (deepinfra/qwen3-32b) is a workhorse Qwen model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.075/M input tokens and $0.225/M output tokens, with cached input at $0.0188/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer deepinfra/qwen3-32b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000262.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepinfra_qwen2_5_72b = {
  id: 'deepinfra/qwen2.5-72b',
  summary: 'Qwen2.5 72B via deepinfra (deepinfra/qwen2.5-72b) is a workhorse Qwen model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.09/M input tokens and $0.2925/M output tokens, with cached input at $0.0225/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
  routingHints: [
    'Prefer deepinfra/qwen2.5-72b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000326.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepinfra_qwen2_5_coder_32b = {
  id: 'deepinfra/qwen2.5-coder-32b',
  summary: 'Qwen2.5 Coder 32B via deepinfra (deepinfra/qwen2.5-coder-32b) is a workhorse Qwen model hosted by deepinfra. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.06/M input tokens and $0.135/M output tokens, with cached input at $0.015/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer deepinfra/qwen2.5-coder-32b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000188.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_deepinfra_qwen_vl_max = {
  id: 'deepinfra/qwen-vl-max',
  summary: 'Qwen VL Max via deepinfra (deepinfra/qwen-vl-max) is a workhorse Qwen model hosted by deepinfra. It speaks openai-chat with a 32,768 token context window and a 8,192 token output cap. List price is $0.6/M input tokens and $2.4/M output tokens, with cached input at $0.15/M. Modalities: text, tools, json, code, vision. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer deepinfra/qwen-vl-max when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0024.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

