import type { Modality, ModelSpec, Protocol } from "../types";

export const FIREWORKS_MODELS: ModelSpec[] = [
  {
    id: 'fireworks/llama-4-maverick',
    provider: 'fireworks',
    displayName: 'Llama 4 Maverick via fireworks',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.2565,
    outputPerMillion: 0.8075,
    cachedInputPerMillion: 0.0641,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Llama 4 Maverick via fireworks (fireworks/llama-4-maverick) is a frontier Llama model hosted by fireworks. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.2565/M input tokens and $0.8075/M output tokens, with cached input at $0.0641/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'fireworks/llama-4-scout',
    provider: 'fireworks',
    displayName: 'Llama 4 Scout via fireworks',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.171,
    outputPerMillion: 0.5605,
    cachedInputPerMillion: 0.0427,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 4 Scout via fireworks (fireworks/llama-4-scout) is a workhorse Llama model hosted by fireworks. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.171/M input tokens and $0.5605/M output tokens, with cached input at $0.0427/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b', 'fireworks/mistral-small-3.1'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'fireworks/llama-3.3-70b',
    provider: 'fireworks',
    displayName: 'Llama 3.3 70B via fireworks',
    family: 'Llama',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.5605,
    outputPerMillion: 0.7505,
    cachedInputPerMillion: 0.1401,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 3.3 70B via fireworks (fireworks/llama-3.3-70b) is a workhorse Llama model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.5605/M input tokens and $0.7505/M output tokens, with cached input at $0.1401/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.1-8b', 'fireworks/mistral-small-3.1'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'fireworks/llama-3.1-8b',
    provider: 'fireworks',
    displayName: 'Llama 3.1 8B via fireworks',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.0475,
    outputPerMillion: 0.076,
    cachedInputPerMillion: 0.0119,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Llama 3.1 8B via fireworks (fireworks/llama-3.1-8b) is a utility Llama model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.0475/M input tokens and $0.076/M output tokens, with cached input at $0.0119/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/mistral-small-3.1'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'fireworks/llama-3.1-405b',
    provider: 'fireworks',
    displayName: 'Llama 3.1 405B via fireworks',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 1.7005,
    outputPerMillion: 1.7005,
    cachedInputPerMillion: 0.4251,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'frontier',
    notes: 'Llama 3.1 405B via fireworks (fireworks/llama-3.1-405b) is a frontier Llama model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.7005/M input tokens and $1.7005/M output tokens, with cached input at $0.4251/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'fireworks/mistral-large-2411',
    provider: 'fireworks',
    displayName: 'Mistral Large 2411 via fireworks',
    family: 'Mistral',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 1.9,
    outputPerMillion: 5.7,
    cachedInputPerMillion: 0.475,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'Mistral Large 2411 via fireworks (fireworks/mistral-large-2411) is a frontier Mistral model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.9/M input tokens and $5.7/M output tokens, with cached input at $0.475/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'fireworks/mistral-small-3.1',
    provider: 'fireworks',
    displayName: 'Mistral Small 3.1 via fireworks',
    family: 'Mistral',
    release: '2025-03',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.095,
    outputPerMillion: 0.285,
    cachedInputPerMillion: 0.0238,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Mistral Small 3.1 via fireworks (fireworks/mistral-small-3.1) is a workhorse Mistral model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.095/M input tokens and $0.285/M output tokens, with cached input at $0.0238/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'fireworks/codestral-2501',
    provider: 'fireworks',
    displayName: 'Codestral 2501 via fireworks',
    family: 'Mistral',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 262144,
    maxOutput: 16384,
    inputPerMillion: 0.285,
    outputPerMillion: 0.855,
    cachedInputPerMillion: 0.0712,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Codestral 2501 via fireworks (fireworks/codestral-2501) is a workhorse Mistral model hosted by fireworks. It speaks openai-chat with a 262,144 token context window and a 16,384 token output cap. List price is $0.285/M input tokens and $0.855/M output tokens, with cached input at $0.0712/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'fireworks/pixtral-large',
    provider: 'fireworks',
    displayName: 'Pixtral Large via fireworks',
    family: 'Mistral',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 1.9,
    outputPerMillion: 5.7,
    cachedInputPerMillion: 0.475,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'Pixtral Large via fireworks (fireworks/pixtral-large) is a workhorse Mistral model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.9/M input tokens and $5.7/M output tokens, with cached input at $0.475/M. Modalities: text, tools, json, code, vision. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 1.6,
  },
  {
    id: 'fireworks/ministral-8b',
    provider: 'fireworks',
    displayName: 'Ministral 8B via fireworks',
    family: 'Mistral',
    release: '2024-10',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.095,
    outputPerMillion: 0.095,
    cachedInputPerMillion: 0.0238,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Ministral 8B via fireworks (fireworks/ministral-8b) is a utility Mistral model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.095/M input tokens and $0.095/M output tokens, with cached input at $0.0238/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-10.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'fireworks/deepseek-v3.2',
    provider: 'fireworks',
    displayName: 'DeepSeek V3.2 via fireworks',
    family: 'DeepSeek',
    release: '2025-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 163840,
    maxOutput: 8192,
    inputPerMillion: 0.2565,
    outputPerMillion: 1.045,
    cachedInputPerMillion: 0.0641,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'DeepSeek V3.2 via fireworks (fireworks/deepseek-v3.2) is a frontier DeepSeek model hosted by fireworks. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.2565/M input tokens and $1.045/M output tokens, with cached input at $0.0641/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-12.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'fireworks/deepseek-v3',
    provider: 'fireworks',
    displayName: 'DeepSeek V3 via fireworks',
    family: 'DeepSeek',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 163840,
    maxOutput: 8192,
    inputPerMillion: 0.2565,
    outputPerMillion: 1.045,
    cachedInputPerMillion: 0.0641,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'DeepSeek V3 via fireworks (fireworks/deepseek-v3) is a frontier DeepSeek model hosted by fireworks. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.2565/M input tokens and $1.045/M output tokens, with cached input at $0.0641/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'fireworks/deepseek-r1',
    provider: 'fireworks',
    displayName: 'DeepSeek R1 via fireworks',
    family: 'DeepSeek',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 163840,
    maxOutput: 8192,
    inputPerMillion: 0.5225,
    outputPerMillion: 2.0805,
    cachedInputPerMillion: 0.1306,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'reasoning',
    notes: 'DeepSeek R1 via fireworks (fireworks/deepseek-r1) is a reasoning DeepSeek model hosted by fireworks. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.5225/M input tokens and $2.0805/M output tokens, with cached input at $0.1306/M. Modalities: text, tools, json, code, reasoning. Tokenizer: deepseek. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'fireworks/deepseek-coder-v2',
    provider: 'fireworks',
    displayName: 'DeepSeek Coder V2 via fireworks',
    family: 'DeepSeek',
    release: '2024-06',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.133,
    outputPerMillion: 0.266,
    cachedInputPerMillion: 0.0333,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'DeepSeek Coder V2 via fireworks (fireworks/deepseek-coder-v2) is a workhorse DeepSeek model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.133/M input tokens and $0.266/M output tokens, with cached input at $0.0333/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-06.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'fireworks/qwen3-235b',
    provider: 'fireworks',
    displayName: 'Qwen3 235B via fireworks',
    family: 'Qwen',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.19,
    outputPerMillion: 0.57,
    cachedInputPerMillion: 0.0475,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'Qwen3 235B via fireworks (fireworks/qwen3-235b) is a frontier Qwen model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.19/M input tokens and $0.57/M output tokens, with cached input at $0.0475/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'fireworks/qwen3-32b',
    provider: 'fireworks',
    displayName: 'Qwen3 32B via fireworks',
    family: 'Qwen',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.095,
    outputPerMillion: 0.285,
    cachedInputPerMillion: 0.0238,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen3 32B via fireworks (fireworks/qwen3-32b) is a workhorse Qwen model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.095/M input tokens and $0.285/M output tokens, with cached input at $0.0238/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'fireworks/qwen2.5-72b',
    provider: 'fireworks',
    displayName: 'Qwen2.5 72B via fireworks',
    family: 'Qwen',
    release: '2024-09',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.114,
    outputPerMillion: 0.3705,
    cachedInputPerMillion: 0.0285,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen2.5 72B via fireworks (fireworks/qwen2.5-72b) is a workhorse Qwen model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.114/M input tokens and $0.3705/M output tokens, with cached input at $0.0285/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'fireworks/qwen2.5-coder-32b',
    provider: 'fireworks',
    displayName: 'Qwen2.5 Coder 32B via fireworks',
    family: 'Qwen',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.076,
    outputPerMillion: 0.171,
    cachedInputPerMillion: 0.019,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen2.5 Coder 32B via fireworks (fireworks/qwen2.5-coder-32b) is a workhorse Qwen model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.076/M input tokens and $0.171/M output tokens, with cached input at $0.019/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'fireworks/qwen-vl-max',
    provider: 'fireworks',
    displayName: 'Qwen VL Max via fireworks',
    family: 'Qwen',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 32768,
    maxOutput: 8192,
    inputPerMillion: 0.76,
    outputPerMillion: 3.04,
    cachedInputPerMillion: 0.19,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'Qwen VL Max via fireworks (fireworks/qwen-vl-max) is a workhorse Qwen model hosted by fireworks. It speaks openai-chat with a 32,768 token context window and a 8,192 token output cap. List price is $0.76/M input tokens and $3.04/M output tokens, with cached input at $0.19/M. Modalities: text, tools, json, code, vision. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 1.6,
  },
  {
    id: 'fireworks/kimi-k2.5',
    provider: 'fireworks',
    displayName: 'Kimi K2.5 via fireworks',
    family: 'Kimi',
    release: '2026-01',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 262144,
    maxOutput: 16384,
    inputPerMillion: 0.57,
    outputPerMillion: 2.85,
    cachedInputPerMillion: 0.1425,
    tokenizer: 'kimi',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Kimi K2.5 via fireworks (fireworks/kimi-k2.5) is a frontier Kimi model hosted by fireworks. It speaks openai-chat with a 262,144 token context window and a 16,384 token output cap. List price is $0.57/M input tokens and $2.85/M output tokens, with cached input at $0.1425/M. Modalities: text, tools, json, code. Tokenizer: kimi. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2026-01.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'fireworks/kimi-k2',
    provider: 'fireworks',
    displayName: 'Kimi K2 via fireworks',
    family: 'Kimi',
    release: '2025-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.57,
    outputPerMillion: 2.375,
    cachedInputPerMillion: 0.1425,
    tokenizer: 'kimi',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Kimi K2 via fireworks (fireworks/kimi-k2) is a frontier Kimi model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.57/M input tokens and $2.375/M output tokens, with cached input at $0.1425/M. Modalities: text, tools, json, code. Tokenizer: kimi. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['fireworks/llama-4-scout', 'fireworks/llama-3.3-70b', 'fireworks/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
];

export const FIREWORKS_MODEL_COUNT = FIREWORKS_MODELS.length;

export const MODEL_DOC_fireworks_llama_4_maverick = {
  id: 'fireworks/llama-4-maverick',
  summary: 'Llama 4 Maverick via fireworks (fireworks/llama-4-maverick) is a frontier Llama model hosted by fireworks. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.2565/M input tokens and $0.8075/M output tokens, with cached input at $0.0641/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer fireworks/llama-4-maverick when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000917.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_llama_4_scout = {
  id: 'fireworks/llama-4-scout',
  summary: 'Llama 4 Scout via fireworks (fireworks/llama-4-scout) is a workhorse Llama model hosted by fireworks. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.171/M input tokens and $0.5605/M output tokens, with cached input at $0.0427/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer fireworks/llama-4-scout when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000622.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_llama_3_3_70b = {
  id: 'fireworks/llama-3.3-70b',
  summary: 'Llama 3.3 70B via fireworks (fireworks/llama-3.3-70b) is a workhorse Llama model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.5605/M input tokens and $0.7505/M output tokens, with cached input at $0.1401/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer fireworks/llama-3.3-70b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001496.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_llama_3_1_8b = {
  id: 'fireworks/llama-3.1-8b',
  summary: 'Llama 3.1 8B via fireworks (fireworks/llama-3.1-8b) is a utility Llama model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.0475/M input tokens and $0.076/M output tokens, with cached input at $0.0119/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer fireworks/llama-3.1-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000133.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_fireworks_llama_3_1_405b = {
  id: 'fireworks/llama-3.1-405b',
  summary: 'Llama 3.1 405B via fireworks (fireworks/llama-3.1-405b) is a frontier Llama model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.7005/M input tokens and $1.7005/M output tokens, with cached input at $0.4251/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer fireworks/llama-3.1-405b when quality class is frontier and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.004251.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_mistral_large_2411 = {
  id: 'fireworks/mistral-large-2411',
  summary: 'Mistral Large 2411 via fireworks (fireworks/mistral-large-2411) is a frontier Mistral model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.9/M input tokens and $5.7/M output tokens, with cached input at $0.475/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer fireworks/mistral-large-2411 when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00665.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_mistral_small_3_1 = {
  id: 'fireworks/mistral-small-3.1',
  summary: 'Mistral Small 3.1 via fireworks (fireworks/mistral-small-3.1) is a workhorse Mistral model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.095/M input tokens and $0.285/M output tokens, with cached input at $0.0238/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
  routingHints: [
    'Prefer fireworks/mistral-small-3.1 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000333.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_codestral_2501 = {
  id: 'fireworks/codestral-2501',
  summary: 'Codestral 2501 via fireworks (fireworks/codestral-2501) is a workhorse Mistral model hosted by fireworks. It speaks openai-chat with a 262,144 token context window and a 16,384 token output cap. List price is $0.285/M input tokens and $0.855/M output tokens, with cached input at $0.0712/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer fireworks/codestral-2501 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000997.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_pixtral_large = {
  id: 'fireworks/pixtral-large',
  summary: 'Pixtral Large via fireworks (fireworks/pixtral-large) is a workhorse Mistral model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.9/M input tokens and $5.7/M output tokens, with cached input at $0.475/M. Modalities: text, tools, json, code, vision. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer fireworks/pixtral-large when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00665.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_ministral_8b = {
  id: 'fireworks/ministral-8b',
  summary: 'Ministral 8B via fireworks (fireworks/ministral-8b) is a utility Mistral model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.095/M input tokens and $0.095/M output tokens, with cached input at $0.0238/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-10.',
  routingHints: [
    'Prefer fireworks/ministral-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000237.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_fireworks_deepseek_v3_2 = {
  id: 'fireworks/deepseek-v3.2',
  summary: 'DeepSeek V3.2 via fireworks (fireworks/deepseek-v3.2) is a frontier DeepSeek model hosted by fireworks. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.2565/M input tokens and $1.045/M output tokens, with cached input at $0.0641/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-12.',
  routingHints: [
    'Prefer fireworks/deepseek-v3.2 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001035.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_deepseek_v3 = {
  id: 'fireworks/deepseek-v3',
  summary: 'DeepSeek V3 via fireworks (fireworks/deepseek-v3) is a frontier DeepSeek model hosted by fireworks. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.2565/M input tokens and $1.045/M output tokens, with cached input at $0.0641/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer fireworks/deepseek-v3 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001035.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_deepseek_r1 = {
  id: 'fireworks/deepseek-r1',
  summary: 'DeepSeek R1 via fireworks (fireworks/deepseek-r1) is a reasoning DeepSeek model hosted by fireworks. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.5225/M input tokens and $2.0805/M output tokens, with cached input at $0.1306/M. Modalities: text, tools, json, code, reasoning. Tokenizer: deepseek. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer fireworks/deepseek-r1 when quality class is reasoning and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.002085.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_deepseek_coder_v2 = {
  id: 'fireworks/deepseek-coder-v2',
  summary: 'DeepSeek Coder V2 via fireworks (fireworks/deepseek-coder-v2) is a workhorse DeepSeek model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.133/M input tokens and $0.266/M output tokens, with cached input at $0.0333/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-06.',
  routingHints: [
    'Prefer fireworks/deepseek-coder-v2 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000399.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_qwen3_235b = {
  id: 'fireworks/qwen3-235b',
  summary: 'Qwen3 235B via fireworks (fireworks/qwen3-235b) is a frontier Qwen model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.19/M input tokens and $0.57/M output tokens, with cached input at $0.0475/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer fireworks/qwen3-235b when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000665.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_qwen3_32b = {
  id: 'fireworks/qwen3-32b',
  summary: 'Qwen3 32B via fireworks (fireworks/qwen3-32b) is a workhorse Qwen model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.095/M input tokens and $0.285/M output tokens, with cached input at $0.0238/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer fireworks/qwen3-32b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000333.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_qwen2_5_72b = {
  id: 'fireworks/qwen2.5-72b',
  summary: 'Qwen2.5 72B via fireworks (fireworks/qwen2.5-72b) is a workhorse Qwen model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.114/M input tokens and $0.3705/M output tokens, with cached input at $0.0285/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
  routingHints: [
    'Prefer fireworks/qwen2.5-72b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000413.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_qwen2_5_coder_32b = {
  id: 'fireworks/qwen2.5-coder-32b',
  summary: 'Qwen2.5 Coder 32B via fireworks (fireworks/qwen2.5-coder-32b) is a workhorse Qwen model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.076/M input tokens and $0.171/M output tokens, with cached input at $0.019/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer fireworks/qwen2.5-coder-32b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000237.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_qwen_vl_max = {
  id: 'fireworks/qwen-vl-max',
  summary: 'Qwen VL Max via fireworks (fireworks/qwen-vl-max) is a workhorse Qwen model hosted by fireworks. It speaks openai-chat with a 32,768 token context window and a 8,192 token output cap. List price is $0.76/M input tokens and $3.04/M output tokens, with cached input at $0.19/M. Modalities: text, tools, json, code, vision. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer fireworks/qwen-vl-max when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00304.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_kimi_k2_5 = {
  id: 'fireworks/kimi-k2.5',
  summary: 'Kimi K2.5 via fireworks (fireworks/kimi-k2.5) is a frontier Kimi model hosted by fireworks. It speaks openai-chat with a 262,144 token context window and a 16,384 token output cap. List price is $0.57/M input tokens and $2.85/M output tokens, with cached input at $0.1425/M. Modalities: text, tools, json, code. Tokenizer: kimi. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2026-01.',
  routingHints: [
    'Prefer fireworks/kimi-k2.5 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.002565.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_fireworks_kimi_k2 = {
  id: 'fireworks/kimi-k2',
  summary: 'Kimi K2 via fireworks (fireworks/kimi-k2) is a frontier Kimi model hosted by fireworks. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.57/M input tokens and $2.375/M output tokens, with cached input at $0.1425/M. Modalities: text, tools, json, code. Tokenizer: kimi. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
  routingHints: [
    'Prefer fireworks/kimi-k2 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.002328.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

