import type { Modality, ModelSpec, Protocol } from "../types";

export const GOOGLE_MODELS: ModelSpec[] = [
  {
    id: 'google/gemini-2.5-pro',
    provider: 'google',
    displayName: 'Gemini 2.5 Pro',
    family: 'gemini-2.5',
    release: '2025-03',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'audio'] as Modality[],
    protocol: 'google-generate' as Protocol,
    contextWindow: 1048576,
    maxOutput: 65536,
    inputPerMillion: 1.25,
    outputPerMillion: 10.0,
    cachedInputPerMillion: 0.31,
    tokenizer: 'gemini',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-central', 'eu-west', 'asia-northeast'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'Gemini 2.5 Pro (google/gemini-2.5-pro) is a frontier gemini-2.5 model hosted by google. It speaks google-generate with a 1,048,576 token context window and a 65,536 token output cap. List price is $1.25/M input tokens and $10.0/M output tokens, with cached input at $0.31/M. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['google/gemini-2.5-flash', 'google/gemini-2.5-flash-lite', 'google/gemini-2.0-flash'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'google/gemini-2.5-flash',
    provider: 'google',
    displayName: 'Gemini 2.5 Flash',
    family: 'gemini-2.5',
    release: '2025-03',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'audio'] as Modality[],
    protocol: 'google-generate' as Protocol,
    contextWindow: 1048576,
    maxOutput: 65536,
    inputPerMillion: 0.15,
    outputPerMillion: 0.6,
    cachedInputPerMillion: 0.0375,
    tokenizer: 'gemini',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-central', 'eu-west', 'asia-northeast'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Gemini 2.5 Flash (google/gemini-2.5-flash) is a workhorse gemini-2.5 model hosted by google. It speaks google-generate with a 1,048,576 token context window and a 65,536 token output cap. List price is $0.15/M input tokens and $0.6/M output tokens, with cached input at $0.0375/M. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['google/gemini-2.5-flash-lite', 'google/gemini-2.0-flash', 'google/gemini-1.5-pro'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'google/gemini-2.5-flash-lite',
    provider: 'google',
    displayName: 'Gemini 2.5 Flash-Lite',
    family: 'gemini-2.5',
    release: '2025-06',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'audio'] as Modality[],
    protocol: 'google-generate' as Protocol,
    contextWindow: 1048576,
    maxOutput: 65536,
    inputPerMillion: 0.07,
    outputPerMillion: 0.3,
    cachedInputPerMillion: 0.0175,
    tokenizer: 'gemini',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-central', 'eu-west', 'asia-northeast'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Gemini 2.5 Flash-Lite (google/gemini-2.5-flash-lite) is a utility gemini-2.5 model hosted by google. It speaks google-generate with a 1,048,576 token context window and a 65,536 token output cap. List price is $0.07/M input tokens and $0.3/M output tokens, with cached input at $0.0175/M. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-06.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['google/gemini-2.5-flash', 'google/gemini-2.0-flash', 'google/gemini-1.5-pro'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'google/gemini-2.0-flash',
    provider: 'google',
    displayName: 'Gemini 2.0 Flash',
    family: 'gemini-2.0',
    release: '2024-12',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'audio'] as Modality[],
    protocol: 'google-generate' as Protocol,
    contextWindow: 1048576,
    maxOutput: 8192,
    inputPerMillion: 0.1,
    outputPerMillion: 0.4,
    cachedInputPerMillion: 0.025,
    tokenizer: 'gemini',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-central', 'eu-west', 'asia-northeast'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Gemini 2.0 Flash (google/gemini-2.0-flash) is a workhorse gemini-2.0 model hosted by google. It speaks google-generate with a 1,048,576 token context window and a 8,192 token output cap. List price is $0.1/M input tokens and $0.4/M output tokens, with cached input at $0.025/M. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['google/gemini-2.5-flash', 'google/gemini-2.5-flash-lite', 'google/gemini-1.5-pro'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'google/gemini-1.5-pro',
    provider: 'google',
    displayName: 'Gemini 1.5 Pro',
    family: 'gemini-1.5',
    release: '2024-04',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'audio'] as Modality[],
    protocol: 'google-generate' as Protocol,
    contextWindow: 2097152,
    maxOutput: 8192,
    inputPerMillion: 1.25,
    outputPerMillion: 5.0,
    cachedInputPerMillion: 0.31,
    tokenizer: 'gemini',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-central', 'eu-west', 'asia-northeast'],
    status: 'legacy',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'Gemini 1.5 Pro (google/gemini-1.5-pro) is a workhorse gemini-1.5 model hosted by google. It speaks google-generate with a 2,097,152 token context window and a 8,192 token output cap. List price is $1.25/M input tokens and $5.0/M output tokens, with cached input at $0.31/M. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: legacy. Released 2024-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['google/gemini-2.5-flash', 'google/gemini-2.5-flash-lite', 'google/gemini-2.0-flash'],
    carbonGPerMTok: 1.6,
  },
  {
    id: 'google/gemma-3-27b',
    provider: 'google',
    displayName: 'Gemma 3 27B',
    family: 'gemma-3',
    release: '2025-03',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'audio'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.09,
    outputPerMillion: 0.16,
    cachedInputPerMillion: undefined,
    tokenizer: 'gemini',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-central', 'eu-west', 'asia-northeast'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Gemma 3 27B (google/gemma-3-27b) is a workhorse gemma-3 model hosted by google. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.09/M input tokens and $0.16/M output tokens. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['google/gemini-2.5-flash', 'google/gemini-2.5-flash-lite', 'google/gemini-2.0-flash'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'google/gemma-3-12b',
    provider: 'google',
    displayName: 'Gemma 3 12B',
    family: 'gemma-3',
    release: '2025-03',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'audio'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.05,
    outputPerMillion: 0.1,
    cachedInputPerMillion: undefined,
    tokenizer: 'gemini',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-central', 'eu-west', 'asia-northeast'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'utility',
    notes: 'Gemma 3 12B (google/gemma-3-12b) is a utility gemma-3 model hosted by google. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.05/M input tokens and $0.1/M output tokens. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['google/gemini-2.5-flash', 'google/gemini-2.5-flash-lite', 'google/gemini-2.0-flash'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'google/gemini-embedding-001',
    provider: 'google',
    displayName: 'Gemini Embedding 001',
    family: 'embeddings',
    release: '2025-01',
    modality: ['embed'] as Modality[],
    protocol: 'openai-embeddings' as Protocol,
    contextWindow: 2048,
    maxOutput: 0,
    inputPerMillion: 0.15,
    outputPerMillion: 0.0,
    cachedInputPerMillion: undefined,
    tokenizer: 'gemini',
    streaming: false,
    tools: false,
    jsonMode: false,
    vision: false,
    regions: ['us-central', 'eu-west', 'asia-northeast'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Gemini Embedding 001 (google/gemini-embedding-001) is a workhorse embeddings model hosted by google. It speaks openai-embeddings with a 2,048 token context window and a 0 token output cap. List price is $0.15/M input tokens and $0.0/M output tokens. Modalities: embed. Tokenizer: gemini. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['semantic search', 'cluster labeling', 'cache keys', 'dedup'],
    fallbacks: ['google/gemini-2.5-flash', 'google/gemini-2.5-flash-lite', 'google/gemini-2.0-flash'],
    carbonGPerMTok: 0.9,
  },
];

export const GOOGLE_MODEL_COUNT = GOOGLE_MODELS.length;

export const MODEL_DOC_google_gemini_2_5_pro = {
  id: 'google/gemini-2.5-pro',
  summary: 'Gemini 2.5 Pro (google/gemini-2.5-pro) is a frontier gemini-2.5 model hosted by google. It speaks google-generate with a 1,048,576 token context window and a 65,536 token output cap. List price is $1.25/M input tokens and $10.0/M output tokens, with cached input at $0.31/M. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
  routingHints: [
    'Prefer google/gemini-2.5-pro when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0075.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol google-generate; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_google_gemini_2_5_flash = {
  id: 'google/gemini-2.5-flash',
  summary: 'Gemini 2.5 Flash (google/gemini-2.5-flash) is a workhorse gemini-2.5 model hosted by google. It speaks google-generate with a 1,048,576 token context window and a 65,536 token output cap. List price is $0.15/M input tokens and $0.6/M output tokens, with cached input at $0.0375/M. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
  routingHints: [
    'Prefer google/gemini-2.5-flash when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0006.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol google-generate; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_google_gemini_2_5_flash_lite = {
  id: 'google/gemini-2.5-flash-lite',
  summary: 'Gemini 2.5 Flash-Lite (google/gemini-2.5-flash-lite) is a utility gemini-2.5 model hosted by google. It speaks google-generate with a 1,048,576 token context window and a 65,536 token output cap. List price is $0.07/M input tokens and $0.3/M output tokens, with cached input at $0.0175/M. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-06.',
  routingHints: [
    'Prefer google/gemini-2.5-flash-lite when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00029.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol google-generate; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_google_gemini_2_0_flash = {
  id: 'google/gemini-2.0-flash',
  summary: 'Gemini 2.0 Flash (google/gemini-2.0-flash) is a workhorse gemini-2.0 model hosted by google. It speaks google-generate with a 1,048,576 token context window and a 8,192 token output cap. List price is $0.1/M input tokens and $0.4/M output tokens, with cached input at $0.025/M. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer google/gemini-2.0-flash when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0004.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol google-generate; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_google_gemini_1_5_pro = {
  id: 'google/gemini-1.5-pro',
  summary: 'Gemini 1.5 Pro (google/gemini-1.5-pro) is a workhorse gemini-1.5 model hosted by google. It speaks google-generate with a 2,097,152 token context window and a 8,192 token output cap. List price is $1.25/M input tokens and $5.0/M output tokens, with cached input at $0.31/M. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: legacy. Released 2024-04.',
  routingHints: [
    'Prefer google/gemini-1.5-pro when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.005.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol google-generate; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_google_gemma_3_27b = {
  id: 'google/gemma-3-27b',
  summary: 'Gemma 3 27B (google/gemma-3-27b) is a workhorse gemma-3 model hosted by google. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.09/M input tokens and $0.16/M output tokens. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
  routingHints: [
    'Prefer google/gemma-3-27b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00026.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_google_gemma_3_12b = {
  id: 'google/gemma-3-12b',
  summary: 'Gemma 3 12B (google/gemma-3-12b) is a utility gemma-3 model hosted by google. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.05/M input tokens and $0.1/M output tokens. Modalities: text, vision, tools, json, code, audio. Tokenizer: gemini. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
  routingHints: [
    'Prefer google/gemma-3-12b when quality class is utility and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00015.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_google_gemini_embedding_001 = {
  id: 'google/gemini-embedding-001',
  summary: 'Gemini Embedding 001 (google/gemini-embedding-001) is a workhorse embeddings model hosted by google. It speaks openai-embeddings with a 2,048 token context window and a 0 token output cap. List price is $0.15/M input tokens and $0.0/M output tokens. Modalities: embed. Tokenizer: gemini. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer google/gemini-embedding-001 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 0 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0003.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-embeddings; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

