import type { Modality, ModelSpec, Protocol } from "../types";

export const GROQ_MODELS: ModelSpec[] = [
  {
    id: 'groq/llama-4-maverick',
    provider: 'groq',
    displayName: 'Llama 4 Maverick via groq',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.189,
    outputPerMillion: 0.595,
    cachedInputPerMillion: 0.0473,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'frontier',
    notes: 'Llama 4 Maverick via groq (groq/llama-4-maverick) is a frontier Llama model hosted by groq. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.189/M input tokens and $0.595/M output tokens, with cached input at $0.0473/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['groq/llama-4-scout', 'groq/llama-3.3-70b', 'groq/llama-3.1-8b'],
    carbonGPerMTok: 0.56,
  },
  {
    id: 'groq/llama-4-scout',
    provider: 'groq',
    displayName: 'Llama 4 Scout via groq',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.126,
    outputPerMillion: 0.413,
    cachedInputPerMillion: 0.0315,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'workhorse',
    notes: 'Llama 4 Scout via groq (groq/llama-4-scout) is a workhorse Llama model hosted by groq. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.126/M input tokens and $0.413/M output tokens, with cached input at $0.0315/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['groq/llama-3.3-70b', 'groq/llama-3.1-8b', 'groq/llama-4-scout-groq'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'groq/llama-3.3-70b',
    provider: 'groq',
    displayName: 'Llama 3.3 70B via groq',
    family: 'Llama',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.413,
    outputPerMillion: 0.553,
    cachedInputPerMillion: 0.1032,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'workhorse',
    notes: 'Llama 3.3 70B via groq (groq/llama-3.3-70b) is a workhorse Llama model hosted by groq. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.413/M input tokens and $0.553/M output tokens, with cached input at $0.1032/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['groq/llama-4-scout', 'groq/llama-3.1-8b', 'groq/llama-4-scout-groq'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'groq/llama-3.1-8b',
    provider: 'groq',
    displayName: 'Llama 3.1 8B via groq',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.035,
    outputPerMillion: 0.056,
    cachedInputPerMillion: 0.0087,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Llama 3.1 8B via groq (groq/llama-3.1-8b) is a utility Llama model hosted by groq. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.035/M input tokens and $0.056/M output tokens, with cached input at $0.0087/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['groq/llama-4-scout', 'groq/llama-3.3-70b', 'groq/llama-4-scout-groq'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'groq/llama-3.1-405b',
    provider: 'groq',
    displayName: 'Llama 3.1 405B via groq',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 1.253,
    outputPerMillion: 1.253,
    cachedInputPerMillion: 0.3132,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'frontier',
    notes: 'Llama 3.1 405B via groq (groq/llama-3.1-405b) is a frontier Llama model hosted by groq. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.253/M input tokens and $1.253/M output tokens, with cached input at $0.3132/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['groq/llama-4-scout', 'groq/llama-3.3-70b', 'groq/llama-3.1-8b'],
    carbonGPerMTok: 0.56,
  },
  {
    id: 'groq/llama-4-scout-groq',
    provider: 'groq',
    displayName: 'Llama 4 Scout on Groq LPU',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.11,
    outputPerMillion: 0.34,
    cachedInputPerMillion: 0.03,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'workhorse',
    notes: 'Llama 4 Scout on Groq LPU (groq/llama-4-scout-groq) is a workhorse Llama model hosted by groq. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.11/M input tokens and $0.34/M output tokens, with cached input at $0.03/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['groq/llama-4-scout', 'groq/llama-3.3-70b', 'groq/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'groq/qwen3-32b-groq',
    provider: 'groq',
    displayName: 'Qwen3 32B on Groq LPU',
    family: 'Qwen',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.29,
    outputPerMillion: 0.59,
    cachedInputPerMillion: undefined,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'workhorse',
    notes: 'Qwen3 32B on Groq LPU (groq/qwen3-32b-groq) is a workhorse Qwen model hosted by groq. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.29/M input tokens and $0.59/M output tokens. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['groq/llama-4-scout', 'groq/llama-3.3-70b', 'groq/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
];

export const GROQ_MODEL_COUNT = GROQ_MODELS.length;

export const MODEL_DOC_groq_llama_4_maverick = {
  id: 'groq/llama-4-maverick',
  summary: 'Llama 4 Maverick via groq (groq/llama-4-maverick) is a frontier Llama model hosted by groq. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.189/M input tokens and $0.595/M output tokens, with cached input at $0.0473/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer groq/llama-4-maverick when quality class is frontier and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000675.',
    'Carbon intensity about 0.56 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_groq_llama_4_scout = {
  id: 'groq/llama-4-scout',
  summary: 'Llama 4 Scout via groq (groq/llama-4-scout) is a workhorse Llama model hosted by groq. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.126/M input tokens and $0.413/M output tokens, with cached input at $0.0315/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer groq/llama-4-scout when quality class is workhorse and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000458.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_groq_llama_3_3_70b = {
  id: 'groq/llama-3.3-70b',
  summary: 'Llama 3.3 70B via groq (groq/llama-3.3-70b) is a workhorse Llama model hosted by groq. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.413/M input tokens and $0.553/M output tokens, with cached input at $0.1032/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer groq/llama-3.3-70b when quality class is workhorse and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001102.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_groq_llama_3_1_8b = {
  id: 'groq/llama-3.1-8b',
  summary: 'Llama 3.1 8B via groq (groq/llama-3.1-8b) is a utility Llama model hosted by groq. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.035/M input tokens and $0.056/M output tokens, with cached input at $0.0087/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer groq/llama-3.1-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $9.8e-05.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_groq_llama_3_1_405b = {
  id: 'groq/llama-3.1-405b',
  summary: 'Llama 3.1 405B via groq (groq/llama-3.1-405b) is a frontier Llama model hosted by groq. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.253/M input tokens and $1.253/M output tokens, with cached input at $0.3132/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer groq/llama-3.1-405b when quality class is frontier and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.003132.',
    'Carbon intensity about 0.56 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_groq_llama_4_scout_groq = {
  id: 'groq/llama-4-scout-groq',
  summary: 'Llama 4 Scout on Groq LPU (groq/llama-4-scout-groq) is a workhorse Llama model hosted by groq. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.11/M input tokens and $0.34/M output tokens, with cached input at $0.03/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer groq/llama-4-scout-groq when quality class is workhorse and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00039.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_groq_qwen3_32b_groq = {
  id: 'groq/qwen3-32b-groq',
  summary: 'Qwen3 32B on Groq LPU (groq/qwen3-32b-groq) is a workhorse Qwen model hosted by groq. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.29/M input tokens and $0.59/M output tokens. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer groq/qwen3-32b-groq when quality class is workhorse and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000875.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

