import type { Modality, ModelSpec, Protocol } from "../types";

export const HUGGINGFACE_MODELS: ModelSpec[] = [
  {
    id: 'huggingface/llama-4-maverick',
    provider: 'huggingface',
    displayName: 'Llama 4 Maverick via huggingface',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.27,
    outputPerMillion: 0.85,
    cachedInputPerMillion: 0.0675,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Llama 4 Maverick via huggingface (huggingface/llama-4-maverick) is a frontier Llama model hosted by huggingface. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.27/M input tokens and $0.85/M output tokens, with cached input at $0.0675/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['huggingface/llama-4-scout', 'huggingface/llama-3.3-70b', 'huggingface/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'huggingface/llama-4-scout',
    provider: 'huggingface',
    displayName: 'Llama 4 Scout via huggingface',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.18,
    outputPerMillion: 0.59,
    cachedInputPerMillion: 0.045,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 4 Scout via huggingface (huggingface/llama-4-scout) is a workhorse Llama model hosted by huggingface. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.18/M input tokens and $0.59/M output tokens, with cached input at $0.045/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['huggingface/llama-3.3-70b', 'huggingface/llama-3.1-8b', 'huggingface/qwen3-32b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'huggingface/llama-3.3-70b',
    provider: 'huggingface',
    displayName: 'Llama 3.3 70B via huggingface',
    family: 'Llama',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.59,
    outputPerMillion: 0.79,
    cachedInputPerMillion: 0.1475,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 3.3 70B via huggingface (huggingface/llama-3.3-70b) is a workhorse Llama model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.59/M input tokens and $0.79/M output tokens, with cached input at $0.1475/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['huggingface/llama-4-scout', 'huggingface/llama-3.1-8b', 'huggingface/qwen3-32b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'huggingface/llama-3.1-8b',
    provider: 'huggingface',
    displayName: 'Llama 3.1 8B via huggingface',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.05,
    outputPerMillion: 0.08,
    cachedInputPerMillion: 0.0125,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Llama 3.1 8B via huggingface (huggingface/llama-3.1-8b) is a utility Llama model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.05/M input tokens and $0.08/M output tokens, with cached input at $0.0125/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['huggingface/llama-4-scout', 'huggingface/llama-3.3-70b', 'huggingface/qwen3-32b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'huggingface/llama-3.1-405b',
    provider: 'huggingface',
    displayName: 'Llama 3.1 405B via huggingface',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 1.79,
    outputPerMillion: 1.79,
    cachedInputPerMillion: 0.4475,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'frontier',
    notes: 'Llama 3.1 405B via huggingface (huggingface/llama-3.1-405b) is a frontier Llama model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.79/M input tokens and $1.79/M output tokens, with cached input at $0.4475/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['huggingface/llama-4-scout', 'huggingface/llama-3.3-70b', 'huggingface/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'huggingface/qwen3-235b',
    provider: 'huggingface',
    displayName: 'Qwen3 235B via huggingface',
    family: 'Qwen',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.2,
    outputPerMillion: 0.6,
    cachedInputPerMillion: 0.05,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'Qwen3 235B via huggingface (huggingface/qwen3-235b) is a frontier Qwen model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.2/M input tokens and $0.6/M output tokens, with cached input at $0.05/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['huggingface/llama-4-scout', 'huggingface/llama-3.3-70b', 'huggingface/llama-3.1-8b'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'huggingface/qwen3-32b',
    provider: 'huggingface',
    displayName: 'Qwen3 32B via huggingface',
    family: 'Qwen',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.1,
    outputPerMillion: 0.3,
    cachedInputPerMillion: 0.025,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen3 32B via huggingface (huggingface/qwen3-32b) is a workhorse Qwen model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.1/M input tokens and $0.3/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['huggingface/llama-4-scout', 'huggingface/llama-3.3-70b', 'huggingface/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'huggingface/qwen2.5-72b',
    provider: 'huggingface',
    displayName: 'Qwen2.5 72B via huggingface',
    family: 'Qwen',
    release: '2024-09',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.12,
    outputPerMillion: 0.39,
    cachedInputPerMillion: 0.03,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen2.5 72B via huggingface (huggingface/qwen2.5-72b) is a workhorse Qwen model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.12/M input tokens and $0.39/M output tokens, with cached input at $0.03/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['huggingface/llama-4-scout', 'huggingface/llama-3.3-70b', 'huggingface/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'huggingface/qwen2.5-coder-32b',
    provider: 'huggingface',
    displayName: 'Qwen2.5 Coder 32B via huggingface',
    family: 'Qwen',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.08,
    outputPerMillion: 0.18,
    cachedInputPerMillion: 0.02,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen2.5 Coder 32B via huggingface (huggingface/qwen2.5-coder-32b) is a workhorse Qwen model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.08/M input tokens and $0.18/M output tokens, with cached input at $0.02/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['huggingface/llama-4-scout', 'huggingface/llama-3.3-70b', 'huggingface/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'huggingface/qwen-vl-max',
    provider: 'huggingface',
    displayName: 'Qwen VL Max via huggingface',
    family: 'Qwen',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 32768,
    maxOutput: 8192,
    inputPerMillion: 0.8,
    outputPerMillion: 3.2,
    cachedInputPerMillion: 0.2,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'Qwen VL Max via huggingface (huggingface/qwen-vl-max) is a workhorse Qwen model hosted by huggingface. It speaks openai-chat with a 32,768 token context window and a 8,192 token output cap. List price is $0.8/M input tokens and $3.2/M output tokens, with cached input at $0.2/M. Modalities: text, tools, json, code, vision. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['huggingface/llama-4-scout', 'huggingface/llama-3.3-70b', 'huggingface/llama-3.1-8b'],
    carbonGPerMTok: 1.6,
  },
];

export const HUGGINGFACE_MODEL_COUNT = HUGGINGFACE_MODELS.length;

export const MODEL_DOC_huggingface_llama_4_maverick = {
  id: 'huggingface/llama-4-maverick',
  summary: 'Llama 4 Maverick via huggingface (huggingface/llama-4-maverick) is a frontier Llama model hosted by huggingface. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.27/M input tokens and $0.85/M output tokens, with cached input at $0.0675/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer huggingface/llama-4-maverick when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000965.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_huggingface_llama_4_scout = {
  id: 'huggingface/llama-4-scout',
  summary: 'Llama 4 Scout via huggingface (huggingface/llama-4-scout) is a workhorse Llama model hosted by huggingface. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.18/M input tokens and $0.59/M output tokens, with cached input at $0.045/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer huggingface/llama-4-scout when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000655.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_huggingface_llama_3_3_70b = {
  id: 'huggingface/llama-3.3-70b',
  summary: 'Llama 3.3 70B via huggingface (huggingface/llama-3.3-70b) is a workhorse Llama model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.59/M input tokens and $0.79/M output tokens, with cached input at $0.1475/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer huggingface/llama-3.3-70b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001575.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_huggingface_llama_3_1_8b = {
  id: 'huggingface/llama-3.1-8b',
  summary: 'Llama 3.1 8B via huggingface (huggingface/llama-3.1-8b) is a utility Llama model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.05/M input tokens and $0.08/M output tokens, with cached input at $0.0125/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer huggingface/llama-3.1-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00014.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_huggingface_llama_3_1_405b = {
  id: 'huggingface/llama-3.1-405b',
  summary: 'Llama 3.1 405B via huggingface (huggingface/llama-3.1-405b) is a frontier Llama model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.79/M input tokens and $1.79/M output tokens, with cached input at $0.4475/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer huggingface/llama-3.1-405b when quality class is frontier and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.004475.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_huggingface_qwen3_235b = {
  id: 'huggingface/qwen3-235b',
  summary: 'Qwen3 235B via huggingface (huggingface/qwen3-235b) is a frontier Qwen model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.2/M input tokens and $0.6/M output tokens, with cached input at $0.05/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer huggingface/qwen3-235b when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0007.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_huggingface_qwen3_32b = {
  id: 'huggingface/qwen3-32b',
  summary: 'Qwen3 32B via huggingface (huggingface/qwen3-32b) is a workhorse Qwen model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.1/M input tokens and $0.3/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer huggingface/qwen3-32b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00035.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_huggingface_qwen2_5_72b = {
  id: 'huggingface/qwen2.5-72b',
  summary: 'Qwen2.5 72B via huggingface (huggingface/qwen2.5-72b) is a workhorse Qwen model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.12/M input tokens and $0.39/M output tokens, with cached input at $0.03/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
  routingHints: [
    'Prefer huggingface/qwen2.5-72b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000435.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_huggingface_qwen2_5_coder_32b = {
  id: 'huggingface/qwen2.5-coder-32b',
  summary: 'Qwen2.5 Coder 32B via huggingface (huggingface/qwen2.5-coder-32b) is a workhorse Qwen model hosted by huggingface. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.08/M input tokens and $0.18/M output tokens, with cached input at $0.02/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer huggingface/qwen2.5-coder-32b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00025.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_huggingface_qwen_vl_max = {
  id: 'huggingface/qwen-vl-max',
  summary: 'Qwen VL Max via huggingface (huggingface/qwen-vl-max) is a workhorse Qwen model hosted by huggingface. It speaks openai-chat with a 32,768 token context window and a 8,192 token output cap. List price is $0.8/M input tokens and $3.2/M output tokens, with cached input at $0.2/M. Modalities: text, tools, json, code, vision. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer huggingface/qwen-vl-max when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0032.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

