import type { Modality, ModelSpec, Protocol } from "../types";

export const MISTRAL_MODELS: ModelSpec[] = [
  {
    id: 'mistral/mistral-large-2411',
    provider: 'mistral',
    displayName: 'Mistral Large 2411 via mistral',
    family: 'Mistral',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 2.0,
    outputPerMillion: 6.0,
    cachedInputPerMillion: 0.5,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'Mistral Large 2411 via mistral (mistral/mistral-large-2411) is a frontier Mistral model hosted by mistral. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.0/M input tokens and $6.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['mistral/mistral-small-3.1', 'mistral/codestral-2501', 'mistral/pixtral-large'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'mistral/mistral-small-3.1',
    provider: 'mistral',
    displayName: 'Mistral Small 3.1 via mistral',
    family: 'Mistral',
    release: '2025-03',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.1,
    outputPerMillion: 0.3,
    cachedInputPerMillion: 0.025,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Mistral Small 3.1 via mistral (mistral/mistral-small-3.1) is a workhorse Mistral model hosted by mistral. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.1/M input tokens and $0.3/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['mistral/codestral-2501', 'mistral/pixtral-large', 'mistral/ministral-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'mistral/codestral-2501',
    provider: 'mistral',
    displayName: 'Codestral 2501 via mistral',
    family: 'Mistral',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 262144,
    maxOutput: 16384,
    inputPerMillion: 0.3,
    outputPerMillion: 0.9,
    cachedInputPerMillion: 0.075,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Codestral 2501 via mistral (mistral/codestral-2501) is a workhorse Mistral model hosted by mistral. It speaks openai-chat with a 262,144 token context window and a 16,384 token output cap. List price is $0.3/M input tokens and $0.9/M output tokens, with cached input at $0.075/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['mistral/mistral-small-3.1', 'mistral/pixtral-large', 'mistral/ministral-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'mistral/pixtral-large',
    provider: 'mistral',
    displayName: 'Pixtral Large via mistral',
    family: 'Mistral',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 2.0,
    outputPerMillion: 6.0,
    cachedInputPerMillion: 0.5,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'Pixtral Large via mistral (mistral/pixtral-large) is a workhorse Mistral model hosted by mistral. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.0/M input tokens and $6.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, code, vision. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['mistral/mistral-small-3.1', 'mistral/codestral-2501', 'mistral/ministral-8b'],
    carbonGPerMTok: 1.6,
  },
  {
    id: 'mistral/ministral-8b',
    provider: 'mistral',
    displayName: 'Ministral 8B via mistral',
    family: 'Mistral',
    release: '2024-10',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.1,
    outputPerMillion: 0.1,
    cachedInputPerMillion: 0.025,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Ministral 8B via mistral (mistral/ministral-8b) is a utility Mistral model hosted by mistral. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.1/M input tokens and $0.1/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-10.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['mistral/mistral-small-3.1', 'mistral/codestral-2501', 'mistral/pixtral-large'],
    carbonGPerMTok: 0.4,
  },
];

export const MISTRAL_MODEL_COUNT = MISTRAL_MODELS.length;

export const MODEL_DOC_mistral_mistral_large_2411 = {
  id: 'mistral/mistral-large-2411',
  summary: 'Mistral Large 2411 via mistral (mistral/mistral-large-2411) is a frontier Mistral model hosted by mistral. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.0/M input tokens and $6.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer mistral/mistral-large-2411 when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.007.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_mistral_mistral_small_3_1 = {
  id: 'mistral/mistral-small-3.1',
  summary: 'Mistral Small 3.1 via mistral (mistral/mistral-small-3.1) is a workhorse Mistral model hosted by mistral. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.1/M input tokens and $0.3/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
  routingHints: [
    'Prefer mistral/mistral-small-3.1 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00035.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_mistral_codestral_2501 = {
  id: 'mistral/codestral-2501',
  summary: 'Codestral 2501 via mistral (mistral/codestral-2501) is a workhorse Mistral model hosted by mistral. It speaks openai-chat with a 262,144 token context window and a 16,384 token output cap. List price is $0.3/M input tokens and $0.9/M output tokens, with cached input at $0.075/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer mistral/codestral-2501 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00105.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_mistral_pixtral_large = {
  id: 'mistral/pixtral-large',
  summary: 'Pixtral Large via mistral (mistral/pixtral-large) is a workhorse Mistral model hosted by mistral. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.0/M input tokens and $6.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, code, vision. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer mistral/pixtral-large when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.007.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_mistral_ministral_8b = {
  id: 'mistral/ministral-8b',
  summary: 'Ministral 8B via mistral (mistral/ministral-8b) is a utility Mistral model hosted by mistral. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.1/M input tokens and $0.1/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-10.',
  routingHints: [
    'Prefer mistral/ministral-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00025.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

