import type { Modality, ModelSpec, Protocol } from "../types";

export const NVIDIA_MODELS: ModelSpec[] = [
  {
    id: 'nvidia/llama-4-maverick',
    provider: 'nvidia',
    displayName: 'Llama 4 Maverick via nvidia',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.297,
    outputPerMillion: 0.935,
    cachedInputPerMillion: 0.0743,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Llama 4 Maverick via nvidia (nvidia/llama-4-maverick) is a frontier Llama model hosted by nvidia. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.297/M input tokens and $0.935/M output tokens, with cached input at $0.0743/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['nvidia/llama-4-scout', 'nvidia/llama-3.3-70b', 'nvidia/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'nvidia/llama-4-scout',
    provider: 'nvidia',
    displayName: 'Llama 4 Scout via nvidia',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.198,
    outputPerMillion: 0.649,
    cachedInputPerMillion: 0.0495,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 4 Scout via nvidia (nvidia/llama-4-scout) is a workhorse Llama model hosted by nvidia. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.198/M input tokens and $0.649/M output tokens, with cached input at $0.0495/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['nvidia/llama-3.3-70b', 'nvidia/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'nvidia/llama-3.3-70b',
    provider: 'nvidia',
    displayName: 'Llama 3.3 70B via nvidia',
    family: 'Llama',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.649,
    outputPerMillion: 0.869,
    cachedInputPerMillion: 0.1623,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 3.3 70B via nvidia (nvidia/llama-3.3-70b) is a workhorse Llama model hosted by nvidia. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.649/M input tokens and $0.869/M output tokens, with cached input at $0.1623/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['nvidia/llama-4-scout', 'nvidia/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'nvidia/llama-3.1-8b',
    provider: 'nvidia',
    displayName: 'Llama 3.1 8B via nvidia',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.055,
    outputPerMillion: 0.088,
    cachedInputPerMillion: 0.0138,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Llama 3.1 8B via nvidia (nvidia/llama-3.1-8b) is a utility Llama model hosted by nvidia. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.055/M input tokens and $0.088/M output tokens, with cached input at $0.0138/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['nvidia/llama-4-scout', 'nvidia/llama-3.3-70b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'nvidia/llama-3.1-405b',
    provider: 'nvidia',
    displayName: 'Llama 3.1 405B via nvidia',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 1.969,
    outputPerMillion: 1.969,
    cachedInputPerMillion: 0.4923,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'frontier',
    notes: 'Llama 3.1 405B via nvidia (nvidia/llama-3.1-405b) is a frontier Llama model hosted by nvidia. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.969/M input tokens and $1.969/M output tokens, with cached input at $0.4923/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['nvidia/llama-4-scout', 'nvidia/llama-3.3-70b', 'nvidia/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
];

export const NVIDIA_MODEL_COUNT = NVIDIA_MODELS.length;

export const MODEL_DOC_nvidia_llama_4_maverick = {
  id: 'nvidia/llama-4-maverick',
  summary: 'Llama 4 Maverick via nvidia (nvidia/llama-4-maverick) is a frontier Llama model hosted by nvidia. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.297/M input tokens and $0.935/M output tokens, with cached input at $0.0743/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer nvidia/llama-4-maverick when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001061.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_nvidia_llama_4_scout = {
  id: 'nvidia/llama-4-scout',
  summary: 'Llama 4 Scout via nvidia (nvidia/llama-4-scout) is a workhorse Llama model hosted by nvidia. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.198/M input tokens and $0.649/M output tokens, with cached input at $0.0495/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer nvidia/llama-4-scout when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000721.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_nvidia_llama_3_3_70b = {
  id: 'nvidia/llama-3.3-70b',
  summary: 'Llama 3.3 70B via nvidia (nvidia/llama-3.3-70b) is a workhorse Llama model hosted by nvidia. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.649/M input tokens and $0.869/M output tokens, with cached input at $0.1623/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer nvidia/llama-3.3-70b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001733.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_nvidia_llama_3_1_8b = {
  id: 'nvidia/llama-3.1-8b',
  summary: 'Llama 3.1 8B via nvidia (nvidia/llama-3.1-8b) is a utility Llama model hosted by nvidia. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.055/M input tokens and $0.088/M output tokens, with cached input at $0.0138/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer nvidia/llama-3.1-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000154.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_nvidia_llama_3_1_405b = {
  id: 'nvidia/llama-3.1-405b',
  summary: 'Llama 3.1 405B via nvidia (nvidia/llama-3.1-405b) is a frontier Llama model hosted by nvidia. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.969/M input tokens and $1.969/M output tokens, with cached input at $0.4923/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer nvidia/llama-3.1-405b when quality class is frontier and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.004922.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

