import type { Modality, ModelSpec, Protocol } from "../types";

export const OPENAI_MODELS: ModelSpec[] = [
  {
    id: 'openai/gpt-4o',
    provider: 'openai',
    displayName: 'GPT-4o',
    family: 'gpt-4o',
    release: '2024-05',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 128000,
    maxOutput: 16384,
    inputPerMillion: 2.5,
    outputPerMillion: 10.0,
    cachedInputPerMillion: 1.25,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'GPT-4o (openai/gpt-4o) is a workhorse gpt-4o model hosted by openai. It speaks openai-chat with a 128,000 token context window and a 16,384 token output cap. List price is $2.5/M input tokens and $10.0/M output tokens, with cached input at $1.25/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-05.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openai/gpt-4o-mini', 'openai/gpt-4.1', 'openai/gpt-4.1-mini'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openai/gpt-4o-mini',
    provider: 'openai',
    displayName: 'GPT-4o mini',
    family: 'gpt-4o',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 128000,
    maxOutput: 16384,
    inputPerMillion: 0.15,
    outputPerMillion: 0.6,
    cachedInputPerMillion: 0.075,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'utility',
    notes: 'GPT-4o mini (openai/gpt-4o-mini) is a utility gpt-4o model hosted by openai. It speaks openai-chat with a 128,000 token context window and a 16,384 token output cap. List price is $0.15/M input tokens and $0.6/M output tokens, with cached input at $0.075/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4.1', 'openai/gpt-4.1-mini'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openai/gpt-4.1',
    provider: 'openai',
    displayName: 'GPT-4.1',
    family: 'gpt-4.1',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1047576,
    maxOutput: 32768,
    inputPerMillion: 2.0,
    outputPerMillion: 8.0,
    cachedInputPerMillion: 0.5,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'GPT-4.1 (openai/gpt-4.1) is a workhorse gpt-4.1 model hosted by openai. It speaks openai-chat with a 1,047,576 token context window and a 32,768 token output cap. List price is $2.0/M input tokens and $8.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1-mini'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openai/gpt-4.1-mini',
    provider: 'openai',
    displayName: 'GPT-4.1 mini',
    family: 'gpt-4.1',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1047576,
    maxOutput: 32768,
    inputPerMillion: 0.4,
    outputPerMillion: 1.6,
    cachedInputPerMillion: 0.1,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'GPT-4.1 mini (openai/gpt-4.1-mini) is a workhorse gpt-4.1 model hosted by openai. It speaks openai-chat with a 1,047,576 token context window and a 32,768 token output cap. List price is $0.4/M input tokens and $1.6/M output tokens, with cached input at $0.1/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openai/gpt-4.1-nano',
    provider: 'openai',
    displayName: 'GPT-4.1 nano',
    family: 'gpt-4.1',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1047576,
    maxOutput: 32768,
    inputPerMillion: 0.1,
    outputPerMillion: 0.4,
    cachedInputPerMillion: 0.025,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'GPT-4.1 nano (openai/gpt-4.1-nano) is a utility gpt-4.1 model hosted by openai. It speaks openai-chat with a 1,047,576 token context window and a 32,768 token output cap. List price is $0.1/M input tokens and $0.4/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'openai/gpt-5',
    provider: 'openai',
    displayName: 'GPT-5',
    family: 'gpt-5',
    release: '2025-08',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1047576,
    maxOutput: 65536,
    inputPerMillion: 5.0,
    outputPerMillion: 20.0,
    cachedInputPerMillion: 0.5,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'GPT-5 (openai/gpt-5) is a frontier gpt-5 model hosted by openai. It speaks openai-chat with a 1,047,576 token context window and a 65,536 token output cap. List price is $5.0/M input tokens and $20.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'openai/gpt-5-mini',
    provider: 'openai',
    displayName: 'GPT-5 mini',
    family: 'gpt-5',
    release: '2025-08',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 400000,
    maxOutput: 32768,
    inputPerMillion: 0.4,
    outputPerMillion: 1.6,
    cachedInputPerMillion: 0.1,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'GPT-5 mini (openai/gpt-5-mini) is a workhorse gpt-5 model hosted by openai. It speaks openai-chat with a 400,000 token context window and a 32,768 token output cap. List price is $0.4/M input tokens and $1.6/M output tokens, with cached input at $0.1/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openai/gpt-5-nano',
    provider: 'openai',
    displayName: 'GPT-5 nano',
    family: 'gpt-5',
    release: '2025-08',
    modality: ['text', 'tools', 'json', 'vision', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 400000,
    maxOutput: 16384,
    inputPerMillion: 0.1,
    outputPerMillion: 0.4,
    cachedInputPerMillion: 0.025,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'GPT-5 nano (openai/gpt-5-nano) is a utility gpt-5 model hosted by openai. It speaks openai-chat with a 400,000 token context window and a 16,384 token output cap. List price is $0.1/M input tokens and $0.4/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'openai/gpt-5-pro',
    provider: 'openai',
    displayName: 'GPT-5 pro',
    family: 'gpt-5',
    release: '2025-12',
    modality: ['text', 'tools', 'json', 'vision', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-responses' as Protocol,
    contextWindow: 1047576,
    maxOutput: 65536,
    inputPerMillion: 15.0,
    outputPerMillion: 60.0,
    cachedInputPerMillion: 1.5,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'reasoning',
    notes: 'GPT-5 pro (openai/gpt-5-pro) is a reasoning gpt-5 model hosted by openai. It speaks openai-responses with a 1,047,576 token context window and a 65,536 token output cap. List price is $15.0/M input tokens and $60.0/M output tokens, with cached input at $1.5/M. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-12.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'openai/o3',
    provider: 'openai',
    displayName: 'o3',
    family: 'o-series',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'reasoning'] as Modality[],
    protocol: 'openai-responses' as Protocol,
    contextWindow: 200000,
    maxOutput: 100000,
    inputPerMillion: 10.0,
    outputPerMillion: 40.0,
    cachedInputPerMillion: 2.5,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'reasoning',
    notes: 'o3 (openai/o3) is a reasoning o-series model hosted by openai. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $10.0/M input tokens and $40.0/M output tokens, with cached input at $2.5/M. Modalities: text, tools, json, reasoning. Tokenizer: o200k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'openai/o3-mini',
    provider: 'openai',
    displayName: 'o3-mini',
    family: 'o-series',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'vision', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-responses' as Protocol,
    contextWindow: 200000,
    maxOutput: 100000,
    inputPerMillion: 1.1,
    outputPerMillion: 4.4,
    cachedInputPerMillion: 0.55,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'reasoning',
    notes: 'o3-mini (openai/o3-mini) is a reasoning o-series model hosted by openai. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $1.1/M input tokens and $4.4/M output tokens, with cached input at $0.55/M. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'openai/o4-mini',
    provider: 'openai',
    displayName: 'o4-mini',
    family: 'o-series',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'vision', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-responses' as Protocol,
    contextWindow: 200000,
    maxOutput: 100000,
    inputPerMillion: 1.1,
    outputPerMillion: 4.4,
    cachedInputPerMillion: 0.275,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'reasoning',
    notes: 'o4-mini (openai/o4-mini) is a reasoning o-series model hosted by openai. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $1.1/M input tokens and $4.4/M output tokens, with cached input at $0.275/M. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'openai/o1',
    provider: 'openai',
    displayName: 'o1',
    family: 'o-series',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'reasoning'] as Modality[],
    protocol: 'openai-responses' as Protocol,
    contextWindow: 200000,
    maxOutput: 100000,
    inputPerMillion: 15.0,
    outputPerMillion: 60.0,
    cachedInputPerMillion: 7.5,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'reasoning',
    notes: 'o1 (openai/o1) is a reasoning o-series model hosted by openai. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $15.0/M input tokens and $60.0/M output tokens, with cached input at $7.5/M. Modalities: text, tools, json, reasoning. Tokenizer: o200k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'openai/o1-mini',
    provider: 'openai',
    displayName: 'o1-mini',
    family: 'o-series',
    release: '2024-09',
    modality: ['text', 'tools', 'json', 'vision', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-responses' as Protocol,
    contextWindow: 128000,
    maxOutput: 65536,
    inputPerMillion: 3.0,
    outputPerMillion: 12.0,
    cachedInputPerMillion: undefined,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'reasoning',
    notes: 'o1-mini (openai/o1-mini) is a reasoning o-series model hosted by openai. It speaks openai-responses with a 128,000 token context window and a 65,536 token output cap. List price is $3.0/M input tokens and $12.0/M output tokens. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'openai/text-embedding-3-small',
    provider: 'openai',
    displayName: 'Embedding 3 small',
    family: 'embeddings',
    release: '2024-01',
    modality: ['embed'] as Modality[],
    protocol: 'openai-embeddings' as Protocol,
    contextWindow: 8191,
    maxOutput: 0,
    inputPerMillion: 0.02,
    outputPerMillion: 0.0,
    cachedInputPerMillion: undefined,
    tokenizer: 'cl100k_base',
    streaming: false,
    tools: false,
    jsonMode: false,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Embedding 3 small (openai/text-embedding-3-small) is a utility embeddings model hosted by openai. It speaks openai-embeddings with a 8,191 token context window and a 0 token output cap. List price is $0.02/M input tokens and $0.0/M output tokens. Modalities: embed. Tokenizer: cl100k_base. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-01.',
    useCases: ['semantic search', 'cluster labeling', 'cache keys', 'dedup'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'openai/text-embedding-3-large',
    provider: 'openai',
    displayName: 'Embedding 3 large',
    family: 'embeddings',
    release: '2024-01',
    modality: ['embed'] as Modality[],
    protocol: 'openai-embeddings' as Protocol,
    contextWindow: 8191,
    maxOutput: 0,
    inputPerMillion: 0.13,
    outputPerMillion: 0.0,
    cachedInputPerMillion: undefined,
    tokenizer: 'cl100k_base',
    streaming: false,
    tools: false,
    jsonMode: false,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Embedding 3 large (openai/text-embedding-3-large) is a workhorse embeddings model hosted by openai. It speaks openai-embeddings with a 8,191 token context window and a 0 token output cap. List price is $0.13/M input tokens and $0.0/M output tokens. Modalities: embed. Tokenizer: cl100k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-01.',
    useCases: ['semantic search', 'cluster labeling', 'cache keys', 'dedup'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openai/gpt-4o-transcribe',
    provider: 'openai',
    displayName: 'GPT-4o Transcribe',
    family: 'audio',
    release: '2025-03',
    modality: ['audio', 'text'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 16000,
    maxOutput: 4096,
    inputPerMillion: 2.5,
    outputPerMillion: 10.0,
    cachedInputPerMillion: undefined,
    tokenizer: 'o200k_base',
    streaming: true,
    tools: false,
    jsonMode: false,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'GPT-4o Transcribe (openai/gpt-4o-transcribe) is a workhorse audio model hosted by openai. It speaks openai-chat with a 16,000 token context window and a 4,096 token output cap. List price is $2.5/M input tokens and $10.0/M output tokens. Modalities: audio, text. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 1.6,
  },
  {
    id: 'openai/gpt-image-1',
    provider: 'openai',
    displayName: 'GPT Image 1',
    family: 'image',
    release: '2025-04',
    modality: ['image'] as Modality[],
    protocol: 'openai-images' as Protocol,
    contextWindow: 32000,
    maxOutput: 0,
    inputPerMillion: 5.0,
    outputPerMillion: 0.0,
    cachedInputPerMillion: undefined,
    tokenizer: 'cl100k_base',
    streaming: false,
    tools: false,
    jsonMode: false,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'workhorse',
    notes: 'GPT Image 1 (openai/gpt-image-1) is a workhorse image model hosted by openai. It speaks openai-images with a 32,000 token context window and a 0 token output cap. List price is $5.0/M input tokens and $0.0/M output tokens. Modalities: image. Tokenizer: cl100k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4.1'],
    carbonGPerMTok: 3.4,
  },
];

export const OPENAI_MODEL_COUNT = OPENAI_MODELS.length;

export const MODEL_DOC_openai_gpt_4o = {
  id: 'openai/gpt-4o',
  summary: 'GPT-4o (openai/gpt-4o) is a workhorse gpt-4o model hosted by openai. It speaks openai-chat with a 128,000 token context window and a 16,384 token output cap. List price is $2.5/M input tokens and $10.0/M output tokens, with cached input at $1.25/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-05.',
  routingHints: [
    'Prefer openai/gpt-4o when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.01.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_gpt_4o_mini = {
  id: 'openai/gpt-4o-mini',
  summary: 'GPT-4o mini (openai/gpt-4o-mini) is a utility gpt-4o model hosted by openai. It speaks openai-chat with a 128,000 token context window and a 16,384 token output cap. List price is $0.15/M input tokens and $0.6/M output tokens, with cached input at $0.075/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer openai/gpt-4o-mini when quality class is utility and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0006.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_openai_gpt_4_1 = {
  id: 'openai/gpt-4.1',
  summary: 'GPT-4.1 (openai/gpt-4.1) is a workhorse gpt-4.1 model hosted by openai. It speaks openai-chat with a 1,047,576 token context window and a 32,768 token output cap. List price is $2.0/M input tokens and $8.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer openai/gpt-4.1 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.008.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_gpt_4_1_mini = {
  id: 'openai/gpt-4.1-mini',
  summary: 'GPT-4.1 mini (openai/gpt-4.1-mini) is a workhorse gpt-4.1 model hosted by openai. It speaks openai-chat with a 1,047,576 token context window and a 32,768 token output cap. List price is $0.4/M input tokens and $1.6/M output tokens, with cached input at $0.1/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer openai/gpt-4.1-mini when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0016.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_gpt_4_1_nano = {
  id: 'openai/gpt-4.1-nano',
  summary: 'GPT-4.1 nano (openai/gpt-4.1-nano) is a utility gpt-4.1 model hosted by openai. It speaks openai-chat with a 1,047,576 token context window and a 32,768 token output cap. List price is $0.1/M input tokens and $0.4/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer openai/gpt-4.1-nano when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0004.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_openai_gpt_5 = {
  id: 'openai/gpt-5',
  summary: 'GPT-5 (openai/gpt-5) is a frontier gpt-5 model hosted by openai. It speaks openai-chat with a 1,047,576 token context window and a 65,536 token output cap. List price is $5.0/M input tokens and $20.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
  routingHints: [
    'Prefer openai/gpt-5 when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.02.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_gpt_5_mini = {
  id: 'openai/gpt-5-mini',
  summary: 'GPT-5 mini (openai/gpt-5-mini) is a workhorse gpt-5 model hosted by openai. It speaks openai-chat with a 400,000 token context window and a 32,768 token output cap. List price is $0.4/M input tokens and $1.6/M output tokens, with cached input at $0.1/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
  routingHints: [
    'Prefer openai/gpt-5-mini when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0016.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_gpt_5_nano = {
  id: 'openai/gpt-5-nano',
  summary: 'GPT-5 nano (openai/gpt-5-nano) is a utility gpt-5 model hosted by openai. It speaks openai-chat with a 400,000 token context window and a 16,384 token output cap. List price is $0.1/M input tokens and $0.4/M output tokens, with cached input at $0.025/M. Modalities: text, tools, json, vision, code. Tokenizer: o200k_base. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-08.',
  routingHints: [
    'Prefer openai/gpt-5-nano when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0004.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_openai_gpt_5_pro = {
  id: 'openai/gpt-5-pro',
  summary: 'GPT-5 pro (openai/gpt-5-pro) is a reasoning gpt-5 model hosted by openai. It speaks openai-responses with a 1,047,576 token context window and a 65,536 token output cap. List price is $15.0/M input tokens and $60.0/M output tokens, with cached input at $1.5/M. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-12.',
  routingHints: [
    'Prefer openai/gpt-5-pro when quality class is reasoning and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.06.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-responses; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_o3 = {
  id: 'openai/o3',
  summary: 'o3 (openai/o3) is a reasoning o-series model hosted by openai. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $10.0/M input tokens and $40.0/M output tokens, with cached input at $2.5/M. Modalities: text, tools, json, reasoning. Tokenizer: o200k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer openai/o3 when quality class is reasoning and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.04.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-responses; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_o3_mini = {
  id: 'openai/o3-mini',
  summary: 'o3-mini (openai/o3-mini) is a reasoning o-series model hosted by openai. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $1.1/M input tokens and $4.4/M output tokens, with cached input at $0.55/M. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer openai/o3-mini when quality class is reasoning and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0044.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-responses; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_o4_mini = {
  id: 'openai/o4-mini',
  summary: 'o4-mini (openai/o4-mini) is a reasoning o-series model hosted by openai. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $1.1/M input tokens and $4.4/M output tokens, with cached input at $0.275/M. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer openai/o4-mini when quality class is reasoning and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0044.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-responses; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_o1 = {
  id: 'openai/o1',
  summary: 'o1 (openai/o1) is a reasoning o-series model hosted by openai. It speaks openai-responses with a 200,000 token context window and a 100,000 token output cap. List price is $15.0/M input tokens and $60.0/M output tokens, with cached input at $7.5/M. Modalities: text, tools, json, reasoning. Tokenizer: o200k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer openai/o1 when quality class is reasoning and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.06.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-responses; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_o1_mini = {
  id: 'openai/o1-mini',
  summary: 'o1-mini (openai/o1-mini) is a reasoning o-series model hosted by openai. It speaks openai-responses with a 128,000 token context window and a 65,536 token output cap. List price is $3.0/M input tokens and $12.0/M output tokens. Modalities: text, tools, json, vision, code, reasoning. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
  routingHints: [
    'Prefer openai/o1-mini when quality class is reasoning and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.012.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-responses; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_text_embedding_3_small = {
  id: 'openai/text-embedding-3-small',
  summary: 'Embedding 3 small (openai/text-embedding-3-small) is a utility embeddings model hosted by openai. It speaks openai-embeddings with a 8,191 token context window and a 0 token output cap. List price is $0.02/M input tokens and $0.0/M output tokens. Modalities: embed. Tokenizer: cl100k_base. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-01.',
  routingHints: [
    'Prefer openai/text-embedding-3-small when quality class is utility and speed class is instant.',
    'Cap max_tokens at 0 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $4e-05.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-embeddings; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_openai_text_embedding_3_large = {
  id: 'openai/text-embedding-3-large',
  summary: 'Embedding 3 large (openai/text-embedding-3-large) is a workhorse embeddings model hosted by openai. It speaks openai-embeddings with a 8,191 token context window and a 0 token output cap. List price is $0.13/M input tokens and $0.0/M output tokens. Modalities: embed. Tokenizer: cl100k_base. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-01.',
  routingHints: [
    'Prefer openai/text-embedding-3-large when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 0 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00026.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-embeddings; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_gpt_4o_transcribe = {
  id: 'openai/gpt-4o-transcribe',
  summary: 'GPT-4o Transcribe (openai/gpt-4o-transcribe) is a workhorse audio model hosted by openai. It speaks openai-chat with a 16,000 token context window and a 4,096 token output cap. List price is $2.5/M input tokens and $10.0/M output tokens. Modalities: audio, text. Tokenizer: o200k_base. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
  routingHints: [
    'Prefer openai/gpt-4o-transcribe when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.01.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openai_gpt_image_1 = {
  id: 'openai/gpt-image-1',
  summary: 'GPT Image 1 (openai/gpt-image-1) is a workhorse image model hosted by openai. It speaks openai-images with a 32,000 token context window and a 0 token output cap. List price is $5.0/M input tokens and $0.0/M output tokens. Modalities: image. Tokenizer: cl100k_base. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer openai/gpt-image-1 when quality class is workhorse and speed class is slow.',
    'Cap max_tokens at 0 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.01.',
    'Carbon intensity about 3.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-images; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

