import type { Modality, ModelSpec, Protocol } from "../types";

export const OPENROUTER_MODELS: ModelSpec[] = [
  {
    id: 'openrouter/llama-4-maverick',
    provider: 'openrouter',
    displayName: 'Llama 4 Maverick via openrouter',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.2835,
    outputPerMillion: 0.8925,
    cachedInputPerMillion: 0.0709,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Llama 4 Maverick via openrouter (openrouter/llama-4-maverick) is a frontier Llama model hosted by openrouter. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.2835/M input tokens and $0.8925/M output tokens, with cached input at $0.0709/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'openrouter/llama-4-scout',
    provider: 'openrouter',
    displayName: 'Llama 4 Scout via openrouter',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.189,
    outputPerMillion: 0.6195,
    cachedInputPerMillion: 0.0473,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 4 Scout via openrouter (openrouter/llama-4-scout) is a workhorse Llama model hosted by openrouter. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.189/M input tokens and $0.6195/M output tokens, with cached input at $0.0473/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b', 'openrouter/mistral-small-3.1'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openrouter/llama-3.3-70b',
    provider: 'openrouter',
    displayName: 'Llama 3.3 70B via openrouter',
    family: 'Llama',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.6195,
    outputPerMillion: 0.8295,
    cachedInputPerMillion: 0.1549,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Llama 3.3 70B via openrouter (openrouter/llama-3.3-70b) is a workhorse Llama model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.6195/M input tokens and $0.8295/M output tokens, with cached input at $0.1549/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.1-8b', 'openrouter/mistral-small-3.1'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openrouter/llama-3.1-8b',
    provider: 'openrouter',
    displayName: 'Llama 3.1 8B via openrouter',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.0525,
    outputPerMillion: 0.084,
    cachedInputPerMillion: 0.0131,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Llama 3.1 8B via openrouter (openrouter/llama-3.1-8b) is a utility Llama model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.0525/M input tokens and $0.084/M output tokens, with cached input at $0.0131/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/mistral-small-3.1'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'openrouter/llama-3.1-405b',
    provider: 'openrouter',
    displayName: 'Llama 3.1 405B via openrouter',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 1.8795,
    outputPerMillion: 1.8795,
    cachedInputPerMillion: 0.4699,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'frontier',
    notes: 'Llama 3.1 405B via openrouter (openrouter/llama-3.1-405b) is a frontier Llama model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.8795/M input tokens and $1.8795/M output tokens, with cached input at $0.4699/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'openrouter/mistral-large-2411',
    provider: 'openrouter',
    displayName: 'Mistral Large 2411 via openrouter',
    family: 'Mistral',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 2.1,
    outputPerMillion: 6.3,
    cachedInputPerMillion: 0.525,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'Mistral Large 2411 via openrouter (openrouter/mistral-large-2411) is a frontier Mistral model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.1/M input tokens and $6.3/M output tokens, with cached input at $0.525/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'openrouter/mistral-small-3.1',
    provider: 'openrouter',
    displayName: 'Mistral Small 3.1 via openrouter',
    family: 'Mistral',
    release: '2025-03',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.105,
    outputPerMillion: 0.315,
    cachedInputPerMillion: 0.0263,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Mistral Small 3.1 via openrouter (openrouter/mistral-small-3.1) is a workhorse Mistral model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.105/M input tokens and $0.315/M output tokens, with cached input at $0.0263/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openrouter/codestral-2501',
    provider: 'openrouter',
    displayName: 'Codestral 2501 via openrouter',
    family: 'Mistral',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 262144,
    maxOutput: 16384,
    inputPerMillion: 0.315,
    outputPerMillion: 0.945,
    cachedInputPerMillion: 0.0788,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Codestral 2501 via openrouter (openrouter/codestral-2501) is a workhorse Mistral model hosted by openrouter. It speaks openai-chat with a 262,144 token context window and a 16,384 token output cap. List price is $0.315/M input tokens and $0.945/M output tokens, with cached input at $0.0788/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openrouter/pixtral-large',
    provider: 'openrouter',
    displayName: 'Pixtral Large via openrouter',
    family: 'Mistral',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 2.1,
    outputPerMillion: 6.3,
    cachedInputPerMillion: 0.525,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'Pixtral Large via openrouter (openrouter/pixtral-large) is a workhorse Mistral model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.1/M input tokens and $6.3/M output tokens, with cached input at $0.525/M. Modalities: text, tools, json, code, vision. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 1.6,
  },
  {
    id: 'openrouter/ministral-8b',
    provider: 'openrouter',
    displayName: 'Ministral 8B via openrouter',
    family: 'Mistral',
    release: '2024-10',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.105,
    outputPerMillion: 0.105,
    cachedInputPerMillion: 0.0263,
    tokenizer: 'mistral',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Ministral 8B via openrouter (openrouter/ministral-8b) is a utility Mistral model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.105/M input tokens and $0.105/M output tokens, with cached input at $0.0263/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-10.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'openrouter/deepseek-v3.2',
    provider: 'openrouter',
    displayName: 'DeepSeek V3.2 via openrouter',
    family: 'DeepSeek',
    release: '2025-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 163840,
    maxOutput: 8192,
    inputPerMillion: 0.2835,
    outputPerMillion: 1.155,
    cachedInputPerMillion: 0.0709,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'DeepSeek V3.2 via openrouter (openrouter/deepseek-v3.2) is a frontier DeepSeek model hosted by openrouter. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.2835/M input tokens and $1.155/M output tokens, with cached input at $0.0709/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-12.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'openrouter/deepseek-v3',
    provider: 'openrouter',
    displayName: 'DeepSeek V3 via openrouter',
    family: 'DeepSeek',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 163840,
    maxOutput: 8192,
    inputPerMillion: 0.2835,
    outputPerMillion: 1.155,
    cachedInputPerMillion: 0.0709,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'DeepSeek V3 via openrouter (openrouter/deepseek-v3) is a frontier DeepSeek model hosted by openrouter. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.2835/M input tokens and $1.155/M output tokens, with cached input at $0.0709/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'openrouter/deepseek-r1',
    provider: 'openrouter',
    displayName: 'DeepSeek R1 via openrouter',
    family: 'DeepSeek',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 163840,
    maxOutput: 8192,
    inputPerMillion: 0.5775,
    outputPerMillion: 2.2995,
    cachedInputPerMillion: 0.1444,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'reasoning',
    notes: 'DeepSeek R1 via openrouter (openrouter/deepseek-r1) is a reasoning DeepSeek model hosted by openrouter. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.5775/M input tokens and $2.2995/M output tokens, with cached input at $0.1444/M. Modalities: text, tools, json, code, reasoning. Tokenizer: deepseek. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 4.76,
  },
  {
    id: 'openrouter/deepseek-coder-v2',
    provider: 'openrouter',
    displayName: 'DeepSeek Coder V2 via openrouter',
    family: 'DeepSeek',
    release: '2024-06',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.147,
    outputPerMillion: 0.294,
    cachedInputPerMillion: 0.0368,
    tokenizer: 'deepseek',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'DeepSeek Coder V2 via openrouter (openrouter/deepseek-coder-v2) is a workhorse DeepSeek model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.147/M input tokens and $0.294/M output tokens, with cached input at $0.0368/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-06.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openrouter/qwen3-235b',
    provider: 'openrouter',
    displayName: 'Qwen3 235B via openrouter',
    family: 'Qwen',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.21,
    outputPerMillion: 0.63,
    cachedInputPerMillion: 0.0525,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'frontier',
    notes: 'Qwen3 235B via openrouter (openrouter/qwen3-235b) is a frontier Qwen model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.21/M input tokens and $0.63/M output tokens, with cached input at $0.0525/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 2.24,
  },
  {
    id: 'openrouter/qwen3-32b',
    provider: 'openrouter',
    displayName: 'Qwen3 32B via openrouter',
    family: 'Qwen',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.105,
    outputPerMillion: 0.315,
    cachedInputPerMillion: 0.0263,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen3 32B via openrouter (openrouter/qwen3-32b) is a workhorse Qwen model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.105/M input tokens and $0.315/M output tokens, with cached input at $0.0263/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openrouter/qwen2.5-72b',
    provider: 'openrouter',
    displayName: 'Qwen2.5 72B via openrouter',
    family: 'Qwen',
    release: '2024-09',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.126,
    outputPerMillion: 0.4095,
    cachedInputPerMillion: 0.0315,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen2.5 72B via openrouter (openrouter/qwen2.5-72b) is a workhorse Qwen model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.126/M input tokens and $0.4095/M output tokens, with cached input at $0.0315/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openrouter/qwen2.5-coder-32b',
    provider: 'openrouter',
    displayName: 'Qwen2.5 Coder 32B via openrouter',
    family: 'Qwen',
    release: '2024-11',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.084,
    outputPerMillion: 0.189,
    cachedInputPerMillion: 0.021,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Qwen2.5 Coder 32B via openrouter (openrouter/qwen2.5-coder-32b) is a workhorse Qwen model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.084/M input tokens and $0.189/M output tokens, with cached input at $0.021/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'openrouter/qwen-vl-max',
    provider: 'openrouter',
    displayName: 'Qwen VL Max via openrouter',
    family: 'Qwen',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 32768,
    maxOutput: 8192,
    inputPerMillion: 0.84,
    outputPerMillion: 3.36,
    cachedInputPerMillion: 0.21,
    tokenizer: 'qwen',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'Qwen VL Max via openrouter (openrouter/qwen-vl-max) is a workhorse Qwen model hosted by openrouter. It speaks openai-chat with a 32,768 token context window and a 8,192 token output cap. List price is $0.84/M input tokens and $3.36/M output tokens, with cached input at $0.21/M. Modalities: text, tools, json, code, vision. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 1.6,
  },
  {
    id: 'openrouter/kimi-k2.5',
    provider: 'openrouter',
    displayName: 'Kimi K2.5 via openrouter',
    family: 'Kimi',
    release: '2026-01',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 262144,
    maxOutput: 16384,
    inputPerMillion: 0.63,
    outputPerMillion: 3.15,
    cachedInputPerMillion: 0.1575,
    tokenizer: 'kimi',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Kimi K2.5 via openrouter (openrouter/kimi-k2.5) is a frontier Kimi model hosted by openrouter. It speaks openai-chat with a 262,144 token context window and a 16,384 token output cap. List price is $0.63/M input tokens and $3.15/M output tokens, with cached input at $0.1575/M. Modalities: text, tools, json, code. Tokenizer: kimi. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2026-01.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'openrouter/kimi-k2',
    provider: 'openrouter',
    displayName: 'Kimi K2 via openrouter',
    family: 'Kimi',
    release: '2025-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.63,
    outputPerMillion: 2.625,
    cachedInputPerMillion: 0.1575,
    tokenizer: 'kimi',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Kimi K2 via openrouter (openrouter/kimi-k2) is a frontier Kimi model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.63/M input tokens and $2.625/M output tokens, with cached input at $0.1575/M. Modalities: text, tools, json, code. Tokenizer: kimi. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'openrouter/glm-4.5',
    provider: 'openrouter',
    displayName: 'GLM-4.5 via openrouter',
    family: 'GLM',
    release: '2025-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.63,
    outputPerMillion: 2.31,
    cachedInputPerMillion: 0.1575,
    tokenizer: 'glm',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'GLM-4.5 via openrouter (openrouter/glm-4.5) is a frontier GLM model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.63/M input tokens and $2.31/M output tokens, with cached input at $0.1575/M. Modalities: text, tools, json, code. Tokenizer: glm. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'openrouter/glm-4.6',
    provider: 'openrouter',
    displayName: 'GLM-4.6 via openrouter',
    family: 'GLM',
    release: '2025-11',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 198000,
    maxOutput: 16384,
    inputPerMillion: 0.525,
    outputPerMillion: 1.89,
    cachedInputPerMillion: 0.1313,
    tokenizer: 'glm',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'GLM-4.6 via openrouter (openrouter/glm-4.6) is a frontier GLM model hosted by openrouter. It speaks openai-chat with a 198,000 token context window and a 16,384 token output cap. List price is $0.525/M input tokens and $1.89/M output tokens, with cached input at $0.1313/M. Modalities: text, tools, json, code. Tokenizer: glm. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-11.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'openrouter/glm-4.5-air',
    provider: 'openrouter',
    displayName: 'GLM-4.5 Air via openrouter',
    family: 'GLM',
    release: '2025-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.1365,
    outputPerMillion: 0.8925,
    cachedInputPerMillion: 0.0341,
    tokenizer: 'glm',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'workhorse',
    notes: 'GLM-4.5 Air via openrouter (openrouter/glm-4.5-air) is a workhorse GLM model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.1365/M input tokens and $0.8925/M output tokens, with cached input at $0.0341/M. Modalities: text, tools, json, code. Tokenizer: glm. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['openrouter/llama-4-scout', 'openrouter/llama-3.3-70b', 'openrouter/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
];

export const OPENROUTER_MODEL_COUNT = OPENROUTER_MODELS.length;

export const MODEL_DOC_openrouter_llama_4_maverick = {
  id: 'openrouter/llama-4-maverick',
  summary: 'Llama 4 Maverick via openrouter (openrouter/llama-4-maverick) is a frontier Llama model hosted by openrouter. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.2835/M input tokens and $0.8925/M output tokens, with cached input at $0.0709/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer openrouter/llama-4-maverick when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001013.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_llama_4_scout = {
  id: 'openrouter/llama-4-scout',
  summary: 'Llama 4 Scout via openrouter (openrouter/llama-4-scout) is a workhorse Llama model hosted by openrouter. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.189/M input tokens and $0.6195/M output tokens, with cached input at $0.0473/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer openrouter/llama-4-scout when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000688.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_llama_3_3_70b = {
  id: 'openrouter/llama-3.3-70b',
  summary: 'Llama 3.3 70B via openrouter (openrouter/llama-3.3-70b) is a workhorse Llama model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.6195/M input tokens and $0.8295/M output tokens, with cached input at $0.1549/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer openrouter/llama-3.3-70b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001654.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_llama_3_1_8b = {
  id: 'openrouter/llama-3.1-8b',
  summary: 'Llama 3.1 8B via openrouter (openrouter/llama-3.1-8b) is a utility Llama model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.0525/M input tokens and $0.084/M output tokens, with cached input at $0.0131/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer openrouter/llama-3.1-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000147.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_openrouter_llama_3_1_405b = {
  id: 'openrouter/llama-3.1-405b',
  summary: 'Llama 3.1 405B via openrouter (openrouter/llama-3.1-405b) is a frontier Llama model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.8795/M input tokens and $1.8795/M output tokens, with cached input at $0.4699/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer openrouter/llama-3.1-405b when quality class is frontier and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.004699.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_mistral_large_2411 = {
  id: 'openrouter/mistral-large-2411',
  summary: 'Mistral Large 2411 via openrouter (openrouter/mistral-large-2411) is a frontier Mistral model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.1/M input tokens and $6.3/M output tokens, with cached input at $0.525/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer openrouter/mistral-large-2411 when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00735.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_mistral_small_3_1 = {
  id: 'openrouter/mistral-small-3.1',
  summary: 'Mistral Small 3.1 via openrouter (openrouter/mistral-small-3.1) is a workhorse Mistral model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.105/M input tokens and $0.315/M output tokens, with cached input at $0.0263/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-03.',
  routingHints: [
    'Prefer openrouter/mistral-small-3.1 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000367.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_codestral_2501 = {
  id: 'openrouter/codestral-2501',
  summary: 'Codestral 2501 via openrouter (openrouter/codestral-2501) is a workhorse Mistral model hosted by openrouter. It speaks openai-chat with a 262,144 token context window and a 16,384 token output cap. List price is $0.315/M input tokens and $0.945/M output tokens, with cached input at $0.0788/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer openrouter/codestral-2501 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001102.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_pixtral_large = {
  id: 'openrouter/pixtral-large',
  summary: 'Pixtral Large via openrouter (openrouter/pixtral-large) is a workhorse Mistral model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $2.1/M input tokens and $6.3/M output tokens, with cached input at $0.525/M. Modalities: text, tools, json, code, vision. Tokenizer: mistral. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer openrouter/pixtral-large when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00735.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_ministral_8b = {
  id: 'openrouter/ministral-8b',
  summary: 'Ministral 8B via openrouter (openrouter/ministral-8b) is a utility Mistral model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.105/M input tokens and $0.105/M output tokens, with cached input at $0.0263/M. Modalities: text, tools, json, code. Tokenizer: mistral. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-10.',
  routingHints: [
    'Prefer openrouter/ministral-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000262.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_openrouter_deepseek_v3_2 = {
  id: 'openrouter/deepseek-v3.2',
  summary: 'DeepSeek V3.2 via openrouter (openrouter/deepseek-v3.2) is a frontier DeepSeek model hosted by openrouter. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.2835/M input tokens and $1.155/M output tokens, with cached input at $0.0709/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-12.',
  routingHints: [
    'Prefer openrouter/deepseek-v3.2 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001144.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_deepseek_v3 = {
  id: 'openrouter/deepseek-v3',
  summary: 'DeepSeek V3 via openrouter (openrouter/deepseek-v3) is a frontier DeepSeek model hosted by openrouter. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.2835/M input tokens and $1.155/M output tokens, with cached input at $0.0709/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer openrouter/deepseek-v3 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001144.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_deepseek_r1 = {
  id: 'openrouter/deepseek-r1',
  summary: 'DeepSeek R1 via openrouter (openrouter/deepseek-r1) is a reasoning DeepSeek model hosted by openrouter. It speaks openai-chat with a 163,840 token context window and a 8,192 token output cap. List price is $0.5775/M input tokens and $2.2995/M output tokens, with cached input at $0.1444/M. Modalities: text, tools, json, code, reasoning. Tokenizer: deepseek. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer openrouter/deepseek-r1 when quality class is reasoning and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.002305.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_deepseek_coder_v2 = {
  id: 'openrouter/deepseek-coder-v2',
  summary: 'DeepSeek Coder V2 via openrouter (openrouter/deepseek-coder-v2) is a workhorse DeepSeek model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.147/M input tokens and $0.294/M output tokens, with cached input at $0.0368/M. Modalities: text, tools, json, code. Tokenizer: deepseek. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-06.',
  routingHints: [
    'Prefer openrouter/deepseek-coder-v2 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000441.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_qwen3_235b = {
  id: 'openrouter/qwen3-235b',
  summary: 'Qwen3 235B via openrouter (openrouter/qwen3-235b) is a frontier Qwen model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.21/M input tokens and $0.63/M output tokens, with cached input at $0.0525/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer openrouter/qwen3-235b when quality class is frontier and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000735.',
    'Carbon intensity about 2.24 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_qwen3_32b = {
  id: 'openrouter/qwen3-32b',
  summary: 'Qwen3 32B via openrouter (openrouter/qwen3-32b) is a workhorse Qwen model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.105/M input tokens and $0.315/M output tokens, with cached input at $0.0263/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer openrouter/qwen3-32b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000367.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_qwen2_5_72b = {
  id: 'openrouter/qwen2.5-72b',
  summary: 'Qwen2.5 72B via openrouter (openrouter/qwen2.5-72b) is a workhorse Qwen model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.126/M input tokens and $0.4095/M output tokens, with cached input at $0.0315/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-09.',
  routingHints: [
    'Prefer openrouter/qwen2.5-72b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000457.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_qwen2_5_coder_32b = {
  id: 'openrouter/qwen2.5-coder-32b',
  summary: 'Qwen2.5 Coder 32B via openrouter (openrouter/qwen2.5-coder-32b) is a workhorse Qwen model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.084/M input tokens and $0.189/M output tokens, with cached input at $0.021/M. Modalities: text, tools, json, code. Tokenizer: qwen. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-11.',
  routingHints: [
    'Prefer openrouter/qwen2.5-coder-32b when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000262.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_qwen_vl_max = {
  id: 'openrouter/qwen-vl-max',
  summary: 'Qwen VL Max via openrouter (openrouter/qwen-vl-max) is a workhorse Qwen model hosted by openrouter. It speaks openai-chat with a 32,768 token context window and a 8,192 token output cap. List price is $0.84/M input tokens and $3.36/M output tokens, with cached input at $0.21/M. Modalities: text, tools, json, code, vision. Tokenizer: qwen. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer openrouter/qwen-vl-max when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00336.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_kimi_k2_5 = {
  id: 'openrouter/kimi-k2.5',
  summary: 'Kimi K2.5 via openrouter (openrouter/kimi-k2.5) is a frontier Kimi model hosted by openrouter. It speaks openai-chat with a 262,144 token context window and a 16,384 token output cap. List price is $0.63/M input tokens and $3.15/M output tokens, with cached input at $0.1575/M. Modalities: text, tools, json, code. Tokenizer: kimi. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2026-01.',
  routingHints: [
    'Prefer openrouter/kimi-k2.5 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.002835.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_kimi_k2 = {
  id: 'openrouter/kimi-k2',
  summary: 'Kimi K2 via openrouter (openrouter/kimi-k2) is a frontier Kimi model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.63/M input tokens and $2.625/M output tokens, with cached input at $0.1575/M. Modalities: text, tools, json, code. Tokenizer: kimi. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
  routingHints: [
    'Prefer openrouter/kimi-k2 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.002573.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_glm_4_5 = {
  id: 'openrouter/glm-4.5',
  summary: 'GLM-4.5 via openrouter (openrouter/glm-4.5) is a frontier GLM model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.63/M input tokens and $2.31/M output tokens, with cached input at $0.1575/M. Modalities: text, tools, json, code. Tokenizer: glm. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
  routingHints: [
    'Prefer openrouter/glm-4.5 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.002415.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_glm_4_6 = {
  id: 'openrouter/glm-4.6',
  summary: 'GLM-4.6 via openrouter (openrouter/glm-4.6) is a frontier GLM model hosted by openrouter. It speaks openai-chat with a 198,000 token context window and a 16,384 token output cap. List price is $0.525/M input tokens and $1.89/M output tokens, with cached input at $0.1313/M. Modalities: text, tools, json, code. Tokenizer: glm. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-11.',
  routingHints: [
    'Prefer openrouter/glm-4.6 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001995.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_openrouter_glm_4_5_air = {
  id: 'openrouter/glm-4.5-air',
  summary: 'GLM-4.5 Air via openrouter (openrouter/glm-4.5-air) is a workhorse GLM model hosted by openrouter. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.1365/M input tokens and $0.8925/M output tokens, with cached input at $0.0341/M. Modalities: text, tools, json, code. Tokenizer: glm. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
  routingHints: [
    'Prefer openrouter/glm-4.5-air when quality class is workhorse and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000719.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

