import type { Modality, ModelSpec, Protocol } from "../types";

export const PERPLEXITY_MODELS: ModelSpec[] = [
  {
    id: 'perplexity/sonar-pro',
    provider: 'perplexity',
    displayName: 'Sonar Pro via perplexity',
    family: 'Sonar',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 200000,
    maxOutput: 8192,
    inputPerMillion: 3.0,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.75,
    tokenizer: 'sonar',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'Sonar Pro via perplexity (perplexity/sonar-pro) is a workhorse Sonar model hosted by perplexity. It speaks openai-chat with a 200,000 token context window and a 8,192 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.75/M. Modalities: text, tools, json, code. Tokenizer: sonar. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['perplexity/sonar'],
    carbonGPerMTok: 1.6,
  },
  {
    id: 'perplexity/sonar',
    provider: 'perplexity',
    displayName: 'Sonar via perplexity',
    family: 'Sonar',
    release: '2025-01',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 127000,
    maxOutput: 8192,
    inputPerMillion: 1.0,
    outputPerMillion: 1.0,
    cachedInputPerMillion: 0.25,
    tokenizer: 'sonar',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'utility',
    notes: 'Sonar via perplexity (perplexity/sonar) is a utility Sonar model hosted by perplexity. It speaks openai-chat with a 127,000 token context window and a 8,192 token output cap. List price is $1.0/M input tokens and $1.0/M output tokens, with cached input at $0.25/M. Modalities: text, tools, json, code. Tokenizer: sonar. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['perplexity/sonar-pro'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'perplexity/sonar-reasoning-pro',
    provider: 'perplexity',
    displayName: 'Sonar Reasoning Pro via perplexity',
    family: 'Sonar',
    release: '2025-02',
    modality: ['text', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 127000,
    maxOutput: 8192,
    inputPerMillion: 2.0,
    outputPerMillion: 8.0,
    cachedInputPerMillion: 0.5,
    tokenizer: 'sonar',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'slow',
    qualityClass: 'reasoning',
    notes: 'Sonar Reasoning Pro via perplexity (perplexity/sonar-reasoning-pro) is a reasoning Sonar model hosted by perplexity. It speaks openai-chat with a 127,000 token context window and a 8,192 token output cap. List price is $2.0/M input tokens and $8.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, code, reasoning. Tokenizer: sonar. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-02.',
    useCases: ['math', 'planning', 'architecture design', 'incident reconstruction', 'policy analysis'],
    fallbacks: ['perplexity/sonar-pro', 'perplexity/sonar'],
    carbonGPerMTok: 4.76,
  },
];

export const PERPLEXITY_MODEL_COUNT = PERPLEXITY_MODELS.length;

export const MODEL_DOC_perplexity_sonar_pro = {
  id: 'perplexity/sonar-pro',
  summary: 'Sonar Pro via perplexity (perplexity/sonar-pro) is a workhorse Sonar model hosted by perplexity. It speaks openai-chat with a 200,000 token context window and a 8,192 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.75/M. Modalities: text, tools, json, code. Tokenizer: sonar. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer perplexity/sonar-pro when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0135.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_perplexity_sonar = {
  id: 'perplexity/sonar',
  summary: 'Sonar via perplexity (perplexity/sonar) is a utility Sonar model hosted by perplexity. It speaks openai-chat with a 127,000 token context window and a 8,192 token output cap. List price is $1.0/M input tokens and $1.0/M output tokens, with cached input at $0.25/M. Modalities: text, tools, json, code. Tokenizer: sonar. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-01.',
  routingHints: [
    'Prefer perplexity/sonar when quality class is utility and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0025.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_perplexity_sonar_reasoning_pro = {
  id: 'perplexity/sonar-reasoning-pro',
  summary: 'Sonar Reasoning Pro via perplexity (perplexity/sonar-reasoning-pro) is a reasoning Sonar model hosted by perplexity. It speaks openai-chat with a 127,000 token context window and a 8,192 token output cap. List price is $2.0/M input tokens and $8.0/M output tokens, with cached input at $0.5/M. Modalities: text, tools, json, code, reasoning. Tokenizer: sonar. Speed class: slow. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-02.',
  routingHints: [
    'Prefer perplexity/sonar-reasoning-pro when quality class is reasoning and speed class is slow.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.008.',
    'Carbon intensity about 4.76 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 2400,
    expectedP95Ms: 9000,
    errorBudgetPct: 0.5,
  },
};

