import type { Modality, ModelSpec, Protocol } from "../types";

export const SAMBANOVA_MODELS: ModelSpec[] = [
  {
    id: 'sambanova/llama-4-maverick',
    provider: 'sambanova',
    displayName: 'Llama 4 Maverick via sambanova',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.2295,
    outputPerMillion: 0.7225,
    cachedInputPerMillion: 0.0574,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'frontier',
    notes: 'Llama 4 Maverick via sambanova (sambanova/llama-4-maverick) is a frontier Llama model hosted by sambanova. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.2295/M input tokens and $0.7225/M output tokens, with cached input at $0.0574/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['sambanova/llama-4-scout', 'sambanova/llama-3.3-70b', 'sambanova/llama-3.1-8b'],
    carbonGPerMTok: 0.56,
  },
  {
    id: 'sambanova/llama-4-scout',
    provider: 'sambanova',
    displayName: 'Llama 4 Scout via sambanova',
    family: 'Llama',
    release: '2025-04',
    modality: ['text', 'tools', 'json', 'code', 'vision'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPerMillion: 0.153,
    outputPerMillion: 0.5015,
    cachedInputPerMillion: 0.0382,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'workhorse',
    notes: 'Llama 4 Scout via sambanova (sambanova/llama-4-scout) is a workhorse Llama model hosted by sambanova. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.153/M input tokens and $0.5015/M output tokens, with cached input at $0.0382/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['sambanova/llama-3.3-70b', 'sambanova/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'sambanova/llama-3.3-70b',
    provider: 'sambanova',
    displayName: 'Llama 3.3 70B via sambanova',
    family: 'Llama',
    release: '2024-12',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.5015,
    outputPerMillion: 0.6715,
    cachedInputPerMillion: 0.1254,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'workhorse',
    notes: 'Llama 3.3 70B via sambanova (sambanova/llama-3.3-70b) is a workhorse Llama model hosted by sambanova. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.5015/M input tokens and $0.6715/M output tokens, with cached input at $0.1254/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['sambanova/llama-4-scout', 'sambanova/llama-3.1-8b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'sambanova/llama-3.1-8b',
    provider: 'sambanova',
    displayName: 'Llama 3.1 8B via sambanova',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.0425,
    outputPerMillion: 0.068,
    cachedInputPerMillion: 0.0106,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Llama 3.1 8B via sambanova (sambanova/llama-3.1-8b) is a utility Llama model hosted by sambanova. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.0425/M input tokens and $0.068/M output tokens, with cached input at $0.0106/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['sambanova/llama-4-scout', 'sambanova/llama-3.3-70b'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'sambanova/llama-3.1-405b',
    provider: 'sambanova',
    displayName: 'Llama 3.1 405B via sambanova',
    family: 'Llama',
    release: '2024-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 1.5215,
    outputPerMillion: 1.5215,
    cachedInputPerMillion: 0.3804,
    tokenizer: 'llama',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-east', 'us-west', 'eu-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'frontier',
    notes: 'Llama 3.1 405B via sambanova (sambanova/llama-3.1-405b) is a frontier Llama model hosted by sambanova. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.5215/M input tokens and $1.5215/M output tokens, with cached input at $0.3804/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['sambanova/llama-4-scout', 'sambanova/llama-3.3-70b', 'sambanova/llama-3.1-8b'],
    carbonGPerMTok: 0.56,
  },
];

export const SAMBANOVA_MODEL_COUNT = SAMBANOVA_MODELS.length;

export const MODEL_DOC_sambanova_llama_4_maverick = {
  id: 'sambanova/llama-4-maverick',
  summary: 'Llama 4 Maverick via sambanova (sambanova/llama-4-maverick) is a frontier Llama model hosted by sambanova. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.2295/M input tokens and $0.7225/M output tokens, with cached input at $0.0574/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer sambanova/llama-4-maverick when quality class is frontier and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00082.',
    'Carbon intensity about 0.56 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_sambanova_llama_4_scout = {
  id: 'sambanova/llama-4-scout',
  summary: 'Llama 4 Scout via sambanova (sambanova/llama-4-scout) is a workhorse Llama model hosted by sambanova. It speaks openai-chat with a 1,048,576 token context window and a 32,768 token output cap. List price is $0.153/M input tokens and $0.5015/M output tokens, with cached input at $0.0382/M. Modalities: text, tools, json, code, vision. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-04.',
  routingHints: [
    'Prefer sambanova/llama-4-scout when quality class is workhorse and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000557.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_sambanova_llama_3_3_70b = {
  id: 'sambanova/llama-3.3-70b',
  summary: 'Llama 3.3 70B via sambanova (sambanova/llama-3.3-70b) is a workhorse Llama model hosted by sambanova. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.5015/M input tokens and $0.6715/M output tokens, with cached input at $0.1254/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-12.',
  routingHints: [
    'Prefer sambanova/llama-3.3-70b when quality class is workhorse and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.001339.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_sambanova_llama_3_1_8b = {
  id: 'sambanova/llama-3.1-8b',
  summary: 'Llama 3.1 8B via sambanova (sambanova/llama-3.1-8b) is a utility Llama model hosted by sambanova. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.0425/M input tokens and $0.068/M output tokens, with cached input at $0.0106/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer sambanova/llama-3.1-8b when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000119.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_sambanova_llama_3_1_405b = {
  id: 'sambanova/llama-3.1-405b',
  summary: 'Llama 3.1 405B via sambanova (sambanova/llama-3.1-405b) is a frontier Llama model hosted by sambanova. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $1.5215/M input tokens and $1.5215/M output tokens, with cached input at $0.3804/M. Modalities: text, tools, json, code. Tokenizer: llama. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2024-07.',
  routingHints: [
    'Prefer sambanova/llama-3.1-405b when quality class is frontier and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.003804.',
    'Carbon intensity about 0.56 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

