import type { Modality, ModelSpec, Protocol } from "../types";

export const XAI_MODELS: ModelSpec[] = [
  {
    id: 'xai/grok-4.5',
    provider: 'xai',
    displayName: 'Grok 4.5',
    family: 'grok-4',
    release: '2026-01',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 32768,
    inputPerMillion: 3.0,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.75,
    tokenizer: 'grok',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Grok 4.5 (xai/grok-4.5) is a frontier grok-4 model hosted by xai. It speaks openai-chat with a 131,072 token context window and a 32,768 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.75/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: grok. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2026-01.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['xai/grok-3', 'xai/grok-3-mini', 'xai/grok-2'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'xai/grok-4',
    provider: 'xai',
    displayName: 'Grok 4',
    family: 'grok-4',
    release: '2025-07',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 32768,
    inputPerMillion: 3.0,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.75,
    tokenizer: 'grok',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'Grok 4 (xai/grok-4) is a frontier grok-4 model hosted by xai. It speaks openai-chat with a 131,072 token context window and a 32,768 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.75/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: grok. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['xai/grok-3', 'xai/grok-3-mini', 'xai/grok-2'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'xai/grok-3',
    provider: 'xai',
    displayName: 'Grok 3',
    family: 'grok-3',
    release: '2025-02',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 3.0,
    outputPerMillion: 15.0,
    cachedInputPerMillion: 0.75,
    tokenizer: 'grok',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-west'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Grok 3 (xai/grok-3) is a workhorse grok-3 model hosted by xai. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.75/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: grok. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-02.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['xai/grok-3-mini', 'xai/grok-2', 'xai/grok-2-vision'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'xai/grok-3-mini',
    provider: 'xai',
    displayName: 'Grok 3 mini',
    family: 'grok-3',
    release: '2025-02',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.3,
    outputPerMillion: 0.5,
    cachedInputPerMillion: 0.075,
    tokenizer: 'grok',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-west'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'utility',
    notes: 'Grok 3 mini (xai/grok-3-mini) is a utility grok-3 model hosted by xai. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.3/M input tokens and $0.5/M output tokens, with cached input at $0.075/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: grok. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-02.',
    useCases: ['classification', 'extraction', 'cheap RAG rewrite', 'eval judges', 'guardrail pre-filter'],
    fallbacks: ['xai/grok-3', 'xai/grok-2', 'xai/grok-2-vision'],
    carbonGPerMTok: 0.4,
  },
  {
    id: 'xai/grok-2',
    provider: 'xai',
    displayName: 'Grok 2',
    family: 'grok-2',
    release: '2024-08',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 2.0,
    outputPerMillion: 10.0,
    cachedInputPerMillion: undefined,
    tokenizer: 'grok',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-west'],
    status: 'legacy',
    speedClass: 'fast',
    qualityClass: 'workhorse',
    notes: 'Grok 2 (xai/grok-2) is a workhorse grok-2 model hosted by xai. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $2.0/M input tokens and $10.0/M output tokens. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: grok. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: legacy. Released 2024-08.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['xai/grok-3', 'xai/grok-3-mini', 'xai/grok-2-vision'],
    carbonGPerMTok: 0.9,
  },
  {
    id: 'xai/grok-2-vision',
    provider: 'xai',
    displayName: 'Grok 2 Vision',
    family: 'grok-2',
    release: '2024-08',
    modality: ['text', 'vision', 'tools', 'json', 'code', 'reasoning'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 32768,
    maxOutput: 8192,
    inputPerMillion: 2.0,
    outputPerMillion: 10.0,
    cachedInputPerMillion: undefined,
    tokenizer: 'grok',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: true,
    regions: ['us-west'],
    status: 'legacy',
    speedClass: 'standard',
    qualityClass: 'workhorse',
    notes: 'Grok 2 Vision (xai/grok-2-vision) is a workhorse grok-2 model hosted by xai. It speaks openai-chat with a 32,768 token context window and a 8,192 token output cap. List price is $2.0/M input tokens and $10.0/M output tokens. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: grok. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: legacy. Released 2024-08.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: ['xai/grok-3', 'xai/grok-3-mini', 'xai/grok-2'],
    carbonGPerMTok: 1.6,
  },
];

export const XAI_MODEL_COUNT = XAI_MODELS.length;

export const MODEL_DOC_xai_grok_4_5 = {
  id: 'xai/grok-4.5',
  summary: 'Grok 4.5 (xai/grok-4.5) is a frontier grok-4 model hosted by xai. It speaks openai-chat with a 131,072 token context window and a 32,768 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.75/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: grok. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2026-01.',
  routingHints: [
    'Prefer xai/grok-4.5 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0135.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_xai_grok_4 = {
  id: 'xai/grok-4',
  summary: 'Grok 4 (xai/grok-4) is a frontier grok-4 model hosted by xai. It speaks openai-chat with a 131,072 token context window and a 32,768 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.75/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: grok. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
  routingHints: [
    'Prefer xai/grok-4 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0135.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_xai_grok_3 = {
  id: 'xai/grok-3',
  summary: 'Grok 3 (xai/grok-3) is a workhorse grok-3 model hosted by xai. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $3.0/M input tokens and $15.0/M output tokens, with cached input at $0.75/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: grok. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-02.',
  routingHints: [
    'Prefer xai/grok-3 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0135.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_xai_grok_3_mini = {
  id: 'xai/grok-3-mini',
  summary: 'Grok 3 mini (xai/grok-3-mini) is a utility grok-3 model hosted by xai. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.3/M input tokens and $0.5/M output tokens, with cached input at $0.075/M. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: grok. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-02.',
  routingHints: [
    'Prefer xai/grok-3-mini when quality class is utility and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.00085.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.1,
  },
};

export const MODEL_DOC_xai_grok_2 = {
  id: 'xai/grok-2',
  summary: 'Grok 2 (xai/grok-2) is a workhorse grok-2 model hosted by xai. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $2.0/M input tokens and $10.0/M output tokens. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: grok. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: legacy. Released 2024-08.',
  routingHints: [
    'Prefer xai/grok-2 when quality class is workhorse and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.009.',
    'Carbon intensity about 0.9 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_xai_grok_2_vision = {
  id: 'xai/grok-2-vision',
  summary: 'Grok 2 Vision (xai/grok-2-vision) is a workhorse grok-2 model hosted by xai. It speaks openai-chat with a 32,768 token context window and a 8,192 token output cap. List price is $2.0/M input tokens and $10.0/M output tokens. Modalities: text, vision, tools, json, code, reasoning. Tokenizer: grok. Speed class: standard. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: legacy. Released 2024-08.',
  routingHints: [
    'Prefer xai/grok-2-vision when quality class is workhorse and speed class is standard.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.009.',
    'Carbon intensity about 1.6 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 900,
    expectedP95Ms: 3200,
    errorBudgetPct: 0.5,
  },
};

