import type { Modality, ModelSpec, Protocol } from "../types";

export const ZAI_MODELS: ModelSpec[] = [
  {
    id: 'zai/glm-4.5',
    provider: 'zai',
    displayName: 'GLM-4.5 via zai',
    family: 'GLM',
    release: '2025-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 16384,
    inputPerMillion: 0.6,
    outputPerMillion: 2.2,
    cachedInputPerMillion: 0.15,
    tokenizer: 'glm',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-west', 'asia-east'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'GLM-4.5 via zai (zai/glm-4.5) is a frontier GLM model hosted by zai. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.6/M input tokens and $2.2/M output tokens, with cached input at $0.15/M. Modalities: text, tools, json, code. Tokenizer: glm. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['zai/glm-4.5-air'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'zai/glm-4.6',
    provider: 'zai',
    displayName: 'GLM-4.6 via zai',
    family: 'GLM',
    release: '2025-11',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 198000,
    maxOutput: 16384,
    inputPerMillion: 0.5,
    outputPerMillion: 1.8,
    cachedInputPerMillion: 0.125,
    tokenizer: 'glm',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-west', 'asia-east'],
    status: 'ga',
    speedClass: 'fast',
    qualityClass: 'frontier',
    notes: 'GLM-4.6 via zai (zai/glm-4.6) is a frontier GLM model hosted by zai. It speaks openai-chat with a 198,000 token context window and a 16,384 token output cap. List price is $0.5/M input tokens and $1.8/M output tokens, with cached input at $0.125/M. Modalities: text, tools, json, code. Tokenizer: glm. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-11.',
    useCases: ['hard reasoning', 'long-horizon agents', 'research synthesis', 'high-stakes writing', 'multimodal ops'],
    fallbacks: ['zai/glm-4.5-air'],
    carbonGPerMTok: 1.26,
  },
  {
    id: 'zai/glm-4.5-air',
    provider: 'zai',
    displayName: 'GLM-4.5 Air via zai',
    family: 'GLM',
    release: '2025-07',
    modality: ['text', 'tools', 'json', 'code'] as Modality[],
    protocol: 'openai-chat' as Protocol,
    contextWindow: 131072,
    maxOutput: 8192,
    inputPerMillion: 0.13,
    outputPerMillion: 0.85,
    cachedInputPerMillion: 0.0325,
    tokenizer: 'glm',
    streaming: true,
    tools: true,
    jsonMode: true,
    vision: false,
    regions: ['us-west', 'asia-east'],
    status: 'ga',
    speedClass: 'instant',
    qualityClass: 'workhorse',
    notes: 'GLM-4.5 Air via zai (zai/glm-4.5-air) is a workhorse GLM model hosted by zai. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.13/M input tokens and $0.85/M output tokens, with cached input at $0.0325/M. Modalities: text, tools, json, code. Tokenizer: glm. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
    useCases: ['product copilots', 'support replies', 'code review', 'summarization', 'tool-using agents'],
    fallbacks: [],
    carbonGPerMTok: 0.4,
  },
];

export const ZAI_MODEL_COUNT = ZAI_MODELS.length;

export const MODEL_DOC_zai_glm_4_5 = {
  id: 'zai/glm-4.5',
  summary: 'GLM-4.5 via zai (zai/glm-4.5) is a frontier GLM model hosted by zai. It speaks openai-chat with a 131,072 token context window and a 16,384 token output cap. List price is $0.6/M input tokens and $2.2/M output tokens, with cached input at $0.15/M. Modalities: text, tools, json, code. Tokenizer: glm. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
  routingHints: [
    'Prefer zai/glm-4.5 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0023.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_zai_glm_4_6 = {
  id: 'zai/glm-4.6',
  summary: 'GLM-4.6 via zai (zai/glm-4.6) is a frontier GLM model hosted by zai. It speaks openai-chat with a 198,000 token context window and a 16,384 token output cap. List price is $0.5/M input tokens and $1.8/M output tokens, with cached input at $0.125/M. Modalities: text, tools, json, code. Tokenizer: glm. Speed class: fast. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-11.',
  routingHints: [
    'Prefer zai/glm-4.6 when quality class is frontier and speed class is fast.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.0019.',
    'Carbon intensity about 1.26 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 420,
    expectedP95Ms: 1400,
    errorBudgetPct: 0.5,
  },
};

export const MODEL_DOC_zai_glm_4_5_air = {
  id: 'zai/glm-4.5-air',
  summary: 'GLM-4.5 Air via zai (zai/glm-4.5-air) is a workhorse GLM model hosted by zai. It speaks openai-chat with a 131,072 token context window and a 8,192 token output cap. List price is $0.13/M input tokens and $0.85/M output tokens, with cached input at $0.0325/M. Modalities: text, tools, json, code. Tokenizer: glm. Speed class: instant. Hold My Beer treats this as a first-class catalog citizen: budgets reserve against these rates, route pools can pin or exclude it, and the evidence ledger records the alias that selected it without storing prompt bodies. Status: ga. Released 2025-07.',
  routingHints: [
    'Prefer zai/glm-4.5-air when quality class is workhorse and speed class is instant.',
    'Cap max_tokens at 4096 in enforce mode for interactive workloads.',
    'Estimated fully-loaded cost for a 2k/500 turn is $0.000685.',
    'Carbon intensity about 0.4 gCO2e per million tokens on this host.',
    'Compatible protocol openai-chat; do not mix with mismatched route pool targets.',
  ],
  sli: {
    expectedP50Ms: 180,
    expectedP95Ms: 480,
    errorBudgetPct: 0.5,
  },
};

