export interface ReasonDoc { code: string; family: string; summary: string; operatorAction: string; userSafe: boolean; }
export const REASON_DOCS: ReasonDoc[] = [
  {
    code: 'AUTH.MISSING_KEY',
    family: 'AUTH',
    summary: 'No virtual key on the request.',
    operatorAction: 'Inspect the evidence row, then rotate keys.',
    userSafe: true,
  },
  {
    code: 'AUTH.MISSING_KEY.S1',
    family: 'AUTH',
    summary: 'No virtual key on the request. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.MISSING_KEY.S2',
    family: 'AUTH',
    summary: 'No virtual key on the request. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.MISSING_KEY.S3',
    family: 'AUTH',
    summary: 'No virtual key on the request. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.MISSING_KEY.S4',
    family: 'AUTH',
    summary: 'No virtual key on the request. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.MISSING_KEY.S5',
    family: 'AUTH',
    summary: 'No virtual key on the request. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.REVOKED',
    family: 'AUTH',
    summary: 'Virtual key has been revoked.',
    operatorAction: 'Inspect the evidence row, then rotate keys.',
    userSafe: true,
  },
  {
    code: 'AUTH.REVOKED.S1',
    family: 'AUTH',
    summary: 'Virtual key has been revoked. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.REVOKED.S2',
    family: 'AUTH',
    summary: 'Virtual key has been revoked. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.REVOKED.S3',
    family: 'AUTH',
    summary: 'Virtual key has been revoked. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.REVOKED.S4',
    family: 'AUTH',
    summary: 'Virtual key has been revoked. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.REVOKED.S5',
    family: 'AUTH',
    summary: 'Virtual key has been revoked. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.ROLE',
    family: 'AUTH',
    summary: 'Key role cannot invoke this alias.',
    operatorAction: 'Inspect the evidence row, then rotate keys.',
    userSafe: true,
  },
  {
    code: 'AUTH.ROLE.S1',
    family: 'AUTH',
    summary: 'Key role cannot invoke this alias. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.ROLE.S2',
    family: 'AUTH',
    summary: 'Key role cannot invoke this alias. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.ROLE.S3',
    family: 'AUTH',
    summary: 'Key role cannot invoke this alias. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.ROLE.S4',
    family: 'AUTH',
    summary: 'Key role cannot invoke this alias. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'AUTH.ROLE.S5',
    family: 'AUTH',
    summary: 'Key role cannot invoke this alias. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then rotate keys. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.RESERVE_FAIL',
    family: 'BGT',
    summary: 'Atomic reserve against the hard limit failed.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget.',
    userSafe: true,
  },
  {
    code: 'BGT.RESERVE_FAIL.S1',
    family: 'BGT',
    summary: 'Atomic reserve against the hard limit failed. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.RESERVE_FAIL.S2',
    family: 'BGT',
    summary: 'Atomic reserve against the hard limit failed. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.RESERVE_FAIL.S3',
    family: 'BGT',
    summary: 'Atomic reserve against the hard limit failed. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.RESERVE_FAIL.S4',
    family: 'BGT',
    summary: 'Atomic reserve against the hard limit failed. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.RESERVE_FAIL.S5',
    family: 'BGT',
    summary: 'Atomic reserve against the hard limit failed. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.SOFT_ALERT',
    family: 'BGT',
    summary: 'Soft limit crossed; alert only.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget.',
    userSafe: true,
  },
  {
    code: 'BGT.SOFT_ALERT.S1',
    family: 'BGT',
    summary: 'Soft limit crossed; alert only. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.SOFT_ALERT.S2',
    family: 'BGT',
    summary: 'Soft limit crossed; alert only. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.SOFT_ALERT.S3',
    family: 'BGT',
    summary: 'Soft limit crossed; alert only. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.SOFT_ALERT.S4',
    family: 'BGT',
    summary: 'Soft limit crossed; alert only. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.SOFT_ALERT.S5',
    family: 'BGT',
    summary: 'Soft limit crossed; alert only. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.DEGRADE',
    family: 'BGT',
    summary: 'Hard limit near; degraded to a cheaper target.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget.',
    userSafe: true,
  },
  {
    code: 'BGT.DEGRADE.S1',
    family: 'BGT',
    summary: 'Hard limit near; degraded to a cheaper target. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.DEGRADE.S2',
    family: 'BGT',
    summary: 'Hard limit near; degraded to a cheaper target. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.DEGRADE.S3',
    family: 'BGT',
    summary: 'Hard limit near; degraded to a cheaper target. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.DEGRADE.S4',
    family: 'BGT',
    summary: 'Hard limit near; degraded to a cheaper target. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.DEGRADE.S5',
    family: 'BGT',
    summary: 'Hard limit near; degraded to a cheaper target. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.TOKEN_CAP',
    family: 'BGT',
    summary: 'max_tokens reduced to the policy cap.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget.',
    userSafe: true,
  },
  {
    code: 'BGT.TOKEN_CAP.S1',
    family: 'BGT',
    summary: 'max_tokens reduced to the policy cap. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.TOKEN_CAP.S2',
    family: 'BGT',
    summary: 'max_tokens reduced to the policy cap. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.TOKEN_CAP.S3',
    family: 'BGT',
    summary: 'max_tokens reduced to the policy cap. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.TOKEN_CAP.S4',
    family: 'BGT',
    summary: 'max_tokens reduced to the policy cap. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.TOKEN_CAP.S5',
    family: 'BGT',
    summary: 'max_tokens reduced to the policy cap. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.PREPAID_EMPTY',
    family: 'BGT',
    summary: 'Prepaid wallet is at zero.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget.',
    userSafe: true,
  },
  {
    code: 'BGT.PREPAID_EMPTY.S1',
    family: 'BGT',
    summary: 'Prepaid wallet is at zero. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.PREPAID_EMPTY.S2',
    family: 'BGT',
    summary: 'Prepaid wallet is at zero. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.PREPAID_EMPTY.S3',
    family: 'BGT',
    summary: 'Prepaid wallet is at zero. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.PREPAID_EMPTY.S4',
    family: 'BGT',
    summary: 'Prepaid wallet is at zero. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'BGT.PREPAID_EMPTY.S5',
    family: 'BGT',
    summary: 'Prepaid wallet is at zero. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then raise or reallocate budget. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.DENY_MODEL',
    family: 'POL',
    summary: 'Requested model is not on the allow list.',
    operatorAction: 'Inspect the evidence row, then adjust the pack.',
    userSafe: true,
  },
  {
    code: 'POL.DENY_MODEL.S1',
    family: 'POL',
    summary: 'Requested model is not on the allow list. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.DENY_MODEL.S2',
    family: 'POL',
    summary: 'Requested model is not on the allow list. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.DENY_MODEL.S3',
    family: 'POL',
    summary: 'Requested model is not on the allow list. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.DENY_MODEL.S4',
    family: 'POL',
    summary: 'Requested model is not on the allow list. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.DENY_MODEL.S5',
    family: 'POL',
    summary: 'Requested model is not on the allow list. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.DENY_PROVIDER',
    family: 'POL',
    summary: 'Provider is blocked for this workload.',
    operatorAction: 'Inspect the evidence row, then adjust the pack.',
    userSafe: true,
  },
  {
    code: 'POL.DENY_PROVIDER.S1',
    family: 'POL',
    summary: 'Provider is blocked for this workload. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.DENY_PROVIDER.S2',
    family: 'POL',
    summary: 'Provider is blocked for this workload. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.DENY_PROVIDER.S3',
    family: 'POL',
    summary: 'Provider is blocked for this workload. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.DENY_PROVIDER.S4',
    family: 'POL',
    summary: 'Provider is blocked for this workload. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.DENY_PROVIDER.S5',
    family: 'POL',
    summary: 'Provider is blocked for this workload. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.REGION',
    family: 'POL',
    summary: 'Target region is outside the lock.',
    operatorAction: 'Inspect the evidence row, then adjust the pack.',
    userSafe: true,
  },
  {
    code: 'POL.REGION.S1',
    family: 'POL',
    summary: 'Target region is outside the lock. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.REGION.S2',
    family: 'POL',
    summary: 'Target region is outside the lock. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.REGION.S3',
    family: 'POL',
    summary: 'Target region is outside the lock. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.REGION.S4',
    family: 'POL',
    summary: 'Target region is outside the lock. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.REGION.S5',
    family: 'POL',
    summary: 'Target region is outside the lock. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.TOOLS',
    family: 'POL',
    summary: 'Tool name is not on the allow list.',
    operatorAction: 'Inspect the evidence row, then adjust the pack.',
    userSafe: true,
  },
  {
    code: 'POL.TOOLS.S1',
    family: 'POL',
    summary: 'Tool name is not on the allow list. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.TOOLS.S2',
    family: 'POL',
    summary: 'Tool name is not on the allow list. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.TOOLS.S3',
    family: 'POL',
    summary: 'Tool name is not on the allow list. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.TOOLS.S4',
    family: 'POL',
    summary: 'Tool name is not on the allow list. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.TOOLS.S5',
    family: 'POL',
    summary: 'Tool name is not on the allow list. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.CONTENT',
    family: 'POL',
    summary: 'Content filter fired.',
    operatorAction: 'Inspect the evidence row, then adjust the pack.',
    userSafe: true,
  },
  {
    code: 'POL.CONTENT.S1',
    family: 'POL',
    summary: 'Content filter fired. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.CONTENT.S2',
    family: 'POL',
    summary: 'Content filter fired. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.CONTENT.S3',
    family: 'POL',
    summary: 'Content filter fired. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.CONTENT.S4',
    family: 'POL',
    summary: 'Content filter fired. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.CONTENT.S5',
    family: 'POL',
    summary: 'Content filter fired. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.ENV',
    family: 'POL',
    summary: 'Environment mismatch (prod key on lab alias).',
    operatorAction: 'Inspect the evidence row, then adjust the pack.',
    userSafe: true,
  },
  {
    code: 'POL.ENV.S1',
    family: 'POL',
    summary: 'Environment mismatch (prod key on lab alias). Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.ENV.S2',
    family: 'POL',
    summary: 'Environment mismatch (prod key on lab alias). Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.ENV.S3',
    family: 'POL',
    summary: 'Environment mismatch (prod key on lab alias). Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.ENV.S4',
    family: 'POL',
    summary: 'Environment mismatch (prod key on lab alias). Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'POL.ENV.S5',
    family: 'POL',
    summary: 'Environment mismatch (prod key on lab alias). Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then adjust the pack. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'SEC.JAILBREAK',
    family: 'SEC',
    summary: 'Jailbreak detector fired.',
    operatorAction: 'Inspect the evidence row, then review the route pool.',
    userSafe: true,
  },
  {
    code: 'SEC.JAILBREAK.S1',
    family: 'SEC',
    summary: 'Jailbreak detector fired. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'SEC.JAILBREAK.S2',
    family: 'SEC',
    summary: 'Jailbreak detector fired. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'SEC.JAILBREAK.S3',
    family: 'SEC',
    summary: 'Jailbreak detector fired. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'SEC.JAILBREAK.S4',
    family: 'SEC',
    summary: 'Jailbreak detector fired. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'SEC.JAILBREAK.S5',
    family: 'SEC',
    summary: 'Jailbreak detector fired. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'SEC.PII',
    family: 'SEC',
    summary: 'PII redaction applied on metadata only.',
    operatorAction: 'Inspect the evidence row, then review the route pool.',
    userSafe: true,
  },
  {
    code: 'SEC.PII.S1',
    family: 'SEC',
    summary: 'PII redaction applied on metadata only. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'SEC.PII.S2',
    family: 'SEC',
    summary: 'PII redaction applied on metadata only. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'SEC.PII.S3',
    family: 'SEC',
    summary: 'PII redaction applied on metadata only. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'SEC.PII.S4',
    family: 'SEC',
    summary: 'PII redaction applied on metadata only. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'SEC.PII.S5',
    family: 'SEC',
    summary: 'PII redaction applied on metadata only. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.SELECTED',
    family: 'RTE',
    summary: 'Target selected by the pool strategy.',
    operatorAction: 'Inspect the evidence row, then review the route pool.',
    userSafe: true,
  },
  {
    code: 'RTE.SELECTED.S1',
    family: 'RTE',
    summary: 'Target selected by the pool strategy. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.SELECTED.S2',
    family: 'RTE',
    summary: 'Target selected by the pool strategy. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.SELECTED.S3',
    family: 'RTE',
    summary: 'Target selected by the pool strategy. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.SELECTED.S4',
    family: 'RTE',
    summary: 'Target selected by the pool strategy. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.SELECTED.S5',
    family: 'RTE',
    summary: 'Target selected by the pool strategy. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.FAILOVER',
    family: 'RTE',
    summary: 'Primary target failed; next eligible used.',
    operatorAction: 'Inspect the evidence row, then review the route pool.',
    userSafe: true,
  },
  {
    code: 'RTE.FAILOVER.S1',
    family: 'RTE',
    summary: 'Primary target failed; next eligible used. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.FAILOVER.S2',
    family: 'RTE',
    summary: 'Primary target failed; next eligible used. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.FAILOVER.S3',
    family: 'RTE',
    summary: 'Primary target failed; next eligible used. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.FAILOVER.S4',
    family: 'RTE',
    summary: 'Primary target failed; next eligible used. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.FAILOVER.S5',
    family: 'RTE',
    summary: 'Primary target failed; next eligible used. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.CIRCUIT_OPEN',
    family: 'RTE',
    summary: 'Circuit is open on this target.',
    operatorAction: 'Inspect the evidence row, then review the route pool.',
    userSafe: true,
  },
  {
    code: 'RTE.CIRCUIT_OPEN.S1',
    family: 'RTE',
    summary: 'Circuit is open on this target. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.CIRCUIT_OPEN.S2',
    family: 'RTE',
    summary: 'Circuit is open on this target. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.CIRCUIT_OPEN.S3',
    family: 'RTE',
    summary: 'Circuit is open on this target. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.CIRCUIT_OPEN.S4',
    family: 'RTE',
    summary: 'Circuit is open on this target. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.CIRCUIT_OPEN.S5',
    family: 'RTE',
    summary: 'Circuit is open on this target. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.NO_ELIGIBLE',
    family: 'RTE',
    summary: 'No target survived policy + health + budget.',
    operatorAction: 'Inspect the evidence row, then review the route pool.',
    userSafe: true,
  },
  {
    code: 'RTE.NO_ELIGIBLE.S1',
    family: 'RTE',
    summary: 'No target survived policy + health + budget. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.NO_ELIGIBLE.S2',
    family: 'RTE',
    summary: 'No target survived policy + health + budget. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.NO_ELIGIBLE.S3',
    family: 'RTE',
    summary: 'No target survived policy + health + budget. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.NO_ELIGIBLE.S4',
    family: 'RTE',
    summary: 'No target survived policy + health + budget. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.NO_ELIGIBLE.S5',
    family: 'RTE',
    summary: 'No target survived policy + health + budget. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.ALIAS_MISS',
    family: 'RTE',
    summary: 'Unknown route alias.',
    operatorAction: 'Inspect the evidence row, then review the route pool.',
    userSafe: true,
  },
  {
    code: 'RTE.ALIAS_MISS.S1',
    family: 'RTE',
    summary: 'Unknown route alias. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.ALIAS_MISS.S2',
    family: 'RTE',
    summary: 'Unknown route alias. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.ALIAS_MISS.S3',
    family: 'RTE',
    summary: 'Unknown route alias. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.ALIAS_MISS.S4',
    family: 'RTE',
    summary: 'Unknown route alias. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'RTE.ALIAS_MISS.S5',
    family: 'RTE',
    summary: 'Unknown route alias. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.UNHEALTHY',
    family: 'HLT',
    summary: 'Provider health probe is failing.',
    operatorAction: 'Inspect the evidence row, then check upstream status.',
    userSafe: true,
  },
  {
    code: 'HLT.UNHEALTHY.S1',
    family: 'HLT',
    summary: 'Provider health probe is failing. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.UNHEALTHY.S2',
    family: 'HLT',
    summary: 'Provider health probe is failing. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.UNHEALTHY.S3',
    family: 'HLT',
    summary: 'Provider health probe is failing. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.UNHEALTHY.S4',
    family: 'HLT',
    summary: 'Provider health probe is failing. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.UNHEALTHY.S5',
    family: 'HLT',
    summary: 'Provider health probe is failing. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.QUOTA',
    family: 'HLT',
    summary: 'Upstream 429.',
    operatorAction: 'Inspect the evidence row, then check upstream status.',
    userSafe: true,
  },
  {
    code: 'HLT.QUOTA.S1',
    family: 'HLT',
    summary: 'Upstream 429. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.QUOTA.S2',
    family: 'HLT',
    summary: 'Upstream 429. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.QUOTA.S3',
    family: 'HLT',
    summary: 'Upstream 429. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.QUOTA.S4',
    family: 'HLT',
    summary: 'Upstream 429. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.QUOTA.S5',
    family: 'HLT',
    summary: 'Upstream 429. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.UPSTREAM_5XX',
    family: 'HLT',
    summary: 'Upstream 5xx.',
    operatorAction: 'Inspect the evidence row, then check upstream status.',
    userSafe: true,
  },
  {
    code: 'HLT.UPSTREAM_5XX.S1',
    family: 'HLT',
    summary: 'Upstream 5xx. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.UPSTREAM_5XX.S2',
    family: 'HLT',
    summary: 'Upstream 5xx. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.UPSTREAM_5XX.S3',
    family: 'HLT',
    summary: 'Upstream 5xx. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.UPSTREAM_5XX.S4',
    family: 'HLT',
    summary: 'Upstream 5xx. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.UPSTREAM_5XX.S5',
    family: 'HLT',
    summary: 'Upstream 5xx. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.TIMEOUT',
    family: 'HLT',
    summary: 'Upstream exceeded the timeout.',
    operatorAction: 'Inspect the evidence row, then check upstream status.',
    userSafe: true,
  },
  {
    code: 'HLT.TIMEOUT.S1',
    family: 'HLT',
    summary: 'Upstream exceeded the timeout. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.TIMEOUT.S2',
    family: 'HLT',
    summary: 'Upstream exceeded the timeout. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.TIMEOUT.S3',
    family: 'HLT',
    summary: 'Upstream exceeded the timeout. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.TIMEOUT.S4',
    family: 'HLT',
    summary: 'Upstream exceeded the timeout. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'HLT.TIMEOUT.S5',
    family: 'HLT',
    summary: 'Upstream exceeded the timeout. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then check upstream status. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.HIT',
    family: 'CCH',
    summary: 'Exact cache hit.',
    operatorAction: 'Inspect the evidence row, then review the route pool.',
    userSafe: true,
  },
  {
    code: 'CCH.HIT.S1',
    family: 'CCH',
    summary: 'Exact cache hit. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.HIT.S2',
    family: 'CCH',
    summary: 'Exact cache hit. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.HIT.S3',
    family: 'CCH',
    summary: 'Exact cache hit. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.HIT.S4',
    family: 'CCH',
    summary: 'Exact cache hit. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.HIT.S5',
    family: 'CCH',
    summary: 'Exact cache hit. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.MISS',
    family: 'CCH',
    summary: 'Cache miss.',
    operatorAction: 'Inspect the evidence row, then review the route pool.',
    userSafe: true,
  },
  {
    code: 'CCH.MISS.S1',
    family: 'CCH',
    summary: 'Cache miss. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.MISS.S2',
    family: 'CCH',
    summary: 'Cache miss. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.MISS.S3',
    family: 'CCH',
    summary: 'Cache miss. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.MISS.S4',
    family: 'CCH',
    summary: 'Cache miss. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.MISS.S5',
    family: 'CCH',
    summary: 'Cache miss. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.BYPASS',
    family: 'CCH',
    summary: 'Streaming or tools bypassed cache.',
    operatorAction: 'Inspect the evidence row, then review the route pool.',
    userSafe: true,
  },
  {
    code: 'CCH.BYPASS.S1',
    family: 'CCH',
    summary: 'Streaming or tools bypassed cache. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.BYPASS.S2',
    family: 'CCH',
    summary: 'Streaming or tools bypassed cache. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.BYPASS.S3',
    family: 'CCH',
    summary: 'Streaming or tools bypassed cache. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.BYPASS.S4',
    family: 'CCH',
    summary: 'Streaming or tools bypassed cache. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'CCH.BYPASS.S5',
    family: 'CCH',
    summary: 'Streaming or tools bypassed cache. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'LAB.SIMULATED',
    family: 'LAB',
    summary: 'Served by the Test Lab simulator.',
    operatorAction: 'Inspect the evidence row, then review the route pool.',
    userSafe: true,
  },
  {
    code: 'LAB.SIMULATED.S1',
    family: 'LAB',
    summary: 'Served by the Test Lab simulator. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'LAB.SIMULATED.S2',
    family: 'LAB',
    summary: 'Served by the Test Lab simulator. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'LAB.SIMULATED.S3',
    family: 'LAB',
    summary: 'Served by the Test Lab simulator. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'LAB.SIMULATED.S4',
    family: 'LAB',
    summary: 'Served by the Test Lab simulator. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'LAB.SIMULATED.S5',
    family: 'LAB',
    summary: 'Served by the Test Lab simulator. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'LAB.LIVE_XAI',
    family: 'LAB',
    summary: 'Served live via the xAI lab path.',
    operatorAction: 'Inspect the evidence row, then review the route pool.',
    userSafe: true,
  },
  {
    code: 'LAB.LIVE_XAI.S1',
    family: 'LAB',
    summary: 'Served live via the xAI lab path. Scenario 1: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'LAB.LIVE_XAI.S2',
    family: 'LAB',
    summary: 'Served live via the xAI lab path. Scenario 2: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'LAB.LIVE_XAI.S3',
    family: 'LAB',
    summary: 'Served live via the xAI lab path. Scenario 3: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'LAB.LIVE_XAI.S4',
    family: 'LAB',
    summary: 'Served live via the xAI lab path. Scenario 4: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
  {
    code: 'LAB.LIVE_XAI.S5',
    family: 'LAB',
    summary: 'Served live via the xAI lab path. Scenario 5: workload isolation, replay-safe, no prompt body.',
    operatorAction: 'Inspect the evidence row, then review the route pool. Scenario playbooks live in docs/reason-codes.md.',
    userSafe: true,
  },
];
export function reasonDoc(code: string): ReasonDoc | undefined {
  return REASON_DOCS.find((r) => r.code === code || r.code.startsWith(code));
}
