/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleAlertsRouteImport } from './routes/console.alerts'
import { Route as ConsoleEvidenceRouteImport } from './routes/console.evidence'
import { Route as ConsoleFinopsRouteImport } from './routes/console.finops'
import { Route as ConsoleKeysRouteImport } from './routes/console.keys'
import { Route as ConsoleLabRouteImport } from './routes/console.lab'
import { Route as ConsoleModelsRouteImport } from './routes/console.models'
import { Route as ConsolePoliciesRouteImport } from './routes/console.policies'
import { Route as ConsoleRoutesRouteImport } from './routes/console.routes'
import { Route as ConsoleSettingsRouteImport } from './routes/console.settings'
import { Route as ConsoleSpendRouteImport } from './routes/console.spend'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/console/',
  path: '/console/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAlertsRoute = ConsoleAlertsRouteImport.update({
  id: '/console/alerts',
  path: '/console/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleEvidenceRoute = ConsoleEvidenceRouteImport.update({
  id: '/console/evidence',
  path: '/console/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleFinopsRoute = ConsoleFinopsRouteImport.update({
  id: '/console/finops',
  path: '/console/finops',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleKeysRoute = ConsoleKeysRouteImport.update({
  id: '/console/keys',
  path: '/console/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleLabRoute = ConsoleLabRouteImport.update({
  id: '/console/lab',
  path: '/console/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleModelsRoute = ConsoleModelsRouteImport.update({
  id: '/console/models',
  path: '/console/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolePoliciesRoute = ConsolePoliciesRouteImport.update({
  id: '/console/policies',
  path: '/console/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoutesRoute = ConsoleRoutesRouteImport.update({
  id: '/console/routes',
  path: '/console/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/console/settings',
  path: '/console/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleSpendRoute = ConsoleSpendRouteImport.update({
  id: '/console/spend',
  path: '/console/spend',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/console/alerts': typeof ConsoleAlertsRoute
  '/console/evidence': typeof ConsoleEvidenceRoute
  '/console/finops': typeof ConsoleFinopsRoute
  '/console/keys': typeof ConsoleKeysRoute
  '/console/lab': typeof ConsoleLabRoute
  '/console/models': typeof ConsoleModelsRoute
  '/console/policies': typeof ConsolePoliciesRoute
  '/console/routes': typeof ConsoleRoutesRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/spend': typeof ConsoleSpendRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/console/': typeof ConsoleIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/console/alerts': typeof ConsoleAlertsRoute
  '/console/evidence': typeof ConsoleEvidenceRoute
  '/console/finops': typeof ConsoleFinopsRoute
  '/console/keys': typeof ConsoleKeysRoute
  '/console/lab': typeof ConsoleLabRoute
  '/console/models': typeof ConsoleModelsRoute
  '/console/policies': typeof ConsolePoliciesRoute
  '/console/routes': typeof ConsoleRoutesRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/spend': typeof ConsoleSpendRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/console': typeof ConsoleIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/console/alerts': typeof ConsoleAlertsRoute
  '/console/evidence': typeof ConsoleEvidenceRoute
  '/console/finops': typeof ConsoleFinopsRoute
  '/console/keys': typeof ConsoleKeysRoute
  '/console/lab': typeof ConsoleLabRoute
  '/console/models': typeof ConsoleModelsRoute
  '/console/policies': typeof ConsolePoliciesRoute
  '/console/routes': typeof ConsoleRoutesRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/spend': typeof ConsoleSpendRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/console/': typeof ConsoleIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/models'
    | '/pricing'
    | '/security'
    | '/console/alerts'
    | '/console/evidence'
    | '/console/finops'
    | '/console/keys'
    | '/console/lab'
    | '/console/models'
    | '/console/policies'
    | '/console/routes'
    | '/console/settings'
    | '/console/spend'
    | '/docs/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/console/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/models'
    | '/pricing'
    | '/security'
    | '/console/alerts'
    | '/console/evidence'
    | '/console/finops'
    | '/console/keys'
    | '/console/lab'
    | '/console/models'
    | '/console/policies'
    | '/console/routes'
    | '/console/settings'
    | '/console/spend'
    | '/docs/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/console'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/models'
    | '/pricing'
    | '/security'
    | '/console/alerts'
    | '/console/evidence'
    | '/console/finops'
    | '/console/keys'
    | '/console/lab'
    | '/console/models'
    | '/console/policies'
    | '/console/routes'
    | '/console/settings'
    | '/console/spend'
    | '/docs/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/console/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ModelsRoute: typeof ModelsRoute
  PricingRoute: typeof PricingRoute
  SecurityRoute: typeof SecurityRoute
  ConsoleAlertsRoute: typeof ConsoleAlertsRoute
  ConsoleEvidenceRoute: typeof ConsoleEvidenceRoute
  ConsoleFinopsRoute: typeof ConsoleFinopsRoute
  ConsoleKeysRoute: typeof ConsoleKeysRoute
  ConsoleLabRoute: typeof ConsoleLabRoute
  ConsoleModelsRoute: typeof ConsoleModelsRoute
  ConsolePoliciesRoute: typeof ConsolePoliciesRoute
  ConsoleRoutesRoute: typeof ConsoleRoutesRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleSpendRoute: typeof ConsoleSpendRoute
  DocsSlugRoute: typeof DocsSlugRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/console'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/alerts': {
      id: '/console/alerts'
      path: '/console/alerts'
      fullPath: '/console/alerts'
      preLoaderRoute: typeof ConsoleAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/evidence': {
      id: '/console/evidence'
      path: '/console/evidence'
      fullPath: '/console/evidence'
      preLoaderRoute: typeof ConsoleEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/finops': {
      id: '/console/finops'
      path: '/console/finops'
      fullPath: '/console/finops'
      preLoaderRoute: typeof ConsoleFinopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/keys': {
      id: '/console/keys'
      path: '/console/keys'
      fullPath: '/console/keys'
      preLoaderRoute: typeof ConsoleKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/lab': {
      id: '/console/lab'
      path: '/console/lab'
      fullPath: '/console/lab'
      preLoaderRoute: typeof ConsoleLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/models': {
      id: '/console/models'
      path: '/console/models'
      fullPath: '/console/models'
      preLoaderRoute: typeof ConsoleModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/policies': {
      id: '/console/policies'
      path: '/console/policies'
      fullPath: '/console/policies'
      preLoaderRoute: typeof ConsolePoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/routes': {
      id: '/console/routes'
      path: '/console/routes'
      fullPath: '/console/routes'
      preLoaderRoute: typeof ConsoleRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/settings': {
      id: '/console/settings'
      path: '/console/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/spend': {
      id: '/console/spend'
      path: '/console/spend'
      fullPath: '/console/spend'
      preLoaderRoute: typeof ConsoleSpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ModelsRoute: ModelsRoute,
  PricingRoute: PricingRoute,
  SecurityRoute: SecurityRoute,
  ConsoleAlertsRoute: ConsoleAlertsRoute,
  ConsoleEvidenceRoute: ConsoleEvidenceRoute,
  ConsoleFinopsRoute: ConsoleFinopsRoute,
  ConsoleKeysRoute: ConsoleKeysRoute,
  ConsoleLabRoute: ConsoleLabRoute,
  ConsoleModelsRoute: ConsoleModelsRoute,
  ConsolePoliciesRoute: ConsolePoliciesRoute,
  ConsoleRoutesRoute: ConsoleRoutesRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleSpendRoute: ConsoleSpendRoute,
  DocsSlugRoute: DocsSlugRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
